#!/bin/sh -eux

ub_compile \
	--libdir=/usr/lib \
	--includedir=/usr/include \
	--with-shared \
	--with-cxx-binding \
	--with-cxx-shared \
	--disable-termcap \
	--enable-widec \
	--enable-pc-files \
	--with-pkg-config-libdir=/usr/lib/pkgconfig \
	--with-fallbacks="vt100,ansi,linux,xterm,screen"
