#!/bin/sh -eux

ub_compile \
	--libdir=/usr/lib \
	--with-shared \
	--disable-termcap \
	--enable-pc-files \
	--with-pkg-config-libdir=/usr/lib/pkgconfig \
	--with-fallbacks="vt100,ansi,linux,xterm,screen"

mkdir Install
UB_MAKEINSTALL_PREFIX="$UB_COMPILEDIR"/Install ub_install

# build widec
ub_compile \
	--libdir=/usr/lib \
	--includedir=/usr/include/ncursesw \
	--with-shared \
	--disable-termcap \
	--enable-widec \
	--enable-pc-files \
	--with-pkg-config-libdir=/usr/lib/pkgconfig \
	--with-fallbacks="vt100,ansi,linux,xterm,screen"
