#!/bin/sh -eux

ub_install

# remove not installed static libs and non-existent -lwayland_protocol from pc files
for staticlib in buildsystem draw_opt ector_opt evas_opt http-parser libunibreak lz4 triangulator wayland_protocol; do
    sed -i -e "s/-l$staticlib//g" $UB_INSTALLDIR/usr/lib/pkgconfig/*.pc
done
