#!/bin/sh -eux

ub_compile \
	-DSTK_INSTALL_BINARY_DIR=/usr/bin \
	-DSTK_INSTALL_DATA_DIR=/usr/share/supertuxkart \
	-DUSE_WIIUSE=no \
	-DBUILD_RECORDER=0 \
	-DCMAKE_CXX_FLAGS="-lpthread -lm -ldl -lGLU"
