#!/bin/sh -eux

ub_compile \
	-DCMAKE_PREFIX_PATH=/usr/lib/qt5 \
	-DKDE_INSTALL_USE_QT_SYS_PATHS=ON \
	-DBUILD_TESTING=OFF \
	-DCMAKE_BUILD_TYPE=Release \
	-DWITH_GTK3_VERSION:STRING="$(pkg-config --modversion gtk+-3.0)"
