#!/bin/sh -eux

cd "$UB_OBJECTDIR"

# The glibc 2.26 supports kernel versions 3.2.0 and above only.

UB_CONFIGURE_DIR="$UB_COMPILEDIR" ub_configure \
	--with-headers=/usr/include \
	--with-tls \
	--enable-add-ons \
	--enable-kernel=3.2.0 \
	--enable-obsolete-rpc \
	--enable-obsolete-nsl \
	--disable-werror \
	--disable-timezone-tools \
	--enable-bind-now \
	--enable-cet \
	--disable-profile \
	--enable-lock-elision \
	--enable-stack-protector=strong \
	libc_cv_slibdir=/usr/lib \
	libc_cv_rtlddir=/usr/lib

# glibc doesn't like -Os!
# build failures with -O1 maybe gcc bug:
# https://sourceware.org/bugzilla/show_bug.cgi?id=19444
ub_make \
	CFLAGS="-O2 -mtune=generic" \
	user-defined-trusted-dirs=/usr/local/lib
