#!/bin/sh -eux

cd "$UB_OBJECTDIR"

touch "$UB_INSTALLDIR"/etc/ld.so.conf
mkdir -p "$UB_INSTALLDIR"/usr/lib/gconv
touch "$UB_INSTALLDIR"/usr/lib/gconv/gconv-modules.cache
make \
	install_root="$UB_INSTALLDIR" \
	install
make \
	install_root="$UB_INSTALLDIR" \
	localedata/install-locales

mv "$UB_INSTALLDIR"/sbin/{ldconfig,sln} "$UB_INSTALLDIR"/usr/sbin
rm -rf "$UB_INSTALLDIR"/sbin

cp -p "$UB_COMPILEDIR"/nscd/nscd.conf    "$UB_INSTALLDIR"/etc/
cp -p "$UB_COMPILEDIR"/nss/nsswitch.conf "$UB_INSTALLDIR"/etc/
cp -p "$UB_COMPILEDIR"/posix/gai.conf    "$UB_INSTALLDIR"/etc/

rm -f "$UB_INSTALLDIR"/etc/ld.so.cache
rm -f "$UB_INSTALLDIR"/usr/libexec/pt_chown

# install nscd init scripts
mkdir -p "$UB_INSTALLDIR"/usr/lib/tmpfiles.d/
install -m 644 "$UB_COMPILEDIR"/nscd/nscd.tmpfiles "$UB_INSTALLDIR"/usr/lib/tmpfiles.d/nscd.conf
install -m 644 "$UB_COMPILEDIR"/nscd/nscd.service "$UB_INSTALLDIR"/usr/lib/systemd/system

# compat symlinks
ln -sT lib "$UB_INSTALLDIR"/lib64

# freepascalnak
ln -s /usr/lib/crt1.o ${UB_INSTALLDIR}/lib/crti1.o
ln -s /usr/lib/crti.o ${UB_INSTALLDIR}/lib/crti.o
ln -s /usr/lib/crtn.o ${UB_INSTALLDIR}/lib/crtn.o
ln -s /usr/lib/gcrt1.o ${UB_INSTALLDIR}/lib/gcrt1.o
