#!/bin/sh -eux

cd "$UB_OBJECTDIR"

touch "$UB_INSTALLDIR"/etc/ld.so.conf
mkdir -p "$UB_INSTALLDIR"/usr/lib/gconv
touch "$UB_INSTALLDIR"/usr/lib/gconv/gconv-modules.cache
make \
	install_root="$UB_INSTALLDIR" \
	install
make \
	install_root="$UB_INSTALLDIR" \
	localedata/install-locales

cp -p "$UB_COMPILEDIR"/nscd/nscd.conf    "$UB_INSTALLDIR"/etc/
cp -p "$UB_COMPILEDIR"/nss/nsswitch.conf "$UB_INSTALLDIR"/etc/
cp -p "$UB_COMPILEDIR"/posix/gai.conf    "$UB_INSTALLDIR"/etc/

rm -f "$UB_INSTALLDIR"/etc/ld.so.cache
rm -f "$UB_INSTALLDIR"/usr/libexec/pt_chown

# install nscd init scripts
mkdir -p "$UB_INSTALLDIR"/usr/lib/tmpfiles.d/
install -m 644 "$UB_COMPILEDIR"/nscd/nscd.tmpfiles "$UB_INSTALLDIR"/usr/lib/tmpfiles.d/nscd.conf
install -m 644 "$UB_COMPILEDIR"/nscd/nscd.service "$UB_INSTALLDIR"/usr/lib/systemd/system

# compat symlinks
ln -sT lib "$UB_INSTALLDIR"/lib64
