#!/bin/sh -eux

cd epson-printer-utility-${UB_VERSION}
ub_install
mkdir -p $UB_INSTALLDIR/usr/lib/udev/rules.d
cp PrinterUtility/epson-printer-utility $UB_INSTALLDIR/usr/bin/
cp support-tool/79-udev-epson.rules $UB_INSTALLDIR/usr/lib/udev/rules.d/

cd ../epson-backend-${UB_VERSION}
ub_install

# rm -Rf $UB_INSTALLDIR/usr/include
rm -Rf $UB_INSTALLDIR/usr/lib/epson-backend/{rc.d,scripts}
rm -Rf $UB_INSTALLDIR/usr/resource
