#!/bin/sh -eux

ub_configure \
	--enable-cups \
	--with-drivers=ALL \
	--with-ijs \
	--with-fontpath="/usr/share/fonts/ghostscript:/usr/share/fonts/Type1:/usr/share/fonts/truetype" \
	--with-system-libtiff

ub_make so

cd ijs
autoreconf -ivf
ub_compile
