#!/bin/sh -eux

rm -r  cups/libs jpeg libpng tiff zlib
cd ijs
libtoolize
cd ..
ub_configure \
	--enable-dynamic \
	--with-ijs \
	--with-drivers=ALL \
	--with-fontpath="/usr/share/fonts/ghostscript:/usr/share/fonts/Type1:/usr/share/fonts/truetype" \
	--enable-fontconfig \
	--enable-freetype \
	--enable-openjpeg \
	--with-system-libtiff \
	--disable-compile-inits

ub_make so

cd ijs
ub_compile
