#!/bin/sh -eux

mkdir -p "${UB_INSTALLDIR}/usr/share/doc/fvwm"
ub_install
install -D -m644 sample.fvwmrc/{decor_examples,DecorMwm,DecorWin95,new-features,system.*} \
	"${UB_INSTALLDIR}/usr/share/doc/fvwm"
