#!/bin/sh -eux

ub_make DESTDIR=/var/uhubuild/work/install LIB_DIR=/usr/lib install install_systemd

mkdir -p ${UB_INSTALLDIR}/etc/iscsi
cp etc/iscsid.conf ${UB_INSTALLDIR}/etc/iscsi/
echo -n > ${UB_INSTALLDIR}/etc/iscsi/initiatorname.iscsi

mv "$UB_INSTALLDIR"/sbin "$UB_INSTALLDIR"/usr/
rm -rf "$UB_INSTALLDIR"/usr/lib/pkgconfig
