#!/bin/sh -eux

mkdir -p ${UB_INSTALLDIR}/usr/share/{applications,appdata,doc/alacritty/example,bash-completion/completions,zsh/site-functions,fish/completions,pixmaps}
cp target/release/alacritty ${UB_INSTALLDIR}/usr/bin/alacritty.bin
cp extra/alacritty.man ${UB_INSTALLDIR}/usr/share/man/man1/alacritty.1
cp extra/linux/Alacritty.desktop ${UB_INSTALLDIR}/usr/share/applications/
cp extra/linux/org.alacritty.Alacritty.appdata.xml ${UB_INSTALLDIR}/usr/share/appdata/org.alacritty.Alacritty.appdata.xml
cp extra/logo/alacritty-term.svg ${UB_INSTALLDIR}/usr/share/pixmaps/Alacritty.svg
cp extra/completions/alacritty.bash ${UB_INSTALLDIR}/usr/share/bash-completion/completions/alacritty
cp extra/completions/_alacritty ${UB_INSTALLDIR}/usr/share/zsh/site-functions/_alacritty
cp extra/completions/alacritty.fish ${UB_INSTALLDIR}/usr/share/fish/completions/
cp alacritty.yml ${UB_INSTALLDIR}/usr/share/doc/alacritty/example/
