#!/bin/sh -eux

ub_install
#mkdir -p "${UB_INSTALLDIR}/usr"/{include,lib/{cmake,pkgconfig}}
#    ln -sr "${UB_INSTALLDIR}${_sitepkgs}/pybind11/include/pybind11" "${UB_INSTALLDIR}/usr/include/pybind11"
#    ln -sr "${UB_INSTALLDIR}${_sitepkgs}/pybind11/share/cmake/pybind11" "${UB_INSTALLDIR}/usr/lib/cmake/pybind11"
#    ln -sr "${UB_INSTALLDIR}${_sitepkgs}/pybind11/share/pkgconfig/pybind11.pc" "${UB_INSTALLDIR}/usr/lib/pkgconfig/pybind11.pc"
#}
