#!/bin/sh -eux

install -o root -g root -m644 deluser.conf "$UB_INSTALLDIR"/etc
install -o root -g root -m755 adduser "$UB_INSTALLDIR"/usr/sbin/adduser
install -o root -g root -m755 deluser "$UB_INSTALLDIR"/usr/sbin/deluser

mkdir -p "$UB_INSTALLDIR"/usr/lib/perl5/vendor_perl/5.18.2/Debian
install -o root -g root -m644 AdduserCommon.pm "$UB_INSTALLDIR"/usr/lib/perl5/vendor_perl/5.18.2/Debian/AdduserCommon.pm

install -o root -g root -m644 doc/adduser.conf.5 "$UB_INSTALLDIR"/usr/share/man/man5/
install -o root -g root -m644 doc/deluser.conf.5 "$UB_INSTALLDIR"/usr/share/man/man5/
install -o root -g root -m644 doc/adduser.8 "$UB_INSTALLDIR"/usr/share/man/man8/
install -o root -g root -m644 doc/deluser.8 "$UB_INSTALLDIR"/usr/share/man/man8/

ln -s adduser "$UB_INSTALLDIR"/usr/sbin/addgroup
ln -s deluser "$UB_INSTALLDIR"/usr/sbin/delgroup
