#!/bin/sh -eux

cd src
ub_install \
        prefix=/usr \
        bindir=/usr/bin \
        docdir=/usr/share/doc/Packages/trigger-rally
mv ../data/icon/trigger-64.png ${UB_INSTALLDIR}/usr/share/pixmaps/trigger.png
rm -rf ${UB_INSTALLDIR}/usr/share/games/trigger-rally/icon
