#!/bin/sh -eux

./configure \
	--enable-fhs \
	--with-systemd \
	--with-piddir=/run \
	--with-sockets-dir=/run/samba \
	--without-ad-dc \
	--without-gpgme \
	--systemd-install-services \
	--bundled-libraries=!tdb,!talloc,!pytalloc-util,!tevent,!popt,!ldb,!pyldb-util \
	--destdir="$UB_INSTALLDIR" \
	--prefix="/usr"             \
	--sysconfdir="/etc"         \
	--localstatedir="/var"      \
	--mandir="/usr/share/man"   \
	--infodir="/usr/share/info" \
	-j $UB_MAKE_PROCS

make -j $UB_MAKE_PROCS
