#!/bin/sh -eux
export LDFLAGS="/usr/lib/libSDL-1.2.so.0"
make	\
  MPKDIR=/usr/share/games/tomatoes/ \
  MUSICDIR=/usr/share/games/tomatoes/music/ \
  CONFIGDIR=/usr/share/games/tomatoes/ \
  OVERRIDEDIR=/usr/share/games/tomatoes/data/
