#!/bin/sh -eux

# qtwebengine: külön csomag

cd $UB_OBJECTDIR

export LD_LIBRARY_PATH="$(pwd)"/lib

$UB_COMPILEDIR/configure \
	-platform linux-g++-64 \
	-prefix /usr/lib/qt5 \
	-sysconfdir /etc/xdg \
	\
	-release            \
	-opensource         \
	-confirm-license	\
	-shared             \
	-journald			\
	-c++std c++1z       \
	-verbose            \
	-silent             \
	-ccache             \
	-no-pch             \
	-qml-debug			\
	-no-use-gold-linker \
	-reduce-relocations \
	-no-rpath           \
	\
	-nomake examples    \
	-nomake tests		\
	-skip qtwebengine	\
	\
	-accessibility      \
	\
	-plugin-sql-sqlite  \
	\
	-gstreamer 1.0		\
	\
	-system-freetype	\
	-system-harfbuzz	\
	-system-libjpeg     \
	-system-libpng      \
	-system-pcre		\
	-system-sqlite		\
	-system-zlib        \
	-system-xcb         \
	\
	-dbus-linked        \
	-openssl-linked     \
	-ssl               \
	\
	-cups               \
	-glib               \
	-gtk				\
	-opengl             \
	-no-iconv           \
	-no-linuxfb         \
	-no-eglfs           \
	-no-kms             \
	-no-libproxy		\
	\
	-fontconfig         \
	-evdev				\
	-mtdev				\
	-libinput			\
	-tslib				\
	-xkb                \
	-xcb-xlib			\

ub_make
