#!/bin/sh -eux

cd $UB_OBJECTDIR

make INSTALL_ROOT="$UB_INSTALLDIR" install

ln -s ../lib/qt5/bin/moc "$UB_INSTALLDIR"/usr/bin/moc-qt5
ln -s ../lib/qt5/bin/qmake "$UB_INSTALLDIR"/usr/bin/qmake-qt5
ln -s ../lib/qt5/bin/rcc "$UB_INSTALLDIR"/usr/bin/rcc-qt5
ln -s ../lib/qt5/bin/uic "$UB_INSTALLDIR"/usr/bin/uic-qt5

# Drop QMAKE_PRL_BUILD_DIR because reference the build dir
find "$UB_INSTALLDIR/usr/lib" -type f -name '*.prl' \
	-exec sed -i -e '/^QMAKE_PRL_BUILD_DIR/d' {} \;

# a desktop fájlok kedvéért szimlinkelünk az /usr/bin-be

ln -s ../lib/qt5/bin/assistant "$UB_INSTALLDIR"/usr/bin/assistant-qt5
ln -s ../lib/qt5/bin/designer "$UB_INSTALLDIR"/usr/bin/designer-qt5
ln -s ../lib/qt5/bin/linguist "$UB_INSTALLDIR"/usr/bin/linguist-qt5
ln -s ../lib/qt5/bin/qdbusviewer "$UB_INSTALLDIR"/usr/bin/qdbusviewer-qt5

# ikonok a desktop fájlokhoz
install -Dm644 $UB_COMPILEDIR/qttools/src/assistant/assistant/images/assistant-128.png \
                  "$UB_INSTALLDIR"/usr/share/pixmaps/assistant-qt5.png
install -Dm644 $UB_COMPILEDIR/qttools/src/designer/src/designer/images/designer.png \
                  "$UB_INSTALLDIR"/usr/share/pixmaps/designer-qt5.png
install -Dm644 $UB_COMPILEDIR/qttools/src/linguist/linguist/images/icons/linguist-128-32.png \
                  "$UB_INSTALLDIR"/usr/share/pixmaps/linguist-qt5.png
install -Dm644 $UB_COMPILEDIR/qttools/src/qdbus/qdbusviewer/images/qdbusviewer-128.png \
                  "$UB_INSTALLDIR"/usr/share/pixmaps/qdbusviewer-qt5.png
