#!/bin/sh -eux

ub_install \
	install-full
mv "$UB_INSTALLDIR"/usr/bin/dialog "$UB_INSTALLDIR"/usr/bin/cdialog
mv "$UB_INSTALLDIR"/usr/lib/libdialog.a "$UB_INSTALLDIR"/usr/lib/libcdialog.a
mv "$UB_INSTALLDIR"/usr/share/man/man1/dialog.1 "$UB_INSTALLDIR"/usr/share/man/man1/cdialog.1
