#!/bin/sh -eux

DEST=$UB_INSTALLDIR/usr
SHARE=$DEST/share
MAN=$SHARE/man

cp dcraw $DEST/bin
cp dcraw.1 $MAN/man1
# Please help me add more languages
for langchar in \
  fr.latin1 it.latin1 de.latin1 pt.latin1 es.latin1 nl.latin1 sv.latin1 \
  ca.latin1 da.latin1 cs.latin2 hu.latin2 pl.latin2 ro.latin2 eo.latin3 \
  ru.koi8-r ja.euc-jp zh_TW.big5 zh_CN.gb2312
do
  lang=`echo $langchar | cut -d. -f1`
  char=`echo $langchar | cut -d. -f2-`
  mkdir -p -m 755 $MAN/$lang/man1
  iconv -f utf-8 -t $char dcraw_$lang.1 > $MAN/$lang/man1/dcraw.1
  mkdir -p -m 755 $MAN/$lang.UTF-8/man1
  cp dcraw_$lang.1 $MAN/$lang.UTF-8/man1/dcraw.1
  mkdir -p -m 755 $SHARE/locale/$lang/LC_MESSAGES
  msgfmt -o $SHARE/locale/$lang/LC_MESSAGES/dcraw.mo dcraw_$lang.po
done
rm "$UB_INSTALLDIR"/usr/share/man/{es,eo,nl}/man1/dcraw.1
