#!/bin/sh -eux

mkdir -p "${UB_INSTALLDIR}/usr/lib/uhubuild"
cp -a src/. "${UB_INSTALLDIR}/usr/lib/uhubuild/"

mv "${UB_INSTALLDIR}"/usr/lib/uhubuild/helpers/* "${UB_INSTALLDIR}"/usr/bin/
rmdir "${UB_INSTALLDIR}"/usr/lib/uhubuild/helpers

mv "${UB_INSTALLDIR}"/usr/lib/uhubuild/build/* "${UB_INSTALLDIR}"/usr/bin/
rmdir "${UB_INSTALLDIR}"/usr/lib/uhubuild/build

mv "${UB_INSTALLDIR}"/usr/lib/uhubuild/dl/* "${UB_INSTALLDIR}"/usr/bin/
rmdir "${UB_INSTALLDIR}"/usr/lib/uhubuild/dl

mkdir -p "${UB_INSTALLDIR}/usr/share/uhubuild"
cp -a config words "${UB_INSTALLDIR}/usr/share/uhubuild/"

mkdir -p "${UB_INSTALLDIR}/usr/share/bash-completion"
cp -a bash-completion/completions "${UB_INSTALLDIR}/usr/share/bash-completion/"

# symlinks
cd "${UB_INSTALLDIR}/usr/bin"
ln -sf "../lib/uhubuild/uhubuild-build"
ln -sf "../lib/uhubuild/uhubuild-check"
ln -sf "../lib/uhubuild/uhubuild-chrootbuild"
ln -sf "../lib/uhubuild/uhubuild-expand"
ln -sf "../lib/uhubuild/uhubuild-extract"
ln -sf "../lib/uhubuild/uhubuild-pack"
ln -sf "../lib/uhubuild/uhubuild-u2d"

# perms
cd "${UB_INSTALLDIR}"
for i in build check chrootbuild depends expand extract pack prepare-chroot; do
	chmod 755 "usr/lib/uhubuild/uhubuild-$i"
done

chmod 644 usr/lib/uhubuild/common
chmod 644 usr/lib/uhubuild/uhubuild-common
chmod 644 usr/lib/uhubuild/uhubuild-commonenvironment
chmod 755 usr/lib/uhubuild/steps/*

chmod 755 usr/bin/ub_*

# build
for dist in UBK3 UBK4 UBK5; do
	for a in 1 2 3 ; do
		mkdir -p "$UB_INSTALLDIR"/var/uhubuild/"$dist"/amd64/chroot${a}
	done
mkdir -p "$UB_INSTALLDIR"/usr/src/UHUBUILD/UB-"$dist"
mkdir -p "$UB_INSTALLDIR"/usr/src/UHUBUILD/misc-"$dist"/extrarelease/amd64
mkdir -p "$UB_INSTALLDIR"/usr/src/UHUBUILD/misc-"$dist"/failed/amd64
mkdir -p "$UB_INSTALLDIR"/usr/src/UHUBUILD/misc-"$dist"/snapshot/compile/amd64
mkdir -p "$UB_INSTALLDIR"/usr/src/UHUBUILD/misc-"$dist"/snapshot/install/amd64
mkdir -p "$UB_INSTALLDIR"/usr/src/UHUBUILD/misc-"$dist"/logpack/amd64
mkdir -p "$UB_INSTALLDIR"/usr/src/UHUBUILD/misc-"$dist"/tmp/amd64
mkdir -p "$UB_INSTALLDIR"/usr/src/UHUBUILD/packages-"$dist"/ub
mkdir -p "$UB_INSTALLDIR"/usr/src/UHUBUILD/packages-"$dist"/amd64
cd "$UB_INSTALLDIR"/usr/src/UHUBUILD/packages-"$dist"/amd64
uhu-scanpkgs
echo "Label: UHU-Linux" > Release
echo "Origin: ubk.hu" >> Release
echo "Version: $dist" >> Release

ln -s "$UB_INSTALLDIR"/usr/bin/build-clean \
	"$UB_INSTALLDIR"/usr/bin/build-clean-"${dist,,}"

ln -s "$UB_INSTALLDIR"/usr/bin/build \
	"$UB_INSTALLDIR"/usr/bin/build-"${dist,,}"

# sources.list
mkdir -p "${UB_INSTALLDIR}/etc/apt"

cat > "$UB_INSTALLDIR"/etc/apt/sources.list-build-$dist <<END
# /etc/apt/sources.list

deb file:/usr/src/UHUBUILD/packages-$dist/amd64 ./

deb http://download.ubk.hu/pkg/${dist,,}/main/amd64 ./
deb http://quantum-mirror.hu/mirrors/pub/ubk/pkg/${dist,,}/main/amd64 ./

END

done
