#!/bin/sh -eux

ub_install

for s in 16 22 24 32 48; do
	install -D -m644 media/icons/tigervnc_$s.png "$UB_INSTALLDIR"/usr/share/icons/hicolor/"$s"x"$s"/apps/tigervnc.png
done

install -D -m644 media/icons/tigervnc.svg "$UB_INSTALLDIR"/usr/share/icons/hicolor/scalable/apps/tigervnc.svg
