#!/bin/sh -eux

cd src

python2 setup.py install --root="$UB_INSTALLDIR"

python3 setup.py install --root="$UB_INSTALLDIR"

mkdir -p ${UB_INSTALLDIR}/usr/share/doc/Packages/python3-pytz
cp LICENSE.txt README.txt ${UB_INSTALLDIR}/usr/share/doc/Packages/python3-pytz/
