#!/bin/sh -eux

cp -a py2 py3

cd py2
python2 setup.py install --root="$UB_INSTALLDIR"
cd ../py3
python3 setup.py install --root="$UB_INSTALLDIR"

mkdir -p ${UB_INSTALLDIR}/usr/share/doc/Packages/python3-pytz
cp LICENSE.txt README.txt ${UB_INSTALLDIR}/usr/share/doc/Packages/python3-pytz/
