#!/bin/sh -eux

git clone https://github.com/rampantpixels/rpmalloc.git src/3rdparty/rpmalloc/rpmalloc
cd src/3rdparty/rpmalloc/rpmalloc
git checkout e8b3be9
cd -

ub_compile \
    -DWANT_SDL:BOOL=OFF \
    -DWANT_PORTAUDIO:BOOL=OFF \
    -DWANT_CAPS:BOOL=OFF \
    -DWANT_CARLA=OFF \
    -DWANT_TAP:BOOL=OFF \
    -DWANT_CALF:BOOL=OFF \
    -DWANT_QT5:BOOL=ON \
    -DWANT_VST:BOOL=OFF \
    -DWANT_VST_NOWINE:BOOL=ON \
    -Wno-dev
