#!/bin/sh -eux

if [ $((`stat -f -c "%a" .`*`stat -f -c "%s" .`/(1024*1024*1024))) -lt 12 ]; then
	echo "At least 12 GB free space is required!"
	exit 1
fi

ccache --max-size=12G

# átpakolunk az /src alá mindent, mert
# ott fogja keresni a letöltött forráscsomagokat
# if [ ! -d src ]; then
# mkdir src
# fi
# mv *.{gz,zip,bz2,xz} src/

# ha van a distro-configs alatt megfelelő tartalmú .conf fájl, ekkor az
# ./autogen.sh --with-distro=<conffile> is használható
# a LibreOfficeUHU.conf fájlhoz
# ./autogen.sh --with-distro=LibreOfficeUHU
# egyébként az autogen.input a preferált (ebben felsorolni az opciókat),
# csak ne legyenek idézőjelek az opciókban (pl. --prefix="/usr"), attól kiakad!

# opciók a distro-configs/LibreOfficeUHU.conf-ból
./autogen.sh \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --with-lang="en-GB hu" \
    --with-vendor=ubk.hu \
    --with-help \
    --with-fonts \
    --with-external-tar=src \
    --with-system-libs \
    --with-system-headers \
    --with-myspell-dicts \
    --with-external-dict-dir=/usr/share/hunspell \
    --without-java \
    --without-system-jars \
    --without-system-abseil \
    --without-system-bluez \
    --without-system-box2d \
    --without-system-dragonbox \
    --without-system-frozen \
    --without-system-libabw \
    --without-system-libcdr \
    --without-system-libcmis \
    --without-system-libebook \
    --without-system-libepubgen \
    --without-system-libexttextcat \
    --without-system-libfixmath \
    --without-system-libfreehand \
    --without-system-libmspub \
    --without-system-libmwaw \
    --without-system-libnumbertext \
    --without-system-libpagemaker \
    --without-system-libqxp \
    --without-system-libstaroffice \
    --without-system-libzmf \
    --without-system-lpsolve \
    --without-system-mdds \
    --without-system-mythes \
    --without-system-orcus \
    --without-system-poppler \
    --without-system-xmlsec \
    --without-system-zxing \
    --disable-coinmp \
    --disable-dbgutil \
    --disable-debug \
    --disable-odk \
    --disable-firebird-sdbc \
    --disable-skia \
    --enable-avahi \
    --enable-fetch-external \
    --enable-gstreamer-1-0 \
    --enable-postgresql-sdbc \
    --enable-python \
    --enable-ext-nlpsolver \
    --enable-gio \
    --enable-gtk3 \
    --enable-gtk3-kde5 \
    --enable-gtk4 \
    --enable-kf5 \
    --enable-qt5 \
    --enable-qt6 \
    --disable-pdfimport \
    --disable-pdfium \
    --enable-release-build

# az unitcheck és a slowcheck nem kell
make build
