#!/bin/sh -eux

CC="ccache gcc -m64"
CXX="ccache g++ -m64"

export LDFLAGS="-Wl,-rpath,/usr/lib/seamonkey/ -Wl,--no-keep-memory -Wl,-z,relro -Wl,-z,now"

: > .mozconfig
cat > .mozconfig << _EOF_
ac_add_options --prefix=/usr
ac_add_options --enable-application=suite
ac_add_options --enable-release
ac_add_options --enable-official-branding
ac_add_options --enable-optimize="-O2"
ac_add_options --with-pthreads
ac_add_options --with-system-bz2
ac_add_options --with-system-icu
ac_add_options --without-system-libevent
ac_add_options --with-system-libvpx
ac_add_options --with-system-nss
ac_add_options --with-system-nspr
ac_add_options --with-system-zlib
ac_add_options --with-system-jpeg
ac_add_options --with-system-png
ac_add_options --enable-system-hunspell
ac_add_options --disable-system-sqlite
ac_add_options --enable-gio
ac_add_options --enable-startup-notification
ac_add_options --enable-default-toolkit=cairo-gtk2
ac_add_options --enable-safe-browsing
ac_add_options --enable-url-classifier
ac_add_options --disable-clang-plugin
ac_add_options --disable-stylo
ac_add_options --disable-debug
ac_add_options --disable-gconf
ac_add_options --disable-gnomeui
ac_add_options --disable-updater
ac_add_options --disable-tests
ac_add_options --disable-strip
ac_add_options --disable-install-strip
ac_add_options --disable-elf-hack
ac_add_options --disable-necko-wifi
ac_add_options --host=x86_64-linux-gnu
ac_add_options --target=x86_64-linux-gnu
_EOF_

cd "$UB_OBJECTDIR"

# az UB_CONFIGURE_DIR="$UB_COMPILEDIR" forma nem jó, linker hiba lesz belőle
"$UB_COMPILEDIR"/configure

ub_make
