#!/bin/sh -eux

export PYTHON=/usr/bin/python2
export PYTHON3=/usr/bin/python3

cd "$UB_OBJECTDIR"

DESTDIR="$UB_INSTALLDIR" "$UB_COMPILEDIR"/mach install

rm -f "$UB_INSTALLDIR"/usr/lib/seamonkey/seamonkey
rm -f "$UB_INSTALLDIR"/usr/bin/seamonkey
ln -s /usr/lib/seamonkey/seamonkey "$UB_INSTALLDIR"/usr/bin/seamonkey

if [ ! -f "$UB_INSTALLDIR"/usr/lib/seamonkey/run-mozilla.sh ]; then
	cp "$UB_COMPILEDIR"/build/unix/run-mozilla.sh "$UB_INSTALLDIR"/usr/lib/seamonkey/run-mozilla.sh
fi

cp "$UB_INSTALLDIR"/usr/lib/seamonkey/chrome/icons/default/default48.png "$UB_INSTALLDIR"/usr/share/pixmaps/seamonkey.png
cp "$UB_INSTALLDIR"/usr/lib/seamonkey/chrome/icons/default/messengerWindow48.png "$UB_INSTALLDIR"/usr/share/pixmaps/seamonkey-mail.png

mkdir -p "$UB_INSTALLDIR"/usr/lib/seamonkey/extensions/langpack-hu@seamonkey.mozilla.org
cp -aR "$UB_COMPILEDIR"/langpack-hu/. "$UB_INSTALLDIR"/usr/lib/seamonkey/extensions/langpack-hu@seamonkey.mozilla.org/
