#!/bin/sh -eux

install -d "$UB_INSTALLDIR/usr/lib/seamonkey"
    cp -r * "$UB_INSTALLDIR/usr/lib/seamonkey/"
    install -d "$UB_INSTALLDIR/usr/bin"
    ln -s /opt/seamonkey/seamonkey "$UB_INSTALLDIR/usr/bin/seamonkey"
    install -d "$UB_INSTALLDIR/usr/share/applications"
    cat <<EOF > "$UB_INSTALLDIR/usr/share/applications/seamonkey.desktop"
[Desktop Entry]
Name=SeaMonkey
GenericName=Internet Suite
Comment=Web browser, advanced email, newsgroup and feed client, IRC chat, and web development tools
Exec=/usr/lib/seamonkey/seamonkey %u
Icon=seamonkey
Terminal=false
Type=Application
Categories=Network;WebBrowser;Email;News;Chat;
MimeType=text/html;text/xml;application/xhtml+xml;application/vnd.mozilla.xul+xml;application/rss+xml;application/rdf+xml;
EOF

    for size in 16 22 24 32 48 64 128 256; do
        install -d "$UB_INSTALLDIR/usr/share/icons/hicolor/${size}x${size}/apps"
        install -m644 "chrome/icons/default/default${size}.png" "$UB_INSTALLDIR/usr/share/icons/hicolor/${size}x${size}/apps/seamonkey.png"
    done

ln -sf ${UB_INSTALLDIR}/usr/lib/seamonkey/seamonkey ${UB_INSTALLDIR}/usr/bin/seamonkey
