#!/bin/sh -eux

cd "$UB_OBJECTDIR"

export PYTHON=/usr/bin/python3
DESTDIR="$UB_INSTALLDIR" "$UB_COMPILEDIR"/mach install

rm -f "$UB_INSTALLDIR"/usr/lib/seamonkey/seamonkey
rm -f "$UB_INSTALLDIR"/usr/bin/seamonkey
ln -s /usr/lib/seamonkey/seamonkey "$UB_INSTALLDIR"/usr/bin/seamonkey

if [ ! -f "$UB_INSTALLDIR"/usr/lib/seamonkey/run-mozilla.sh ]; then
	cp "$UB_COMPILEDIR"/build/unix/run-mozilla.sh "$UB_INSTALLDIR"/usr/lib/seamonkey/run-mozilla.sh
fi

# install icons
for i in 16 22 24 32 48 64 128 256; do
    install -Dm644 "$UB_COMPILEDIR"/comm/suite/branding/seamonkey/default${i}.png \
      "$UB_INSTALLDIR/usr/share/icons/hicolor/${i}x${i}/apps/seamonkey.png"
done
install -Dm644 "$UB_COMPILEDIR"/comm/suite/branding/seamonkey/icons/gtk/messengerWindow16.png \
    "$UB_INSTALLDIR/usr/share/icons/hicolor/16x16/apps/seamonkey.png"
install -Dm644 "$UB_COMPILEDIR"/comm/suite/branding/seamonkey/icons/gtk/messengerWindow.png \
    "$UB_INSTALLDIR/usr/share/icons/hicolor/32x32/apps/seamonkey-mail.png"
install -Dm644 "$UB_COMPILEDIR"/comm/suite/branding/seamonkey/icons/gtk/messengerWindow48.png \
    "$UB_INSTALLDIR/usr/share/icons/hicolor/48x48}/apps/seamonkey-mail.png"

mkdir -p "$UB_INSTALLDIR"/usr/lib/seamonkey/extensions/langpack-hu@seamonkey.mozilla.org
cp -aR "$UB_COMPILEDIR"/langpack-hu/. "$UB_INSTALLDIR"/usr/lib/seamonkey/extensions/langpack-hu@seamonkey.mozilla.org/
