#!/bin/sh -eux

ub_compile \
    -Dcheck-update=no \
    -Dappdata-test=disabled \
	-Dgi-docgen=disabled \
	-Dbug-report-url=https://example.com/ \
    -Dheadless-tests=disabled # enabled by default, depends on xorg-server-xvfb
