#!/bin/sh -eux

ub_compile \
    -Dcheck-update=no \
    -Dappdata-test=disabled \
	-Dgi-docgen=disabled \
	-Dg-ir-doc=false \
	-Dvala=disabled \
	-Dlua=enabled \
	-Dbug-report-url=https://example.com/
