#!/bin/sh -eux

ub_install

ln -s gimp-${UB_VERSION_HEAD2} ${UB_INSTALLDIR}/usr/bin/gimp
ln -s gimptool-${UB_VERSION_HEAD2} ${UB_INSTALLDIR}/usr/bin/gimptool
ln -s gimp-console-${UB_VERSION_HEAD2} ${UB_INSTALLDIR}/usr/bin/gimp-console
ln -s gimp-test-clipboard-${UB_VERSION_HEAD2} ${UB_INSTALLDIR}/usr/bin/gimp-test-clipboard
