#!/bin/bash -eux

# hostname : coreutils
# logger : util-linux
# ping : iputils
# ping6 : iputils
# traceroute : traceroute
# whois : whois
# syslogd : sysklogd

ub_compile \
	--disable-hostname \
	--disable-logger \
	--disable-ping \
	--disable-ping6 \
	--disable-traceroute \
	--disable-whois \
	--disable-syslogd
