#!/bin/sh -eux

# sys_nerr, sys_errlist removed in glibc 2.32, disable v4l

autoreconf

UB_UPDATELIBTOOL=yes ub_compile \
	--disable-v4l \
	--enable-oss \
	--enable-libpostproc \
	--enable-freetype2 \
	--enable-ogg \
	--enable-vorbis \
	--enable-theora \
	--enable-libdv \
	--enable-libquicktime \
	--enable-lzo \
	--enable-a52 \
	--enable-libxml2 \
	--enable-mjpegtools \
	--enable-sdl \
	--enable-x264 \
	--enable-xvid \
	--enable-libmpeg2 \
	--enable-libmpeg2convert \
	--disable-libv4l2 \
	--disable-libv4lconvert \
	--enable-alsa \
	--enable-faac \
	--enable-imagemagick
