#!/bin/sh -eux

#autoreconf -vif
export PKG_CONFIG_PATH='/usr/lib/ffmpeg4.4/pkgconfig'
ub_compile \
    --disable-sse \
    --disable-sse2 \
    --disable-altivec \
    --enable-mmx \
    --enable-lame \
    --enable-ogg \
    --enable-vorbis \
    --enable-theora \
    --enable-libdv \
    --enable-libxml2 \
    --enable-v4l \
    --enable-imagemagick \
    --enable-libjpeg \
    --enable-lzo \
    --enable-mjpegtools \
    --enable-freetype2 \
    --enable-a52 \
    --enable-xvid \
    --enable-x264 \
    --enable-alsa \
    --enable-libmpeg2 \
    --enable-libmpeg2convert \
    --enable-ffmpeg
