#!/bin/sh -eux

cd py2
find -name "*.py" -exec sed -e 's/env python/&2/' -i {} \;
python2 setup.py install --root=${UB_INSTALLDIR}
mv ${UB_INSTALLDIR}/usr/bin/gflags2man.py ${UB_INSTALLDIR}/usr/bin/gflags2man.py2
cd ../py3
python3 setup.py install --root=${UB_INSTALLDIR}
mkdir -p ${UB_INSTALLDIR}/usr/share/doc/Packages/python2-gflags
cp AUTHORS COPYING README* ${UB_INSTALLDIR}/usr/share/doc/Packages/python2-gflags/
cp AUTHORS COPYING README* ../
