diff -Naur a/Makefile b/Makefile
--- a/Makefile	2024-01-29 14:09:41.000000000 +0100
+++ b/Makefile	2024-05-05 22:46:02.762693892 +0200
@@ -2,13 +2,13 @@
 TOP = .
 SUBDIRS = as10k1 envy24control hdsploader hdspconf hdspmixer \
 	  mixartloader pcxhrloader rmedigicontrol sb16_csp seq sscape_ctl \
-	  us428control usx2yloader vxloader echomixer ld10k1 qlo10k1 \
+	  us428control usx2yloader vxloader echomixer ld10k1 \
 	  hwmixvolume hdajackretask hda-verb hdajacksensetest
 
 all:
 	@for i in $(SUBDIRS); do \
 	  cd $(TOP)/$$i; echo $(TOP)/$$i; \
-	  ./gitcompile $(GITCOMPILE_ARGS) || exit 1; \
+	  ./gitcompile --prefix=/usr --sbindir=/usr/bin $(GITCOMPILE_ARGS) || exit 1; \
 	  cd ..; make -C $$i || exit 1; \
 	done
 
@@ -16,9 +16,9 @@
 	@for i in $(SUBDIRS); do \
 	  cd $(TOP)/$$i; echo $(TOP)/$$i; \
 	  if [ -x ./configure ]; then \
-	    ./configure $(CONFIGURE_ARGS) || exit 1; \
+	    ./configure --prefix=/usr --sbindir=/usr/bin $(CONFIGURE_ARGS) || exit 1; \
 	  else \
-	    make CONFIGURE_ARGS="$CONFIGURE_ARGS" configure || exit 1; \
+	    autoreconf -vif ./configure --prefix=/usr --sbindir=/usr/bin $(CONFIGURE_ARGS) || exit 1; \
 	  fi; \
 	  cd ..; make -C $$i || exit 1; \
 	done
