diff -Nur orig/Makefile mod/Makefile
--- orig/Makefile	2021-05-27 22:09:02.000000000 +0200
+++ mod/Makefile	2021-06-20 18:44:35.478640181 +0200
@@ -1,8 +1,8 @@
 VERSION = 1.2.5
 TOP = .
-SUBDIRS = as10k1 envy24control hdsploader hdspconf hdspmixer \
-	  mixartloader pcxhrloader rmedigicontrol sb16_csp seq sscape_ctl \
-	  us428control usx2yloader vxloader echomixer ld10k1 qlo10k1 \
+SUBDIRS = as10k1 envy24control hdsploader hdspconf hdspmixer \
+	  mixartloader pcxhrloader rmedigicontrol sb16_csp seq/sbiload sscape_ctl \
+	  us428control usx2yloader vxloader echomixer ld10k1  \
 	  hwmixvolume hdajackretask hda-verb hdajacksensetest
 
 all:
@@ -14,13 +14,13 @@
 
 configure:
 	@for i in $(SUBDIRS); do \
-	  cd $(TOP)/$$i; echo $(TOP)/$$i; \
+		cd $(TOP)/$$i; \
 	  if [ -x ./configure ]; then \
-	    ./configure $(CONFIGURE_ARGS) || exit 1; \
+	    ./configure --prefix=/usr --sbindir=/usr/bin $(CONFIGURE_ARGS) || exit 1; \
 	  else \
-	    make CONFIGURE_ARGS="$CONFIGURE_ARGS" configure || exit 1; \
+	    autoreconf -vif ./configure --prefix=/usr --sbindir=/usr/bin $(CONFIGURE_ARGS) || exit 1; \
 	  fi; \
-	  cd ..; make -C $$i || exit 1; \
+		cd -; make -C $$i || exit 1; \
 	done
 
 install:
