#!/bin/sh -eux

ub_install

mv "$UB_INSTALLDIR"/usr/share/locale/hu_HU "$UB_INSTALLDIR"/usr/share/locale/hu
mv "$UB_INSTALLDIR"/usr/share/icons/applet_uptime.png "$UB_INSTALLDIR"/usr/share/pixmaps/applet_uptime.png
