#! /bin/bash

export MAIN_DIALOG='
 <vbox>
  <combobox>
    <item>First item</item>
    <item>Second item</item>
    <item>Third item</item>
  </combobox>
  <hbox>
   <button ok></button>
   <button cancel></button>
  </hbox>
 </vbox>
'

gtkdialog --program MAIN_DIALOG


