#!/bin/sh -eux

py3docdir="$UB_INSTALLDIR"/usr/share/doc/Packages/python3-pycodestyle
mkdir -p $py3docdir
cd py3
python3 setup.py install --root="$UB_INSTALLDIR"
mv "$UB_INSTALLDIR"/usr/bin/pycodestyle "$UB_INSTALLDIR"/usr/bin/py3codestyle
cd ../py2
python2 setup.py install --root="$UB_INSTALLDIR"
cp CHANGES.txt README.rst $py3docdir
mv CHANGES.txt README.rst ../
