#!/bin/sh -eux

mkdir -p ${UB_INSTALLDIR}/usr/share/applications
cp build/share/applications/org.bluesabre.Mugshot.desktop ${UB_INSTALLDIR}/usr/share/applications/
python3 setup.py install --root="$UB_INSTALLDIR" --skip-build
