#!/bin/sh -eux

cp -r bin $UB_INSTALLDIR/usr/
cp -r share/* $UB_INSTALLDIR/usr/share
cucc='
kitty
kitty-extensions
cacert.pem
libcrypt.so.2
libiconv.so.2
libpython3.12.so.1.0
'
for i in ${cucc};do
cp -r lib/$i $UB_INSTALLDIR/usr/lib
done
# nem kell html doksi
rm -rf $UB_INSTALLDIR/usr/share/doc
