#!/bin/sh -eux

# completions
python3 __main__.py + complete setup bash | install -Dm644 /dev/stdin "${UB_INSTALLDIR}"/usr/share/bash-completion/completions/kitty
python3 __main__.py + complete setup fish | install -Dm644 /dev/stdin "${UB_INSTALLDIR}"/usr/share/fish/vendor_completions.d/kitty.fish
python3 __main__.py + complete setup zsh
install -Dm644 /dev/stdin "${UB_INSTALLDIR}"/usr/share/zsh/site-functions/_kitty

cd linux-package
cp -r * "${UB_INSTALLDIR}"/usr/
cd -
mkdir -p "${UB_INSTALLDIR}"/usr/share/doc/Packages/kitty
tic -x -o "$UB_INSTALLDIR/usr/share/terminfo" terminfo/kitty.terminfo
