#!/bin/sh -eux

# completions
python3 __main__.py + complete setup bash | install -Dm644 /dev/stdin "${UB_INSTALLDIR}"/usr/share/bash-completion/completions/kitty
python3 __main__.py + complete setup fish | install -Dm644 /dev/stdin "${UB_INSTALLDIR}"/usr/share/fish/vendor_completions.d/kitty.fish
python3 __main__.py + complete setup zsh
install -Dm644 /dev/stdin "${UB_INSTALLDIR}"/usr/share/zsh/site-functions/_kitty

cd linux-package
cp -r * "${UB_INSTALLDIR}"/usr/
cd -
mkdir -p "${UB_INSTALLDIR}"/usr/share/doc/Packages/kitty
rm -rf "${UB_INSTALLDIR}"/usr/share/doc/kitty/html
install -Dm644 docs/generated/conf/kitty.conf "${UB_INSTALLDIR}"/usr/share/doc/Packages/kitty/kitty.conf
mkdir -p "$UB_INSTALLDIR/usr/share/terminfo"
tic -x -o "$UB_INSTALLDIR/usr/share/terminfo" terminfo/kitty.terminfo
mv $UB_INSTALLDIR/usr/share/man/man1/kitty.conf.5 $UB_INSTALLDIR/usr/share/man/man1/kitty.conf.1
