#!/bin/sh -eux

export CFLAGS="-fPIC"
cd "$UB_OBJECTDIR"

UB_CONFIGURE_DIR="$UB_COMPILEDIR" \
LIBS="-lpthread" \
ub_configure \
	--enable-elf-shlibs \
	--disable-libblkid \
	--disable-uuidd \
	--disable-libuuid \
	--disable-fsck

ub_make
