#!/bin/sh -eux

cd "$UB_OBJECTDIR"

ub_install

make \
	DESTDIR="$UB_INSTALLDIR" \
	install-libs

mv "$UB_INSTALLDIR"/lib/pkgconfig "$UB_INSTALLDIR"/usr/lib/

mv "$UB_INSTALLDIR"/bin/compile_et "$UB_INSTALLDIR"/usr/bin/
mv "$UB_INSTALLDIR"/bin/mk_cmds    "$UB_INSTALLDIR"/usr/bin/

#mv "$UB_INSTALLDIR"/lib/libcom_err.a "$UB_INSTALLDIR"/usr/lib/
