#!/bin/sh -eux

ln -s /usr/bin/colorgcc "$UB_INSTALLDIR"/bin/gcc
ln -s /usr/bin/colorgcc "$UB_INSTALLDIR"/bin/g++
ln -s /usr/bin/colorgcc "$UB_INSTALLDIR"/bin/cc
ln -s /usr/bin/colorgcc "$UB_INSTALLDIR"/bin/c++
ln -s /usr/bin/colorgcc "$UB_INSTALLDIR"/bin/gcj
