#!/bin/sh -eux

_py_ver=$(python3 -c "import sys; print(str(sys.version_info.major)+'.'+str(sys.version_info.minor))")

install -Dm755 waf "$UB_INSTALLDIR/usr/bin/waf"
install -vDm 644 wscript -t "$UB_INSTALLDIR"/usr/share/waf

# installing, byte-compiling waflib and stripping pkgdir from it
install -vDm 644 waflib/*.py \
    -t "$UB_INSTALLDIR/usr/lib/python${_py_ver}/site-packages/waf/waflib"
install -vDm 644 waflib/Tools/*.py \
    -t "$UB_INSTALLDIR/usr/lib/python${_py_ver}/site-packages/waf/waflib/Tools"
install -vDm 644 waflib/extras/*.py \
    -t "$UB_INSTALLDIR/usr/lib/python${_py_ver}/site-packages/waf/waflib/extras"
python -m compileall -d "/usr/lib/python${_py_ver}" \
    "$UB_INSTALLDIR/usr/lib/python${_py_ver}"
python -O -m compileall -d "/usr/lib/python${_py_ver}" \
    "$UB_INSTALLDIR/usr/lib/python${_py_ver}"
