#!/bin/sh -eux

git clone -b upx-vendor https://github.com/upx/upx-vendor-doctest.git vendor/doctest
git clone -b upx-vendor https://github.com/upx/upx-vendor-lzma-sdk.git vendor/lzma-sdk
git clone -b upx-vendor https://github.com/upx/upx-vendor-ucl.git vendor/ucl
git clone -b upx-vendor https://github.com/upx/upx-vendor-valgrind.git vendor/valgrind
git clone -b upx-vendor https://github.com/upx/upx-vendor-zlib.git vendor/zlib

ub_compile
