#!/bin/sh -eux

ub_compile \
	--with-distro=generic \
	--with-bashcompletion \
	--with-udev \
	--without-rgmanager \
	--without-pacemaker \
	--without-heartbeat \
	--without-xen \
	--with-initscripttype=systemd \
	--sbindir=/usr/sbin \
	--libdir=/usr/lib
