#!/bin/sh -eux

ub_install

# move /lib files under /usr/lib
#mkdir -p $UB_INSTALLDIR/usr/lib/drbd
#mv $UB_INSTALLDIR/lib/drbd/* $UB_INSTALLDIR/usr/lib/drbd/

rm -rf $UB_INSTALLDIR/sbin
rm -rf $UB_INSTALLDIR/lib/drbd
rm -rf $UB_INSTALLDIR/lib
