#!/bin/sh -eux

celdir="$UB_INSTALLDIR"/usr/share/sddm/themes
mkdir -p "$celdir"
cp -R catppuccin-frappe "$celdir"/
cp -R catppuccin-latte "$celdir"/
cp -R catppuccin-macchiato "$celdir"/
cp -R catppuccin-mocha "$celdir"/
