#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR"/usr/share/eaglemode
perl make.pl install dir="$UB_INSTALLDIR"/usr/share/eaglemode

ln -s ../eaglemode/res/icons/eaglemode32.png "$UB_INSTALLDIR"/usr/share/pixmaps/eaglemode.png
