#!/bin/sh -eux

export DESTDIR="$UB_INSTALLDIR"
jam install
cp ${UB_INSTALLDIR}/usr/lib/libedelib.so.2.2.0 ${UB_INSTALLDIR}/usr/lib/libedelib.so
cp ${UB_INSTALLDIR}/usr/lib/libedelib_gui.so.2.2.0 ${UB_INSTALLDIR}/usr/lib/libedelib_gui.so
cp ${UB_INSTALLDIR}/usr/lib/libedelib_dbus.so.2.2.0 ${UB_INSTALLDIR}/usr/lib/libedelib_dbus.so
