#!/bin/sh -eux

mkdir -p ${UB_INSTALLDIR}/usr/share/applications
mv opt/google/earth/pro/google-earth-pro.desktop ${UB_INSTALLDIR}/usr/share/applications/
for size in 16 22 24 32 48 64 128 256; do
	mkdir -p ${UB_INSTALLDIR}/usr/share/icons/hicolor/${size}x${size}/apps/
	cp opt/google/earth/pro/product_logo_$size.png \
		${UB_INSTALLDIR}/usr/share/icons/hicolor/${size}x${size}/apps/google-earth-pro.png
done

mv opt/google ${UB_INSTALLDIR}/usr/lib

# rm broken link
rm ${UB_INSTALLDIR}/usr/lib/google/earth/pro/google-earth-pro
ln -s /usr/lib/google/earth/pro/googleearth ${UB_INSTALLDIR}/usr/bin/google-earth

# patchelf
find "${UB_INSTALLDIR}"/usr/lib -type f -exec patchelf --set-interpreter /usr/lib/ld-linux-x86-64.so.2 &> /dev/null {} \;
