#!/bin/sh -eux

./configure \
	--destdir="$UB_INSTALLDIR" \
	--prefix="/usr"             \
	--sysconfdir="/etc"         \
	--localstatedir="/var"      \
	--mandir="/usr/share/man"   \
	--infodir="/usr/share/info" \

ub_make
