#!/bin/sh -eux

cd py3
python3 setup.py install --prefix=/usr --root="$UB_INSTALLDIR" --optimize=1
mkdir -p  $UB_INSTALLDIR/usr/share/doc/Packages/python3-constantly
cp {README.rst,LICENSE} $UB_INSTALLDIR/usr/share/doc/Packages/python3-constantly/
mv {README.rst,LICENSE} ../
cd ../py2
python setup.py install --prefix=/usr --root="$UB_INSTALLDIR" --optimize=1
