#!/bin/sh -eux

ub_compile \
	-DCMAKE_INSTALL_PREFIX=/usr/lib/qt5 \
	-DLIB_INSTALL_DIR=/usr/lib/ \
	-DQML_INSTALL_DIR=/usr/lib/qt5/qml \
	-DKDE_INSTALL_INCLUDEDIR=/usr/include/qt5 \
	-DKDE_INSTALL_CMAKEPACKAGEDIR=/usr/lib/cmake \
	-DECM_MKSPECS_INSTALL_DIR=/usr/lib/qt5/mkspecs/modules \
	-DPORT=Qt \
	-DENABLE_TOOLS=OFF \
	-DENABLE_API_TESTS=OFF
