#!/bin/sh -eux

export CFLAGS+=' -Wno-narrowing'
export CXXFLAGS+="-Wno-narrowing -fpermissive"
ub_compile \
	--prefix=/var/www/htdig \
	--bindir=/usr/bin \
	--with-cgi-bin-dir=/var/www/cgi-bin \
	--with-database-dir=/var/www/htdig \
	--with-image-dir=/var/www/htdocs/htdig \
	--with-search-dir=/var/www/htdocs/htdig
