#!/bin/sh -eux

extensions="nemo-fileroller nemo-image-converter nemo-preview nemo-python nemo-seahorse nemo-share"
for progs in ${extensions}; do
cd $progs
  if [ -f autogen.sh ]; then
    rm -f autogen.sh
    autoreconf -vif
  fi
  ub_compile
cd ..
done
