#!/bin/sh -eux

extensions="nemo-seahorse nemo-preview nemo-fileroller nemo-python nemo-image-converter nemo-share"
for progs in ${extensions};do
cd $progs
ub_install
if [ "$progs" == "nemo-seahorse" ];then
make -C tool DESTDIR=$UB_INSTALLDIR uninstall
rm -rf $UB_INSTALLDIR/usr/share/{GConf,glib-2.0,nemo-seahorse}
fi
cd ..
done
mkdir -p "$UB_INSTALLDIR"/usr/share/{nemo-terminal,glib-2.0/schemas,nemo-python/extensions/}
cd nemo-terminal
    cp src/nemo_terminal.py "$UB_INSTALLDIR"/usr/share/nemo-python/extensions/nemo_terminal.py
    cp src/org.nemo.extensions.nemo-terminal.gschema.xml "$UB_INSTALLDIR"/usr/share/glib-2.0/schemas/org.nemo.extensions.nemo-terminal.gschema.xml
  cp pixmap/logo_120x120.png "$UB_INSTALLDIR"/usr/share/nemo-terminal/logo_120x120.png
cd -

docdir=$UB_INSTALLDIR/usr/share/doc/Packages
mkdir -p $docdir/{nemo-fileroller,nemo-seahorse,nemo-share,nemo-python,nemo-preview,nemo-terminal,nemo-image-converter}
cp nemo-fileroller/{COPYING,README} $docdir/nemo-fileroller/
cp nemo-seahorse/{COPYING,ChangeLog,README,THANKS} $docdir/nemo-seahorse/
cp nemo-seahorse/{AUTHORS,ChangeLog,COPYING,README} $docdir/nemo-share/
cp nemo-python/{AUTHORS,ChangeLog,COPYING,README} $docdir/nemo-python/
cp nemo-preview/{AUTHORS,COPYING,README} $docdir/nemo-preview/
cp nemo-terminal/{AUTHORS,COPYING,README} $docdir/nemo-terminal/
cp nemo-image-converter/{AUTHORS,COPYING,README} $docdir/nemo-image-converter/
