diff -Naur yuja-chg-ed0d352a85b9-orig/Makefile yuja-chg-ed0d352a85b9/Makefile
--- yuja-chg-ed0d352a85b9-orig/Makefile	2016-01-30 06:39:58.000000000 +0100
+++ yuja-chg-ed0d352a85b9/Makefile	2019-10-05 12:09:37.503330062 +0200
@@ -1,8 +1,8 @@
 HG = hg
-PYTHON = python
+PYTHON = python2
 
 DESTDIR =
-PREFIX = /usr/local
+PREFIX = /usr
 MANDIR = $(PREFIX)/share/man/man1
 
 CHGSOCKDIR = /tmp/chg$(shell id -u)
