#!/bin/sh -eux

ub_install

rm -f "$UB_INSTALLDIR"/lib/firmware/{ess/{maestro3_assp_kernel.fw,maestro3_assp_minisrc.fw},korg/k1212.dsp,yamaha/{{ds1_ctrl,ds1_dsp,ds1e_ctrl}.fw,yss225_registers.bin},sb16/{alaw_main,ima_adpcm_{capture,init,playback},mulaw_main}.csp}
rm "$UB_INSTALLDIR"/lib/firmware/ctefx.bin
rm "$UB_INSTALLDIR"/lib/firmware/ctspeq.bin
