#!/bin/sh -eux

make -f Makefile.unix \
	BINDIR="$UB_INSTALLDIR"/usr/bin \
	INCLUDEDIR="$UB_INSTALLDIR"/usr/share/psutils \
	PERL="$UB_INSTALLDIR"/usr/bin/perl \
	MANDIR="$UB_INSTALLDIR"/usr/share/man/man1 \
	install
