#!/bin/sh -eux

ub_install PREFIX=/usr
rm "$UB_INSTALLDIR"/usr/share/man//lz4.1
rm "$UB_INSTALLDIR"/usr/share/man//lz4c.1
rm "$UB_INSTALLDIR"/usr/share/man//lz4cat.1
rm "$UB_INSTALLDIR"/usr/share/man//unlz4.1
