#!/bin/sh -eux

if [ -d .git ]; then
    git submodule update --init --recursive
else
    git clone https://github.com/mruby/mruby.git mruby/mruby
    git clone git://git.guelker.eu/tinyclipboard.git tinyclipboard
    git clone git://git.guelker.eu/pod-cpp.git pod-parser
fi

cd tsc
ub_compile \
	-DUSE_LIBXMLPP3=ON
