#!/bin/sh -eux

if [ -d .git ]; then
    git submodule update --init --recursive
else
    git clone https://github.com/Secretchronicles/tinyclipboard.git tinyclipboard
    git clone https://github.com/Secretchronicles/pod-parser.git pod-parser
    git clone https://github.com/mruby/mruby.git mruby/mruby
    cd mruby/mruby
    git checkout 1c09046
    cd ../../
fi

cd tsc
ub_compile \
	-DUSE_LIBXMLPP3=ON
