#!/bin/sh -eux

ub_compile \
	-DCMAKE_PREFIX_PATH=/usr/lib/qt5 \
	-DKDE_INSTALL_USE_QT_SYS_PATHS=ON \
	-DBIN_INSTALL_DIR=/usr/bin \
	-DLIB_INSTALL_DIR=/usr/lib \
	-DINCLUDE_INSTALL_DIR=/usr/include \
	-DBUILD_TESTING=OFF
