#!/bin/sh -eux

make KEYCODES_PROGS=yes RESIZECONS_PROGS=yes DESTDIR="$UB_INSTALLDIR" install

# ro_win.map.gz is useless
rm -f ${UB_INSTALLDIR}/usr/share/keymaps/i386/qwerty/ro_win.map.gz

# Create additional name for Serbian latin keyboard
ln -s sr-cy.map.gz ${UB_INSTALLDIR}/usr/share/keymaps/i386/qwerty/sr-latin.map.gz
