#!/bin/sh -eux

ub_compile \
	--with-db=gdbm \
	--disable-setuid \
	--enable-mandirs=GNU \
	--enable-cache-owner=root \
	--with-systemdsystemunitdir=/usr/lib/systemd/system \
	--with-sections="1 n l 8 3 0 2 5 4 9 6 7"
