#!/bin/sh -e

query_giomodules ()
{
	[ -z "${UHU_PKG_QUIET+x}" ] && echo -n "  Querying GIO modules ..."
	gio-querymodules /usr/lib/gio/modules
	true > /var/lib/uhu-pkg/gio-querymodules
	while [ ! /var/lib/uhu-pkg/gio-querymodules -ot /var/lib/dpkg/info \
	     -a ! /var/lib/uhu-pkg/gio-querymodules -nt /var/lib/dpkg/info ]; do
		sleep 0.1
		true > /var/lib/uhu-pkg/gio-querymodules
	done
	[ -z "${UHU_PKG_QUIET+x}" ] && echo
}

if [ "$2" = "upgrade" ]; then
	exit 0
fi

if [ ! -f /var/lib/uhu-pkg/gio-querymodules ]; then
	query_giomodules
fi
