#!/bin/sh -eux

if [ "$UB_ARCH" = "amd64" ]; then
	tar -xzvf flash_player_ppapi_linux.x86_64.tar.gz
else
	tar -xzvf flash_player_ppapi_linux.i386.tar.gz
fi
rm -f flash_player_ppapi_linux*.tar.gz

libdir="$UB_INSTALLDIR/usr/lib"
sofile=libpepflashplayer.so

mkdir -p "$libdir"/adobe-flashplugin
mkdir -p "$libdir"/{firefox,mozilla}/plugins

install -m 755 $sofile "$libdir"/adobe-flashplugin/

install -m 644 manifest.json "$libdir"/adobe-flashplugin/

ln -s ../../adobe-flashplugin/$sofile "$libdir"/firefox/plugins/
ln -s ../../adobe-flashplugin/$sofile "$libdir"/mozilla/plugins/
