#!/bin/sh -eux

libdir="$UB_INSTALLDIR/usr/lib"
sofile=libpepflashplayer.so

mkdir -p "$libdir"/adobe-flashplugin
mkdir -p "$libdir"/{firefox,mozilla}/plugins

install -m 755 $sofile "$libdir"/adobe-flashplugin/

install -m 644 manifest.json "$libdir"/adobe-flashplugin/

ln -s ../../adobe-flashplugin/$sofile "$libdir"/firefox/plugins/
ln -s ../../adobe-flashplugin/$sofile "$libdir"/mozilla/plugins/
