#!/bin/sh -eux

ub_install
cp /etc/xdg/menus/lxde-applications.menu .
patch -i ${UB_SRCDIR}/patches/lxmenu-layout-mod.patch.skip
mkdir -p ${UB_INSTALLDIR}/etc/xdg/menus
cp lxde-applications.menu ${UB_INSTALLDIR}/etc/xdg/menus/fluxbox-applications.menu
