#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR"/usr/share/games/smokinguns/{smokinguns,baseq3}
install -Dm 755 "build/release-linux-x86_64/smokinguns.x86_64" "$UB_INSTALLDIR/usr/bin/smokinguns"
install -Dm 755 "build/release-linux-x86_64/smokinguns_dedicated.x86_64" "$UB_INSTALLDIR/usr/bin/smokinguns_dedicated"
cp build/release-linux-x86_64/renderer_* "$UB_INSTALLDIR"/usr/share/games/smokinguns/

install -Dm 644 "misc/smokinguns.png" "$UB_INSTALLDIR/usr/share/pixmaps/smokinguns.png"

unzip -jo Smokin_Guns_1.1.zip "Smokin' Guns 1.1"/baseq3/pak* -d ${UB_INSTALLDIR}/usr/share/games/smokinguns/baseq3/
unzip -jo Smokin_Guns_1.1.zip "Smokin' Guns 1.1"/smokinguns/* -d ${UB_INSTALLDIR}/usr/share/games/smokinguns/smokinguns/
