#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR"/usr/share/games/smokinguns/
install -Dm 755 "build/release-linux-x86_64/smokinguns.x86_64" "$UB_INSTALLDIR/usr/bin/smokinguns"
install -Dm 755 "build/release-linux-x86_64/smokinguns_dedicated.x86_64" "$UB_INSTALLDIR/usr/bin/smokinguns_dedicated"
cp build/release-linux-x86_64/renderer_* "$UB_INSTALLDIR"/usr/share/games/smokinguns/

install -Dm 644 "misc/smokinguns.png" "$UB_INSTALLDIR/usr/share/pixmaps/smokinguns.png"
