#!/bin/sh -eux

make \
      TO_BIN='lua5.3 luac5.3' \
      TO_LIB="liblua5.3.a liblua5.3.so liblua5.3.so.5.3 liblua5.3.so.$UB_VERSION" \
      INSTALL_DATA='cp -d' \
      INSTALL_TOP="$UB_INSTALLDIR"/usr \
      INSTALL_INC="$UB_INSTALLDIR"/usr/include/lua5.3 \
      INSTALL_MAN="$UB_INSTALLDIR"/usr/share/man/man1 \
install

mkdir -p "$UB_INSTALLDIR"/usr/lib/pkgconfig
ln -sf lua53.pc  "$UB_INSTALLDIR"/usr/lib/pkgconfig/lua5.3.pc
ln -sf lua53.pc  "$UB_INSTALLDIR"/usr/lib/pkgconfig/lua-5.3.pc

cd "$UB_INSTALLDIR"/usr/share/man/man1
mv lua.1 lua5.3.1
mv luac.1 luac5.3.1
