#!/bin/sh -eux

rm -f CMakeLists.txt
autoreconf -vif
ub_compile \
	--sysconfdir=/etc/clamav \
    --with-dbdir=/var/lib/clamav \
    --with-system-libmspack \
    --disable-rpath \
    --disable-clamav \
    --disable-llvm \
    --enable-zlib-vcheck \
    --enable-clamdtop \
    --sbindir=/usr/sbin \
    --disable-milter
