#!/bin/sh -eux

export QTDIR="/usr/lib/qt5"

cd src
rm -f autogen.sh # git checkout ylwrap
aclocal
libtoolize --copy
automake --add-missing --force-missing --copy
autoconf
ub_compile \
	--disable-webkit
