#!/bin/sh -eux

cd py
python setup.py install --root ${UB_INSTALLDIR}
mv "$UB_INSTALLDIR"/usr/bin/chardetect{,-py2}
cd ../py3
python3 setup.py install --root ${UB_INSTALLDIR}
cp LICENSE README.rst ../
mkdir -p ${UB_INSTALLDIR}/usr/share/doc/Packages/python3-chardet
cp LICENSE README.rst ${UB_INSTALLDIR}/usr/share/doc/Packages/python3-chardet/
