#!/bin/sh -eux

ub_install

ln -sf libffi.so.6 ${UB_INSTALLDIR}/usr/lib/libffi.so.5
ln -sf ../lib/libffi-${UB_VERSION}/include/ffi.h ${UB_INSTALLDIR}/usr/include
ln -sf ../lib/libffi-${UB_VERSION}/include/ffitarget.h ${UB_INSTALLDIR}/usr/include
