#!/bin/sh -eux

python2 setup.py install --root="$UB_INSTALLDIR"
python3 setup.py install --root="$UB_INSTALLDIR"

#python3-pyyaml doksik
mkdir -p ${UB_INSTALLDIR}/usr/share/doc/Packages/python3-pyyaml
cp CHANGES LICENSE README ${UB_INSTALLDIR}/usr/share/doc/Packages/python3-pyyaml/
