#!/bin/sh -eux

cp -a py2 py3
cd py3
python3 setup.py install --root=${UB_INSTALLDIR}
cd ../py2
python setup.py install --root=${UB_INSTALLDIR}

mkdir -p ${UB_INSTALLDIR}/usr/share/Packages/python3-mutagen
cp COPYING NEWS README.rst ${UB_INSTALLDIR}/usr/share/Packages/python3-mutagen/
cp COPYING NEWS README.rst ../
