#!/bin/sh -eux

install -Dm755 linux-boot-prober "$UB_INSTALLDIR"/usr/bin/linux-boot-prober
install -Dm755 os-prober "$UB_INSTALLDIR"/usr/bin/os-prober
install -Dm755 newns "$UB_INSTALLDIR"/usr/lib/os-prober/newns
install -Dm755 common.sh $UB_INSTALLDIR/usr/share/os-prober/common.sh

for dir in os-probes os-probes/mounted os-probes/init linux-boot-probes linux-boot-probes/mounted; do
	install -dm755 "$UB_INSTALLDIR/usr/lib/$dir"
	install -m755 -t "$UB_INSTALLDIR/usr/lib/$dir" "$dir"/common/*
	[[ -d "$dir"/x86 ]] && cp -r "$dir"/x86/* "$UB_INSTALLDIR/usr/lib/$dir"
done

install -Dm755 os-probes/mounted/powerpc/20macosx "$UB_INSTALLDIR"/usr/lib/os-probes/mounted/20macosx
