#!/bin/sh -eux

python3 setup.py build --build-lib=build/python3
python2 setup.py build --build-lib=build/python2
find build/python2 -type f -exec \
    sed -i '1s,^#! \?/usr/bin/\(env \|\)python$,#!/usr/bin/python2,' {} \;
