#!/bin/sh -eux

function py3doksi () {
    mkdir -p $py3docdir
    for doksik in `cat ${UB_SRCDIR}/doc`;do
        cp $doksik $py3docdir/
    done
}

py3docdir=$UB_INSTALLDIR/usr/share/doc/Packages/python3-msgpack

python3 setup.py build --build-lib=build/python3 \
    install --root="$UB_INSTALLDIR"

python2 setup.py build --build-lib=build/python2 \
    install --root="$UB_INSTALLDIR"

py3doksi
