#!/bin/sh -eux

cp docutils/{BUGS.txt,COPYING.txt,FAQ.txt,HISTORY.txt,README.txt,RELEASE-NOTES.txt,THANKS.txt} ./
cp -a docutils docutils3
cd docutils
python setup.py install --root="$UB_INSTALLDIR"
for _f in "$UB_INSTALLDIR"/usr/bin/*.py; do
      mv -v "$_f" "${_f%.py}2.py"
done
for f in "$UB_INSTALLDIR"/usr/bin/*2.py; do
      ln -s "$(basename $f)" "$UB_INSTALLDIR/usr/bin/$(basename $f .py)"
done
cd ../docutils3
python3 setup.py install --root="$UB_INSTALLDIR"
mkdir -p ${UB_INSTALLDIR}/usr/share/doc/Packages/python3-docutils
cp ../docutils/{BUGS.txt,COPYING.txt,FAQ.txt,HISTORY.txt,README.txt,RELEASE-NOTES.txt,THANKS.txt} \
${UB_INSTALLDIR}/usr/share/doc/Packages/python3-docutils/
