#!/bin/sh -eux

sed -i "/ADDITIONAL_OBJCFLAGS/s/=/= -fobjc-exceptions/" GNUmakefile
rm deps/Linux-deps/include/png.h
rm deps/Linux-deps/include/pngconf.h

export UB_TARGET="x86_64-unknown-linux"
export PYTHON=python3
CC=gcc make GNUSTEP_MAKEFILES="/usr/share/GNUstep/Makefiles" -f Makefile release-deployment
