#!/bin/sh -eux

sharedir=${UB_INSTALLDIR}/usr/share
mkdir -p ${sharedir}/{oolite,applications,pixmaps,doc/oolite}
cp -r oolite.app/* ${sharedir}/oolite/
install -D -m644 installers/FreeDesktop/oolite-icon.png ${sharedir}/pixmaps/oolite-icon.png
install -D -m644 installers/FreeDesktop/oolite.desktop ${sharedir}/applications/oolite.desktop
install -D -m644 Doc/*.pdf Doc/*.odt Doc/*.doc ${sharedir}/doc/oolite/
rm -rf ${UB_INSTALLDIR}/usr/include
