#!/bin/sh -eux

# ismert DM-ek: gdmflexiserver, kdmctl, lxdm, lightdm (dm-tool)
# image directory defaults: /usr/share/backgrounds/images/, /usr/share/wallpapers/

export RPM_PACKAGE_VERSION=no
ub_compile \
	--enable-locking \
	--with-x-app-defaults=/usr/share/X11/app-defaults \
	--with-login-manager=no \
	--with-image-directory=no \
	--with-text-file=no \
	--without-readdisplay \
	--without-shadow \
	--with-setuid-hacks \
	--with-pam \
	--with-gtk \
	--with-gl \
	--without-gle \
	--with-pixbuf \
	--with-proc-interrupts \
	--with-jpeg
