#!/bin/sh -eux

make \
	install_prefix="$UB_INSTALLDIR"/ \
	install

ln -sf graphic-login "$UB_INSTALLDIR"/etc/pam.d/xscreensaver

for i in "$UB_INSTALLDIR"/usr/share/man/man6/*.6; do
	mv "$i" "$i"xscr
done
rm -f "${UB_INSTALLDIR}"/usr/share/xscreensaver/config/{electricsheep,fireflies}.xml
