#!/bin/sh -eux

make \
	install_prefix="$UB_INSTALLDIR"/ \
	install

ln -sf graphic-login "$UB_INSTALLDIR"/etc/pam.d/xscreensaver

rm -f "${UB_INSTALLDIR}"/usr/share/xscreensaver/config/{electricsheep,fireflies}.xml
