#!/bin/sh -eux

ub_compile \
	--with-ssl \
	--with-gss \
	--with-gpgme \
	--with-gtkspell \
	--with-sqlite \
	--with-compface \
	--with-libsecret \
	--with-canberra \
	--with-ldap \
	--with-html-widget=webkit2
