#!/bin/bash -eux

ub_configure \
    --includedir=/usr/include \
    --with-gtk=3 \
    --with-opengl \
    --enable-unicode \
    --enable-graphics_ctx \
    --disable-precomp-headers \
    --with-regex=sys \
    --with-libpng=sys \
    --with-libxpm=sys \
    --with-libjpeg=sys \
    --with-libtiff=sys \
    --with-wx-config=/usr/bin/wx-config-gtk3

cd wxPython
python2 setup.py build
