#!/bin/sh -eux

make \
	DESTDIR="${UB_INSTALLDIR}" \
	XFIGDOCDIR=/usr/share/doc/xfig \
	LIBDIR=/usr/share \
	MANDIR=/usr/share/man/man1 \
	XAPPLOADDIR=/usr/share/X11/app-defaults \
install

mv "$UB_INSTALLDIR"/usr/bin/xfig "$UB_INSTALLDIR"/usr/bin/xfig.bin
