#!/bin/sh -eux

autoreconf -vif
export CPPFLAGS=" -I/usr/include/tirpc/"
export LDFLAGS+=" -ltirpc"
export PKG_CONFIG_PATH='/usr/lib/ffmpeg4.4/pkgconfig'
ub_compile \
	--enable-turbo \
	--disable-doxygen \
	--disable-sdl1 \
	--enable-toonz
