#!/bin/sh -eux

datadir="$UB_INSTALLDIR"/usr/share/games/xrick
install -d -m 755 $datadir
cp -r data.zip $datadir/
cp -r xrick.dsp $datadir/
install  --mode=755 xrick $datadir/
gunzip xrick.6.gz
install -m 644 xrick.6 "$UB_INSTALLDIR"/usr/share/man/man6/
