#!/bin/sh -eux

cellibdir=${UB_INSTALLDIR}/usr/lib
pcdir=${cellibdir}/pkgconfig
celbindir=${UB_INSTALLDIR}/usr/bin
make \
      TO_LIB="liblua.so liblua.so.${UB_VERSION_HEAD2} liblua.so.${UB_VERSION}" \
      INSTALL_DATA='cp -d' \
      INSTALL_TOP="${UB_INSTALLDIR}/usr" \
      INSTALL_MAN="${UB_INSTALLDIR}/usr"/share/man/man1 \
      install
      ln -sf /usr/bin/lua ${celbindir}/lua${UB_VERSION_HEAD2}
      ln -sf /usr/bin/luac ${celbindir}/luac${UB_VERSION_HEAD2}
      ln -sf /usr/lib/liblua.so.${UB_VERSION} ${cellibdir}/liblua${UB_VERSION_HEAD2}.so
      mkdir -p ${pcdir}
      ln -sf lua54.pc ${pcdir}/lua.pc
      ln -sf lua54.pc ${pcdir}/lua${UB_VERSION_HEAD2}.pc
      ln -sf lua54.pc ${pcdir}/lua-${UB_VERSION_HEAD2}.pc

cat > ${pcdir}/lua54.pc <<EOF

INSTALL_BIN=/usr/bin
INSTALL_INC=/usr/include
INSTALL_LIB=/usr/lib
INSTALL_MAN=/usr/man/man1
INSTALL_LMOD=/usr/share/lua/${UB_VERSION_HEAD2}
INSTALL_CMOD=/usr/lib/lua/$UB_VERSION_HEAD2

Name: Lua
Description: An Extensible Extension Language
Version: ${UB_VERSION}
Requires:
Libs: -L/usr/lib -llua -lm
Cflags: -I/usr/include

EOF
