#!/bin/sh -eux

mkdir -p $UB_INSTALLDIR/usr/share/pekwm/themes
rm -rf mavon-t-pekwm-0.1.4-pre2/bunfocus/.xvpics
# felesleges, jobb van a pekwm-themes csomagban
rm -rf clearlooks-0.1.4pre2
cp -r * $UB_INSTALLDIR/usr/share/pekwm/themes/
