#!/bin/sh -eux

ub_install

rm "$UB_INSTALLDIR"/usr/bin/on_ac_power

cp apm.1 apmsleep.1 "$UB_INSTALLDIR"/usr/share/man/man1/
cp apmd.8 "$UB_INSTALLDIR"/usr/share/man/man8/
mkdir -p "$UB_INSTALLDIR"/usr/share/man/fr/man1
cp apmsleep.fr.1 "$UB_INSTALLDIR"/usr/share/man/fr/man1/apmsleep.1
