#!/bin/sh -eux

sharedir="${UB_INSTALLDIR}/usr/share"
gamesdir="${sharedir}/games"
#installálás a make-val
make \
	DESTDIR="${UB_INSTALLDIR}" \
	datadir="${gamesdir}/foobillardplus/data" \
	prefix="${gamesdir}" \
	install
#kézimunka, uhusítás
install -d "${UB_INSTALLDIR}"/usr/{bin,share/{applications,pixmaps}}
mv "${gamesdir}"/foobillardplus.desktop "${sharedir}"/applications/
mv "${gamesdir}"/foobillardplus.{png,xbm} "${sharedir}"/pixmaps/
ln -s /usr/share/games/foobillardplus/bin/foobillardplus "${UB_INSTALLDIR}"/usr/bin/foobillardplus
