#!/bin/sh -eux

#pytest-devpi-server
mappak="pytest-devpi-server \
pytest-fixture-config \
pytest-git \
pytest-listener \
pytest-profiling \
pytest-pyramid-server \
pytest-qt-app \
pytest-server-fixtures \
pytest-shutil \
pytest-svn \
pytest-verbose-parametrize \
pytest-virtualenv \
pytest-webdriver"
for i in $mappak;do
cd $i
cp ../common* ../CHAN* ../LICE* ../READ* ../VERS*  ./
python2 setup.py install --root="$UB_INSTALLDIR"
python3 setup.py install --root="$UB_INSTALLDIR"
cd -
done
