#!/bin/sh -eux

cp target/release/me-tv $UB_INSTALLDIR/usr/bin/
cp target/release/me-tv-record $UB_INSTALLDIR/usr/bin/
cp target/release/me-tv-schedule $UB_INSTALLDIR/usr/bin/
cp doc/me-tv.1 $UB_INSTALLDIR/usr/share/man/man1/
