#!/bin/sh -eux

install -Dm755 target/release/czkawka_cli -t $UB_INSTALLDIR/usr/bin/
install -Dm755 target/release/czkawka_gui -t $UB_INSTALLDIR/usr/bin/
install -Dm644 data/com.github.qarmin.czkawka.desktop -t $UB_INSTALLDIR/usr/share/applications/
install -Dm644 data/icons/com.github.qarmin.czkawka.svg -t $UB_INSTALLDIR/usr/share/icons/hicolor/scalable/apps/
install -Dm644 data/com.github.qarmin.czkawka.metainfo.xml -t $UB_INSTALLDIR/usr/share/metainfo/
