#!/bin/sh -eux

ub_install

rm -Rf "$UB_INSTALLDIR"/usr/share/gnome/help/gnucash-help/{it,pt}
rm -Rf "$UB_INSTALLDIR"/usr/share/gnome/help/gnucash-guide/{it,ja,pt,ru}
rm -Rf "$UB_INSTALLDIR"/usr/share/gnucash-docs
