#!/bin/sh -eux

sed -i \
	-e "s:share/OGRE/docs:share/doc/ogre:" \
	Docs/CMakeLists.txt
sed -i \
	-e '/CONFIGURATIONS/s:CONFIGURATIONS Release.*::' \
	CMake/Utils/OgreConfigTargets.cmake
export CXXFLAGS+=' -Wno-deprecated-copy -Wno-deprecated-declarations -DBOOST_BIND_GLOBAL_PLACEHOLDERS -Wno-cast-qual '
export CXXFLAGS+=' -Wno-terminate -Wno-misleading-indentation -Wno-sequence-point -Wno-int-in-bool-context '
export CXXFLAGS+=' -Wmaybe-uninitialized -Wno-class-memaccess -Wno-shadow -Wno-sign-compare -Wno-switch '
ub_compile \
	-DOGRE_FULL_RPATH=NO \
	-DOGRE_BUILD_PLUGIN_CG=TRUE \
	-DOGRE_INSTALL_DOCS=FALSE \
	-DOGRE_BUILD_SAMPLES=FALSE \
	-DOGRE_INSTALL_SAMPLES=FALSE \
	-DOGRE_INSTALL_SAMPLES_SOURCE=FALSE \
	-DOGRE_BUILD_RENDERSYSTEM_GL=TRUE \
	-DOGRE_BUILD_TESTS=FALSE \
	-DOGRE_BUILD_TOOLS=TRUE \
	-DOGRE_CONFIG_ENABLE_ZIP=TRUE \
	-DOGRE_BUILD_RENDERSYSTEM_GLES=FALSE
