#!/bin/sh -eux

mkdir -p ${UB_INSTALLDIR}/usr/share/{XaoS/catalogs,XaoS/tutorial,applications,pixmaps}

cp build/XaoS ${UB_INSTALLDIR}/usr/bin/xaos

cp xdg/io.github.xaos_project.XaoS.desktop ${UB_INSTALLDIR}/usr/share/applications/
cp xdg/xaos.png ${UB_INSTALLDIR}/usr/share/pixmaps/

cp catalogs/*.cat ${UB_INSTALLDIR}/usr/share/XaoS/catalogs/
cp tutorial/*.xaf tutorial/*.xhf ${UB_INSTALLDIR}/usr/share/XaoS/tutorial/

cp -a examples ${UB_INSTALLDIR}/usr/share/XaoS/
