#!/bin/sh -eux

ub_install

#remove conflicting files with unixodbc
rm -f "$UB_INSTALLDIR"/usr/lib/libodbc.so
rm -f "$UB_INSTALLDIR"/usr/lib/libodbc.a
rm -f "$UB_INSTALLDIR"/usr/include/odbcinst.h
rm -f "$UB_INSTALLDIR"/usr/include/sql.h
rm -f "$UB_INSTALLDIR"/usr/include/sqlext.h
rm -f "$UB_INSTALLDIR"/usr/include/sqltypes.h
rm -f "$UB_INSTALLDIR"/usr/include/sqlucode.h
