#!/bin/sh -eux

install -m755 bzip2-shared "$UB_INSTALLDIR"/usr/bin/bzip2
install -m755 bzip2recover bzdiff bzgrep bzmore "$UB_INSTALLDIR"/usr/bin/
install -m644 bzip2.1 "$UB_INSTALLDIR"/usr/share/man/man1/
install -m644 bzlib.h "$UB_INSTALLDIR"/usr/include/

cp -dpR libbz2.so.* "$UB_INSTALLDIR"/usr/lib/
ln -sf /usr/lib/libbz2.so."$UB_VERSION" "$UB_INSTALLDIR"/usr/lib/libbz2.so
ln -sf /usr/lib/libbz2.so."$UB_VERSION" "$UB_INSTALLDIR"/usr/lib/libbz2.so.1

ln -sf bzip2 "$UB_INSTALLDIR"/usr/bin/bunzip2
ln -sf bzip2 "$UB_INSTALLDIR"/usr/bin/bzcat
ln -sf bzip2.1 "$UB_INSTALLDIR"/usr/share/man/man1/bunzip2.1
ln -sf bzip2.1 "$UB_INSTALLDIR"/usr/share/man/man1/bzcat.1
ln -sf bzip2.1 "$UB_INSTALLDIR"/usr/share/man/man1/bzip2recover.1
