#!/bin/sh -eux

ub_install

ln -sf aclocal "$UB_INSTALLDIR"/usr/bin/aclocal-"$UB_VERSION_HEAD2"
ln -sf aclocal "$UB_INSTALLDIR"/usr/bin/aclocal-1.15
ln -sf automake "$UB_INSTALLDIR"/usr/bin/automake-"$UB_VERSION_HEAD2"
ln -sf automake "$UB_INSTALLDIR"/usr/bin/automake-1.15
