#!/bin/sh -eux

mkdir -p build
cd build

# -system-webengine-icu

qmake \
    QMAKE_EXTRA_ARGS+="-system-webengine-icu -proprietary-codecs -system-ffmpeg -spellchecker" \
    ../qtwebengine.pro
ub_make
