#!/bin/sh -eux

ub_compile \
    --sbindir=/usr/sbin \
    --disable-sbin-override \
    --disable-gss \
	--enable-ipv6 \
	--enable-libmount-mount \
	--enable-mountconfig \
	--enable-nfsv4 \
	--enable-nfsv41
