#!/bin/sh -eux

# move from /lib to /usr/lib
sed -i -e 's|/lib|/usr/lib|' setup.py

python3 setup.py install --root="$UB_INSTALLDIR"

mkdir -p "$UB_INSTALLDIR"/usr/share/bash-completion/completions
cp shell-completion/bash "$UB_INSTALLDIR"/usr/share/bash-completion/completions/ufw
