#!/bin/sh -eux

python setup.py install --root="$UB_INSTALLDIR"

mkdir -p "$UB_INSTALLDIR"/usr/share/bash-completion/completions
cp shell-completion/bash "$UB_INSTALLDIR"/usr/share/bash-completion/completions/ufw
