#!/bin/sh -eux

cd py2
python2 setup.py install --root="$UB_INSTALLDIR"
cd ../py3
python3 setup.py install --root="$UB_INSTALLDIR"

mkdir -p "$UB_INSTALLDIR"/usr/share/doc/Packages/python2-psutil
cp "$UB_COMPILEDIR"/py2/{CREDITS,LICENSE,README*} "$UB_INSTALLDIR"/usr/share/doc/Packages/python2-psutil/
mkdir -p "$UB_INSTALLDIR"/usr/share/doc/Packages/python3-psutil
cp "$UB_COMPILEDIR"/py3/{CREDITS,LICENSE,README*} "$UB_INSTALLDIR"/usr/share/doc/Packages/python3-psutil/
