#!/bin/bash -eux

#előkészület
KVER="$(ls -1 /lib/modules | grep x86_64)"
moduldir="$UB_COMPILEDIR/lib/modules/"$KVER"/kernel/drivers/video"
mkdir -p $moduldir
forras="NVIDIA-Linux-x86_64-${UB_VERSION}-no-compat32"
#kicsomagolás és belépés
chmod +x $forras.run
./"$forras".run -x
mv $forras/* ./
rm *.run
patch -i "$UB_SRCDIR"/patches/menu.patch.skip
patch -Np1 < "$UB_SRCDIR"/patches/kernel-4.11.patch.skip
patch -Np1 < "$UB_SRCDIR"/patches/kernel-5.5.patch.skip
cd kernel
make IGNORE_CC_MISMATCH=yes SYSSRC=/usr/src/linux-$KVER KERNEL_UNAME="$KVER" MODULE_ROOT=$moduldir module
export UB_MAKE_PROCS=1
cd uvm
make SYSSRC=/usr/src/linux-$KVER KERNEL_UNAME="$KVER" MODULE_ROOT=$moduldir/uvm module
