#!/bin/sh -eux

make INSTALL_ROOT="$UB_INSTALLDIR" install

# nomake examples/demos
rm -Rf "$UB_INSTALLDIR"/usr/lib/qt4/{demos,examples}

# obsolete, újabb gstreammel nem működik a dolog, nincs qtwebkit, külön kell gyártani.
# kiszedjük a static lib utalásokat (QTBUG-12058)
#sed -i -e 's#-L\.\./\.\./WebCore/release ##g;s#-L\.\./\.\./JavaScriptCore/release ##g;s#-lwebcore ##g;s#-ljscore ##g' \
#	"$UB_INSTALLDIR"/usr/lib/qt4/lib/libQtWebKit.la \
#	"$UB_INSTALLDIR"/usr/lib/qt4/lib/pkgconfig/QtWebKit.pc

# a desktop fájlok kedvéért szimlinkelünk az /usr/bin-be - robert

ln -s ../lib/qt4/bin/assistant "$UB_INSTALLDIR"/usr/bin/assistant-qt4
ln -s ../lib/qt4/bin/qtconfig "$UB_INSTALLDIR"/usr/bin/qt4config
ln -s ../lib/qt4/bin/designer "$UB_INSTALLDIR"/usr/bin/designer-qt4
ln -s ../lib/qt4/bin/linguist "$UB_INSTALLDIR"/usr/bin/linguist-qt4
ln -s ../lib/qt4/bin/lrelease "$UB_INSTALLDIR"/usr/bin/lrelease-qt4
ln -s ../lib/qt4/bin/lupdate "$UB_INSTALLDIR"/usr/bin/lupdate-qt4
ln -s ../lib/qt4/bin/moc "$UB_INSTALLDIR"/usr/bin/moc-qt4
ln -s ../lib/qt4/bin/uic "$UB_INSTALLDIR"/usr/bin/uic-qt4
ln -s ../lib/qt4/bin/qmake "$UB_INSTALLDIR"/usr/bin/qmake-qt4
ln -s ../lib/qt4/bin/qdbusviewer "$UB_INSTALLDIR"/usr/bin/qdbusviewer-qt4
ln -s ../lib/qt4/bin/rcc "$UB_INSTALLDIR"/usr/bin/rcc-qt4

# ikonok a desktop fájlokhoz
install -Dm644 tools/assistant/tools/assistant/images/assistant-128.png \
                  "$UB_INSTALLDIR"/usr/share/pixmaps/assistant-qt4.png
install -Dm644 tools/designer/src/designer/images/designer.png \
                  "$UB_INSTALLDIR"/usr/share/pixmaps/designer-qt4.png
install -Dm644 tools/linguist/linguist/images/icons/linguist-128-32.png \
                  "$UB_INSTALLDIR"/usr/share/pixmaps/linguist-qt4.png
install -Dm644 tools/qdbus/qdbusviewer/images/qdbusviewer-128.png \
                  "$UB_INSTALLDIR"/usr/share/pixmaps/qdbusviewer-qt4.png
install -Dm644 tools/qtconfig/images/appicon.png "$UB_INSTALLDIR"/usr/share/pixmaps/qt4config.png

# pkgconfig linkek
mkdir -p "$UB_INSTALLDIR"/usr/lib/pkgconfig
for pc in "$UB_INSTALLDIR"/usr/lib/qt4/lib/pkgconfig/*.pc; do
	ln -s ../../lib/qt4/lib/pkgconfig/`basename $pc` "$UB_INSTALLDIR"/usr/lib/pkgconfig/`basename $pc`
done
