#!/bin/sh -eux

python setup.py install --root="$UB_INSTALLDIR"

for f in cygdb cython cythonize; do
    mv "$UB_INSTALLDIR"/usr/bin/$f "$UB_INSTALLDIR"/usr/bin/${f}2
done

python3 setup.py install --root="$UB_INSTALLDIR"
