#!/bin/sh -eux

ub_compile \
	--enable-scan-build \
	--enable-gui-build \
	--enable-fax-build \
	--enable-pp-build \
	--enable-policykit \
	--enable-qt4 \
	--enable-hpcups-install \
	--enable-hpijs-install \
	--enable-cups-drv-install \
	--enable-cups-ppd-install \
	--enable-foomatic-ppd-install \
	--enable-foomatic-drv-install \
	--enable-foomatic-rip-hplip-install \
	--enable-new-hpcups
