#!/bin/sh -eux

ub_compile \
	--with-pgsql \
	--with-sqlite \
	--with-mysql \
	--with-gssapi=plugin \
	--with-ldap=plugin \
	--with-solr \
	--with-zlib \
	--with-bzlib \
	--with-sql=plugin \
	--with-systemdsystemunitdir=/usr/lib/systemd/system/
