#!/bin/sh -eux

ub_install

cp -a doc ${UB_INSTALLDIR}/usr/share/doc/iproute2
mv -f ${UB_INSTALLDIR}/usr/share/doc/Packages/iproute2/examples ${UB_INSTALLDIR}/usr/share/doc/iproute2/
rm -rf ${UB_INSTALLDIR}/usr/share/doc/Packages
