#!/bin/sh -eux

opts=" \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --disable-silent-rules \
    --disable-werror \
    --enable-cache-stats \
    --enable-device-mapper \
    --enable-nls \
    --enable-grub-mkfont \
    --enable-grub-mount \
    --with-bootdir="/boot" \
    --with-grubdir=grub \
"

export FREETYPE="pkg-config freetype2"
export BUILD_FREETYPE="pkg-config freetype2"

cp unifont-15.1.04.bdf grub/unifont.bdf

touch grub/grub-core/extra_deps.lst

cp -r grub grub-bios
cp -r grub grub-efi

cd grub-bios
if [ -d .git ]; then
./bootstrap
else
./autogen.sh
fi
./configure \
	$opts \
	--enable-efiemu \
	--target="i386" \
	--enable-boot-time \
	--with-platform="pc"
make -j2

cd ../grub-efi
if [ -d .git ]; then
./bootstrap
else
./autogen.sh
fi
./configure \
	$opts \
	--disable-efiemu \
	--target=x86_64 \
	--enable-boot-time \
 	--with-platform="efi"
make -j2

cd ../grub
if [ -d .git ]; then
./bootstrap
else
./autogen.sh
fi
./configure \
	$opts \
	--enable-grub-emu-usb=no \
	--enable-grub-emu-sdl=no \
	--disable-grub-emu-pci \
	--target=x86_64 \
	--with-platform="emu"
make -j2
