#!/bin/sh -eux

ub_install
cp TeXmacs/misc/mime/texmacs.desktop "$UB_INSTALLDIR"/usr/share/applications/
cp TeXmacs/misc/pixmaps/TeXmacs.xpm "$UB_INSTALLDIR"/usr/share/pixmaps/
mkdir -p "$UB_INSTALLDIR"/usr/share/TeXmacs/fonts
cp -a fonts/. "$UB_INSTALLDIR"/usr/share/TeXmacs/fonts/
