#!/bin/sh -eux

cd openbox-themes-1.0.2/

mkdir -p ${UB_INSTALLDIR}/usr/share/themes
cp -r * ${UB_INSTALLDIR}/usr/share/themes/
rm -rf ${UB_INSTALLDIR}/usr/share/themes/debian
rm -rf ${UB_INSTALLDIR}/usr/share/doc
