#!/bin/sh -eux

ub_install
python3 setup.py install --root=$UB_INSTALLDIR
mkdir -p $UB_INSTALLDIR/usr/share/doc/Packages/python3-cycler
cp -r LICENSE README.rst $UB_INSTALLDIR/usr/share/doc/Packages/python3-cycler/
