#!/bin/sh -eux

mkdir -p $UB_INSTALLDIR/usr/share/icewm/themes
cp -r * $UB_INSTALLDIR/usr/share/icewm/themes/
cd $UB_INSTALLDIR/usr/share/icewm/themes/
rm -f Makefile *.spec
rm -rf ElbergRed/taskbar/.xvpics ElbergBlue/taskbar/.xvpics
