#!/bin/sh -eux

export PYCURL_SSL_LIBRARY=openssl

cd pycurl
python2 setup.py install --root="$UB_INSTALLDIR"

cd ../pycurl3
python3 setup.py install --root="$UB_INSTALLDIR"
cd ..

sharedoc=${UB_INSTALLDIR}/usr/share/doc
rm -rf $sharedoc/pycurl/examples
mv $sharedoc/pycurl ./pycurldoc
mkdir -p $sharedoc/Packages/
cp -a pycurldoc $sharedoc/Packages/python3-pycurl
