#!/bin/sh -eux

ub_compile \
	-Dptp-helper-permissions=capabilities \
	-Ddbghelp=disabled \
	-Dgobject-cast-checks=disabled \
	-Dglib-asserts=disabled \
	-Dglib-checks=disabled \
	-Dtests=disabled \
	-Dexamples=disabled \
	-Dbenchmarks=disabled \
	-Ddoc=disabled
