#!/bin/sh -eux

ub_compile \
	-DCMAKE_PREFIX_PATH=/usr/lib/qt6 \
	-DBUILD_TESTING=OFF \
	-DCMAKE_INSTALL_LIBEXECDIR=lib \
	-DCMAKE_INSTALL_LIBDIR=/usr/lib/qt6 \
	-DCMAKE_DISABLE_FIND_PACKAGE_packagekitqt6=ON \
	-DWITH_KCM=OFF \
	-DBUILD_DummyBackend=OFF \
	-DBUILD_FlatpakBackend=ON \
	-DBUILD_FwupdBackend=ON \
	-DBUILD_RpmOstreeBackend=OFF \
	-DBUILD_SnapBackend=OFF \
	-DBUILD_SteamOSBackend=OFF \
