#!/bin/sh -eux

git clone https://github.com/eranif/ctags.git ctags
git clone https://github.com/eranif/dbgd.git wxdap
git clone https://github.com/jbeder/yaml-cpp yaml-cpp
cd yaml-cpp
git checkout 1b50109

cd -

export CXXFLAGS=" -fno-devirtualize"
ub_compile \
    -DCMAKE_INSTALL_LIBDIR=lib
