#!/bin/sh -eux

git clone https://github.com/eranif/ctags.git ctags
git clone https://github.com/eranif/dbgd.git wxdap

export CXXFLAGS=" -fno-devirtualize"
ub_compile \
    -DCMAKE_INSTALL_LIBDIR=lib
