#!/bin/sh -eux

export UB_MAKE_PROCS=1
ub_compile \
	-DREPLAY_GAIN_INCLUDE_DIR=${UB_COMPILEDIR}/libreplaygain/include \
    -DREPLAY_GAIN_LIBRARY:FILEPATH=${UB_COMPILEDIR}/build/libreplaygain/src/libreplaygain.a \
    -DCUEFILE_INCLUDE_DIR=${UB_COMPILEDIR}/libcuefile/include \
    -DCUEFILE_LIBRARY:FILEPATH=${UB_COMPILEDIR}/build/libcuefile/src/libcuefile.a ..
