#!/bin/sh -eux

cd twisted3
python3 setup.py install --prefix=/usr --root="$UB_INSTALLDIR" --optimize=1
mkdir -p  $UB_INSTALLDIR/usr/share/doc/Packages/python3-incremental
cp {README.rst,NEWS.rst,LICENSE} $UB_INSTALLDIR/usr/share/doc/Packages/python3-incremental/
mv {README.rst,NEWS.rst,LICENSE} ../
cd ../twisted
python setup.py install --prefix=/usr --root="$UB_INSTALLDIR" --optimize=1
