#!/bin/sh -eux

sed -i 's/create=xarchiver --add-to %F/create=xarchiver --compress %F/' data/archivers.list

# ha még nincs menu-cache
export BOOTSTRAP=0
autoreconf -vif
if [ $BOOTSTRAP = "1" ]; then
ub_configure \
	--with-extra-only

else
ub_configure \
	--enable-udisks \
	--with-gnu-ld \
	--with-html-dir=/usr/share/doc/libfm/html \
	--with-gtk=3

fi

ub_make
