#!/bin/sh -eux

ub_install

mkdir -p $UB_INSTALLDIR/usr/lib/qt5/mkspecs/features
mv $UB_INSTALLDIR/usr/share/mkspecs/features/kdsoap.prf $UB_INSTALLDIR/usr/lib/qt5/mkspecs/features/kdsoap.prf
rm -Rf $UB_INSTALLDIR/usr/share/mkspecs
