#!/bin/sh -eux

cd build
ub_install install-gdb install-info-gdb

# remove conflicting files
rm -rf "$UB_INSTALLDIR"/usr/include
rm -rf "$UB_INSTALLDIR"/usr/lib/lib{ctf*,bfd*,opcodes*,iberty*,mmalloc*}
rm -rf "$UB_INSTALLDIR"/usr/share/info
#binutils-dev ütközés
rm -rf "$UB_INSTALLDIR"/usr/lib/libsframe.a
