#!/bin/sh -eux

ub_compile \
    -Denable-libcolordcompat=true \
    -Denable-vala=true \
    -Denable-print-profiles=true \
    -Dwith-daemon-user=colord \
    -Denable-argyllcms-sensor=true \
    -Dman=false \
    -Ddocs=false
