#!/bin/sh -eux

ub_install

if [ ! -f "$UB_INSTALLDIR"/usr/bin/regina ]; then
	ln -s regina32 "$UB_INSTALLDIR"/usr/bin/regina
fi
if [ ! -f "$UB_INSTALLDIR"/usr/bin/rexx ]; then
	ln -s rexx32 "$UB_INSTALLDIR"/usr/bin/rexx
fi

cp -a regina.pdf "$UB_INSTALLDIR"/usr/share/Regina-REXX/
cp -a regina64.xpm "$UB_INSTALLDIR"/usr/share/Regina-REXX/
cp -a regutil.pdf "$UB_INSTALLDIR"/usr/share/Regina-REXX/

for i in animal block dateconv gci-try newstr rexxcps timeconv; \
	do 	echo "#!/usr/bin/rexx" >demo/$i; \
		cat demo/$i.rexx >>demo/$i; chmod 755 demo/$i; \
		cp -a demo/$i "$UB_INSTALLDIR"/usr/share/Regina-REXX/$i.rexx; \
	done;

cp -a trip "$UB_INSTALLDIR"/usr/share/Regina-REXX/
