#!/bin/sh -eux

export CC=clang
export CXX=clang++
export AR=llvm-ar
export NM=llvm-nm
export RANLIB=llvm-ranlib

export PYTHON=/usr/bin/python3
export MACH_USE_SYSTEM_PYTHON=1

export RUSTFLAGS="-C embed-bitcode"

: > .mozconfig
cat > .mozconfig << _EOF_
mk_add_options MOZ_OBJDIR=$UB_OBJECTDIR
ac_add_options --enable-application=js
ac_add_options --prefix=/usr
ac_add_options --enable-release
ac_add_options --enable-hardening
ac_add_options --enable-optimize
ac_add_options --enable-rust-simd
ac_add_options --enable-linker=lld
ac_add_options --disable-bootstrap
ac_add_options --disable-debug
ac_add_options --disable-debug-symbols
ac_add_options --disable-jemalloc
ac_add_options --disable-rust-simd
ac_add_options --disable-strip
ac_add_options --disable-tests
ac_add_options --with-system-zlib
ac_add_options --with-system-icu
ac_add_options --enable-readline
ac_add_options --enable-shared-js
ac_add_options --with-intl-api
_EOF_

"$UB_COMPILEDIR"/mach build
