#!/bin/sh -eux

ub_install

install -D -m755 url_handler.sh "$UB_INSTALLDIR"/etc/urlview/url_handler.sh
install -D -m644 sample.urlview "$UB_INSTALLDIR"/etc/urlview/system.urlview
ln -fs ../../../etc/urlview/url_handler.sh "$UB_INSTALLDIR"/usr/bin/url_handler.sh
