#!/bin/sh -eux

ub_install
mv ${UB_INSTALLDIR}/usr/bin/gzdoom ${UB_INSTALLDIR}/usr/share/games/doom
mkdir -p ${UB_INSTALLDIR}/usr/share/icons/hicolor/256x256/apps
cp src/posix/zdoom.xpm ${UB_INSTALLDIR}/usr/share/icons/hicolor/256x256/apps/gzdoom.xpm
