#!/bin/sh -eux

ub_install
cp -r ${UB_INSTALLDIR}/usr/share/gzdoom/fm_banks ${UB_INSTALLDIR}/usr/share/games/doom/
cp -r ${UB_INSTALLDIR}/usr/share/gzdoom/soundfonts ${UB_INSTALLDIR}/usr/share/games/doom/
rm -rf ${UB_INSTALLDIR}/usr/share/gzdoom
mv ${UB_INSTALLDIR}/usr/bin/gzdoom ${UB_INSTALLDIR}/usr/share/games/doom/
mkdir -p ${UB_INSTALLDIR}/usr/share/icons/hicolor/256x256/apps
cp src/posix/zdoom.xpm ${UB_INSTALLDIR}/usr/share/icons/hicolor/256x256/apps/gzdoom.xpm
