#!/bin/sh -eux

# A -O3 veszélyes
ub_replace -O3 -O2 configure
ub_replace -O3 -O2 Modules/zlib/configure
ub_replace -O3 -O2 Modules/zlib/Makefile.in

ub_configure \
	--enable-unicode=ucs4 \
	--with-system-expat \
	--with-system-ffi \
	--enable-ipv6
ub_make
