#!/bin/sh -eux

# A -O3 veszélyes
ub_replace -O3 -O2 configure

# a tk függ a tcl-től
TCLTKLIBS=$(pkg-config --libs tk)

ub_configure \
	--enable-unicode=ucs4 \
	--with-system-expat \
	--with-system-ffi \
	--enable-ipv6 \
	--with-tcltk-includes='-I/usr/include' \
	--with-tcltk-libs="-L/usr/lib $TCLTKLIBS"
ub_make
