#!/bin/sh -eux

export CXXFLAGS="-DPARANOID"
ub_compile \
    --enable-x86-debugger \
    --enable-ne2000 \
    --enable-pci \
    --enable-clgd54xx \
    --enable-sb16=linux \
    --enable-3dnow \
    --with-x11 \
    --with-nogui \
    --with-term \
    --with-rfb \
    --with-sdl2 \
    --without-wx \
    --enable-cpu-level=6 \
    --enable-disasm \
    --enable-e1000 \
    --enable-x86-64 \
    --enable-smp

#cd bios
#make bios
#cp BIOS-bochs-latest BIOS-bochs-kvm
