#!/bin/sh -eux

ub_compile \
	--disable-docbook \
	--enable-plugins \
	--enable-cpu-level=6 \
	--enable-ne2000 \
	--enable-pci \
	--enable-usb \
	--enable-repeat-speedups \
	--enable-fast-function-calls \
	--enable-disasm \
	--enable-readline \
	--enable-fpu \
	--enable-3dnow \
	--enable-x86-64 \
	--enable-debugger \
	--enable-cdrom \
	--enable-sb16=linux \
	--enable-gameport \
	--enable-smp \
	--enable-avx \
	--enable-xpm \
	--enable-clgd54xx \
	--with-x11 \
	--with-x \
	--with-term \
	--with-sdl
