#!/bin/sh -eux

# Install icon into icons directory
sed -i 's|$(datadir)/pixmaps|$(datadir)/icons/hicolor/48x48/apps|' pixmaps/Makefile.am
convert pixmaps/gwget-large.png +set date:create +set date:modify -background none -extent 200x200 pixmaps/gwget-large.png

autoreconf -vif

export CFLAGS=' -fcommon'
ub_compile \
	--disable-epiphany-extension \
	--disable-schemas-compile
