#!/bin/sh -eux

ub_install

install -dm755 "$UB_INSTALLDIR"/usr/share/icons/hicolor/{64x64,128x128}/apps/
convert pixmaps/gwget-large.png +set date:create +set date:modify -resize 64x64 -alpha on "$UB_INSTALLDIR/usr/share/icons/hicolor/64x64/apps/gwget.png"
convert pixmaps/gwget-large.png +set date:create +set date:modify -resize 128x128 -alpha on "$UB_INSTALLDIR/usr/share/icons/hicolor/128x128/apps/gwget.png"
