#!/bin/sh -eux

#touch __init__.py

pythonver=$(python -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')
export PYTHONPATH=`pwd`:/usr/lib/python$pythonver
./waf configure \
		--prefix=/usr \
		--dbus \
		--classic \
		--systemd-unit
./waf build
