#!/bin/sh -eux

export UB_MAKE_PROCS=1
export CPPFLAGS=-I/usr/include/openssl-1.0
export LDFLAGS=-L/usr/lib/openssl-1.0
export COPTS=' -fPIC'
export CXXOPTS=' -fPIC -fpermissive -fno-tree-dce -fno-optimize-sibling-calls'
export VERBOSE=1
ub_compile
