#!/bin/sh -e

if [ "$2" = "upgrade" -o "$2" = "purge" ]; then
	exit 0
fi

if [ ! -f /var/lib/uhu-pkg/ldconfig ]; then
	[ -z "${UHU_PKG_QUIET+x}" ] && echo -n "  Running ldconfig ..."
	/usr/sbin/ldconfig -X
	true > /var/lib/uhu-pkg/ldconfig
	while [ ! /var/lib/uhu-pkg/ldconfig -ot /var/lib/dpkg/info \
	     -a ! /var/lib/uhu-pkg/ldconfig -nt /var/lib/dpkg/info ]; do
		sleep 0.1
		true > /var/lib/uhu-pkg/ldconfig
	done
	[ -z "${UHU_PKG_QUIET+x}" ] && echo
fi
