diff -Naur skinsoppalusikka-2.4.0-orig/Makefile skinsoppalusikka-2.4.0/Makefile
--- skinsoppalusikka-2.4.0-orig/Makefile	2018-04-15 20:30:40.000000000 +0200
+++ skinsoppalusikka-2.4.0/Makefile	2019-10-05 19:08:34.006526951 +0200
@@ -28,7 +28,7 @@
 
 export CFLAGS   = $(call PKGCFG,cflags)
 export CXXFLAGS = $(call PKGCFG,cxxflags)
-STRIP           ?= /bin/true
+STRIP           ?= /usr/bin/true
 
 ### The version number of VDR's plugin API:
 
