#!/bin/sh -eux

ub_compile \
	--disable-shared \
	--enable-dselect \
	--enable-start-stop-daemon \
	--enable-update-alternatives \
	--enable-disk-preallocate

rm -f po/hu.gmo
msgfmt po/hu.po -o po/hu.gmo
