#!/bin/sh -eux

# prepare installation
mkdir -p "$UB_INSTALLDIR/etc/dpkg/origins"
mkdir -p "$UB_INSTALLDIR/usr/share/doc/dpkg"
mkdir -p "$UB_INSTALLDIR/var/lib/dpkg"

# install
ub_install

# remove docs, they are installed via the "doc" file
rm -r "$UB_INSTALLDIR/usr/share/doc/dpkg"
