#!/bin/sh -eux

g++ -fPIC -shared -Dunix -c -Wall -O2 -DNDEBUG libzpaq.cpp -o libzpaq.so
chmod +x libzpaq.so

g++ -fPIC -static -Dunix -c -Wall -O2 -DNDEBUG libzpaq.cpp -o libzpaq.o
ar rcs libzpaq.a libzpaq.o

#ub_replace -O3 -O2 Makefile

ub_make
