#!/bin/sh -eux

make DESTDIR=${UB_INSTALLDIR} PREFIX=/usr install

mkdir -p "$UB_INSTALLDIR"/usr/lib/pkgconfig
cat >"$UB_INSTALLDIR"/usr/lib/pkgconfig/libcrypto++.pc <<EOF
prefix=/usr
libdir=\${prefix}/lib
includedir=\${prefix}/include/cryptopp

Name: libcrypto++
Description: General purpose cryptographic shared library
URL: http://www.cryptopp.com
Version: ${UB_VERSION}
Requires:
Libs: -L\${libdir} -lcryptopp
Cflags: -I\${includedir}
EOF

rm -rf ${UB_INSTALLDIR}/usr/bin  ${UB_INSTALLDIR}/usr/share/cryptopp
