#!/bin/sh -eux

ub_compile \
    -Dxorg=true \
    -Dxephyr=true \
    -Dglamor=true \
    -Dxnest=true \
    -Dxwin=false \
    -Dbuilder_addr="ubk@ubk.hu" \
    -Dbuilder_string="ubk.hu" \
    -Ddefault_font_path="/usr/share/fonts/misc,/usr/share/fonts/75dpi,/usr/share/fonts/100dpi,/usr/share/fonts/truetype,/usr/share/fonts/Type1,/usr/share/fonts/ghostscript,/usr/share/fonts/unifont,/usr/share/fonts/freefont" \
    -Dxdm-auth-1=true \
    -Dsecure-rpc=false \
    -Dxkb_output_dir="/var/lib/xkb" \
    -Dsuid_wrapper=false \
	-Dudev=true \
	-Dhal=false \
	-Dxf86bigfont=true \
	-Dxinerama=true \
	-Dxcsecurity=true \
	-Ddga=true \
	-Ddri3=true \
	-Dlibunwind=true
