#!/bin/sh -eux

cd "$UB_OBJECTDIR"

export PYTHON=/usr/bin/python3
export MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE=system
DESTDIR="$UB_INSTALLDIR" "$UB_COMPILEDIR"/mach install

rm -f "$UB_INSTALLDIR"/usr/lib/thunderbird/thunderbird
rm -f "$UB_INSTALLDIR"/usr/bin/thunderbird

mkdir -p "$UB_INSTALLDIR"/usr/lib/thunderbird/extensions
mv "$UB_COMPILEDIR"/hu.xpi "$UB_INSTALLDIR"/usr/lib/thunderbird/extensions/langpack-hu@thunderbird.mozilla.org.xpi

# install icons
for i in 16 22 24 32 48 64 128 256; do
    install -Dm644 "$UB_COMPILEDIR"/comm/mail/branding/thunderbird/default${i}.png \
      "$UB_INSTALLDIR/usr/share/icons/hicolor/${i}x${i}/apps/thunderbird.png"
done
cp "$UB_COMPILEDIR"/comm/mail/branding/thunderbird/default48.png "$UB_INSTALLDIR"/usr/share/pixmaps/thunderbird.png

cd "$UB_INSTALLDIR"/usr/lib/thunderbird
ln -s thunderbird-bin thunderbird
cd -
