#!/bin/sh -eux

mkdir -p $UB_INSTALLDIR/usr/lib/thunderbird
cp -a * $UB_INSTALLDIR/usr/lib/thunderbird/

_vendorjs="$UB_INSTALLDIR/usr/lib/thunderbird/defaults/preferences/vendor.js"
install -Dm644 /dev/stdin "$_vendorjs" <<END
// Use LANG environment variable to choose locale
pref("intl.locale.matchOS", true);

// Disable default mailer checking.
pref("mail.shell.checkDefaultMail", false);

// Don't disable our bundled extensions in the application directory
pref("extensions.autoDisableScopes", 11);
pref("extensions.shownSelectionUI", true);
END

# icons
for i in 16 22 24 32 48 256; do
    install -d "$UB_INSTALLDIR"/usr/share/icons/hicolor/${i}x${i}/apps/
    ln -s /usr/lib/thunderbird/chrome/icons/default/default$i.png \
          "$UB_INSTALLDIR"/usr/share/icons/hicolor/${i}x${i}/apps/thunderbird.png
done

  # Use system-provided dictionaries
  # rm -r "$UB_INSTALLDIR"/usr/lib/thunderbird/dictionaries # Not in 68.0
  ln -Ts /usr/share/hunspell "$UB_INSTALLDIR"/usr/lib/thunderbird/dictionaries
  ln -Ts /usr/share/hyphen "$UB_INSTALLDIR"/usr/lib/thunderbird/hyphenation

# Use system certificates
  ln -sf /usr/lib/libnssckbi.so "$UB_INSTALLDIR"/usr/lib/thunderbird/libnssckbi.so

ln -s /usr/lib/thunderbird/thunderbird "$UB_INSTALLDIR"/usr/bin/thunderbird
