#!/bin/sh -eux

# xfce: gtk2

export CXXFLAGS+=' -std=c++11'
NOCONFIGURE=1 ./autogen.sh
ub_compile \
	--disable-distribution \
	--disable-gconf \
	--disable-xml \
	--enable-dbus \
	--enable-gnome3 \
	--enable-mate \
	--enable-xfce
