#!/bin/bash -eux

ub_compile \
    --systemdsystemunitdir=$(pkg-config --variable=systemdsystemunitdir systemd) \
    --bashcompletiondir=$(pkg-config --variable=completionsdir bash-completion) \
    --libdir=/usr/lib
