#!/bin/sh -eux

cd snowballstemmer
python setup.py install --root="$UB_INSTALLDIR"
cd ../snowballstemmer3
python3 setup.py install --root="$UB_INSTALLDIR"

py3docdir=${UB_INSTALLDIR}/usr/share/doc/Packages/python3-snowballstemmer
mkdir -p $py3docdir
cp LICENSE.rst README.rst $py3docdir/
