.TH UNARJ 1
.SH NAME
\fBunarj\fR   \- Unarchiver for the ARJ archiving utility.
.SH DESCRIPTION
\fBunarj\fR is a un-archiver for the traditional DOS archiver
called ARJ.  At this stage it will only unarchive the .ARJ'd
file on Linux systems - There is no current plan by Robert
Jung to distribute the creation of ARJ packages under the
Unix platform.
.PP
For more information on \fBunarj\fR and its command line switches -
either run the executable without any options or read the documentation
in the \fB/usr/share/doc/unarj\fR directory.
.PP
