#!/bin/sh -eux

install -d "$UB_INSTALLDIR"/usr/share/makeself
install -m755 makeself.sh "$UB_INSTALLDIR"/usr/bin/makeself
install -m644 makeself.1 "$UB_INSTALLDIR"/usr/share/man/man1/
install -m755 makeself-header.sh "$UB_INSTALLDIR"/usr/share/makeself/
sed -e 's|HEADER=`dirname $0`/makeself-header.sh|HEADER=/usr/share/makeself/makeself-header.sh|' -i "$UB_INSTALLDIR"/usr/bin/makeself
