#!/bin/sh -eux

ub_install

# myspell/hunspell symlink
install -dm755 ${UB_INSTALLDIR}/usr/share/myspell/dicts
ln -sv /usr/share/hyphen/hyph_en_US.dic ${UB_INSTALLDIR}/usr/share/myspell/dicts/hyph_en_US.dic
