#!/bin/sh -eux

### BoostPython2.cmake:
## find_boost_python3() tries to find the package with different component
## names. By default it tries "python3", "python-py$suffix" and
## "python-$dotsuffix", where suffix is based on the `python_version` argument.
## One can supply a custom component name by setting the
## `CALAMARES_BOOST_PYTHON3_COMPONENT` variable at CMake time.
#set( CALAMARES_BOOST_PYTHON3_COMPONENT python3 CACHE STRING
#    "Name of the Boost.Python component. If Boost.Python is installed as
#    libboost_python-foo.so then this variable should be set to 'python-foo'."
#)

cd lang/python/hu/LC_MESSAGES
rm python.mo
msgfmt -o python.mo python.po
cd -
ub_compile \
	-DCMAKE_PREFIX_PATH=/usr/lib/qt5 \
	-DCMAKE_BUILD_TYPE=Debug \
	-DCMAKE_INSTALL_LIBDIR=/usr/lib \
	-DCALAMARES_BOOST_PYTHON3_COMPONENT="python37" \
	-DINSTALL_CONFIG=ON
