#!/bin/sh -eux

# cd lang/python/hu/LC_MESSAGES
# rm python.mo
# msgfmt -o python.mo python.po
# cd -
ub_compile \
	-DCMAKE_PREFIX_PATH=/usr/lib/qt5 \
	-DCMAKE_BUILD_TYPE=Debug \
	-DCMAKE_INSTALL_LIBDIR=/usr/lib
