#!/bin/sh -eux

ub_install

# https://github.com/calamares/calamares/commit/8f72d2541f241ef5a1f4bc945bdc908e7dbe9fdd
mkdir -p $UB_INSTALLDIR/usr/share/calamares/modules

find $UB_COMPILEDIR/build/src/modules -name "*.conf" -exec cp {} $UB_INSTALLDIR/usr/share/calamares/modules \;
cp settings.conf $UB_INSTALLDIR/usr/share/calamares/settings.conf

cp $UB_INSTALLDIR/usr/share/calamares/settings.conf $UB_INSTALLDIR/usr/share/calamares/settings.conf.net
cp $UB_INSTALLDIR/usr/share/calamares/modules/welcome.conf $UB_INSTALLDIR/usr/share/calamares/modules/welcome.conf.net
cp $UB_INSTALLDIR/usr/share/calamares/modules/packages.conf $UB_INSTALLDIR/usr/share/calamares/modules/packages.conf.net

rm -Rf $UB_INSTALLDIR/usr/include
rm -Rf $UB_INSTALLDIR/usr/lib/cmake
