diff -Nur orig/Makefile mod/Makefile
--- orig/Makefile	2017-12-21 15:38:04.000000000 +0100
+++ mod/Makefile	2018-01-09 17:41:03.248733516 +0100
@@ -907,7 +907,7 @@
 endif
 ifndef INSTALL_PREFIX
 ifdef UNIXHier
-INSTALL_PREFIX=/usr/local
+INSTALL_PREFIX=$(DESTDIR)/usr
 else
 ifdef INSTALL_FPCPACKAGE
 INSTALL_BASEDIR:=/pp
