#!/bin/sh -eux

ub_install

ln -s /usr/share/lirc/contrib/irman2lirc ${UB_INSTALLDIR}/usr/bin/irman2lirc

mkdir -p ${UB_INSTALLDIR}/usr/share/lirc
mv remotes ${UB_INSTALLDIR}/usr/share/lirc/remotes

# Az alap kernel rules
mkdir -p ${UB_INSTALLDIR}/etc/udev/rules.d
cp contrib/60-lirc.rules ${UB_INSTALLDIR}/etc/udev/rules.d/

# Ez letiltja a kernel lirc-et, lehasított csomagrész
cp contrib/99-remote-control-lirc.rules ${UB_INSTALLDIR}/etc/udev/rules.d/

# Doksi html fájlok
mkdir -p ${UB_INSTALLDIR}/usr/share/doc/lirc
cp -a doc/plugindocs ${UB_INSTALLDIR}/usr/share/doc/lirc/
