#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR"/usr/lib/nagios
cp -a src/check_nrpe "$UB_INSTALLDIR"/usr/lib/nagios/
cp -a src/nrpe "$UB_INSTALLDIR"/usr/sbin/
cp -a sample-config/nrpe.cfg "$UB_INSTALLDIR"/etc/
