#!/bin/sh -eux

ub_replace "test_fsel_LDADD = \$(GP_LIBS) \$(GTK_LIBS) ../src/libgtkam.a" \
	"test_fsel_LDADD = \$(GP_LIBS) \$(GTK_LIBS) \$(EXIF_LIBS) ../src/libgtkam.a" \
	"test/Makefile.in"

ub_replace "test_cancel_LDADD = \$(GP_LIBS) \$(GTK_LIBS) ../src/libgtkam.a" \
	"test_cancel_LDADD = \$(GP_LIBS) \$(GTK_LIBS) \$(EXIF_LIBS) ../src/libgtkam.a" \
	"test/Makefile.in"

ub_compile \
    --without-bonobo \
    --without-gnome
