#!/bin/sh -eux

ub_install
make -C src DESTDIR="$UB_INSTALLDIR" uninstall-binPROGRAMS
make -C src/tools DESTDIR="$UB_INSTALLDIR" uninstall
make -C src/compositor/plugins DESTDIR="$UB_INSTALLDIR" uninstall
make -C doc/man DESTDIR="$UB_INSTALLDIR" uninstall
