#!/bin/sh -eux

# Convert header of HUNSPELL_heading from ISO-8859-2 to UTF-8.
perl -e '
	use Encode qw(from_to);
	my $convert = 1;
	while (<>) {
		from_to($_, "ISO-8859-2", "UTF-8") if $convert;
		$convert = 0 if /^NAME/;
		print;
	}
' <HUNSPELL_heading >HUNSPELL_heading.tmp
touch -r HUNSPELL_heading HUNSPELL_heading.tmp
mv HUNSPELL_heading.tmp HUNSPELL_heading

# Convert other files, too.
for i in ChangeLog GYIK OLVASSEL README tipikus/*; do
	if ! iconv -f UTF-8 -t UTF-8 <"$i" >/dev/null 2>&1; then
		iconv -f ISO-8859-2 -t UTF-8 <"$i" >"$i.tmp"
		touch -r "$i" "$i.tmp"
		mv "$i.tmp" "$i"
	fi
done

make
make -C doc
