#!/bin/sh -eux

ub_install
install -m 755 libxnee/src/.libs/libxnee.so.0.0.0 "$UB_INSTALLDIR"/usr/lib/
(
	cd "$UB_INSTALLDIR"/usr/lib/
	ln -s libxnee.so.0.0.0 libxnee.so.0
	ln -s libxnee.so.0.0.0 libxnee.so
)
