#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR"/etc
ln -s /proc/self/mounts "$UB_INSTALLDIR"/etc/mtab

mkdir -p "$UB_INSTALLDIR"/var/spool
ln -s ../mail "$UB_INSTALLDIR"/var/spool/mail

rm -rf "$UB_INSTALLDIR"/sbin
ln -sf usr/sbin "$UB_INSTALLDIR"/sbin

rm -rf "$UB_INSTALLDIR"/bin
ln -sf usr/bin "$UB_INSTALLDIR"/bin
