#!/bin/sh -eux

ub_install

rm -f $UB_INSTALLDIR/usr/bin/kill
rm -f $UB_INSTALLDIR/usr/share/bash-completion/completions/runuser
rm -Rf $UB_INSTALLDIR/etc/pam.d
rm -Rf $UB_INSTALLDIR/usr/share/doc/util-linux
