#!/bin/sh -eux

export UB_MAKE_PROCS=1
export CFLAGS+="-O2"
mkdir -p include/curl
touch include/curl/types.h
./configure \
    --prefix=/usr \
	--enable-libxml2-backend	\
	--disable-abyss-server		\
	--disable-wininet-client	\
	--disable-libwww-client
make
