#!/bin/sh -eux

mkdir -p $UB_INSTALLDIR/usr/share/games/
unzip -o dangerdeep-data-${UB_VERSION}.zip -d $UB_INSTALLDIR/usr/share/games
mv $UB_INSTALLDIR/usr/share/games/data $UB_INSTALLDIR/usr/share/games/dangerdeep
ikonhely=$UB_INSTALLDIR/usr/share/pixmaps
mandir=$UB_INSTALLDIR/usr/share/man/man6
mkdir -p $ikonhely $mandir
scons installbindir=$UB_INSTALLDIR/usr/bin datadir='/usr/share/games/dangerdeep' install
cp dftd_icon.xpm $ikonhely/
cp doc/man/dangerdeep.6 $mandir/
mv $UB_INSTALLDIR/usr/bin/dangerdeep $UB_INSTALLDIR/usr/share/games/dangerdeep.bin
