#!/bin/bash -eux

#előkészület
KVER="$(ls -1 /usr/lib/modules | grep x86_64)"
forras="NVIDIA-Linux-x86_64-${UB_VERSION}-no-compat32"
moduldir="$UB_COMPILEDIR/usr/lib/modules/"$KVER"/kernel/drivers"
mkdir -p $moduldir
#kicsomagolás és belépés
chmod +x $forras.run
./"$forras".run -x
mv $forras/* ./
rm $forras.*
sed -i 's/__NV_VK_ICD__/libGLX_nvidia.so.0/' nvidia_icd.json.template
sed -i 's%__UTILS_PATH__/%%' nvidia-settings.desktop
sed -i 's%__PIXMAP_PATH__/nvidia-settings.png%nvidia-settings%' nvidia-settings.desktop
bsdtar -xf nvidia-persistenced-init.tar.bz2
cd kernel
make SYSSRC=/usr/src/linux-$KVER KERNEL_UNAME="$KVER" MODULE_ROOT=$moduldir module
cd ../nvsett
export NV_USE_BUNDLED_LIBJANSSON=0
export PREFIX=/usr
ub_compile
