#!/bin/bash -eux
function alprogi {
	cd $1
    export PREFIX=/usr
    ub_compile
    cd ..
}

#előkészület
KVER="$(ls -1 /lib/modules | grep x86_64)"
forras="NVIDIA-Linux-x86_64-${UB_VERSION}-no-compat32"
moduldir="$UB_COMPILEDIR/lib/modules/"$KVER"/kernel/drivers"
mkdir -p $moduldir
#kicsomagolás és belépés
chmod +x $forras.run
./"$forras".run -x
mv $forras/* ./
rm -rf $forras
patch -Np1 < "$UB_SRCDIR"/patches/nvidia-json.skip
cd kernel
patch -Np1 < "$UB_SRCDIR"/patches/drm-detection.skip
make SYSSRC=/usr/src/linux-$KVER KERNEL_UNAME="$KVER" MODULE_ROOT=$moduldir module
cd ..
export NV_USE_BUNDLED_LIBJANSSON=0
alprogi settings
alprogi xconfig
alprogi modprobe
alprogi persistenced
