#!/bin/sh -eux

ub_compile \
        -DCMAKE_INSTALL_LIBDIR=/usr/lib \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_INCLUDEDIR=/usr/include \
        -DCMAKE_INSTALL_FULL_LIBDIR=/usr/lib
