#!/bin/sh -eux

ub_install

mv $UB_INSTALLDIR/usr/include/cmake/* $UB_INSTALLDIR/usr/lib/cmake/
mv $UB_INSTALLDIR/usr/include/pkgconfig/* $UB_INSTALLDIR/usr/lib/pkgconfig/
rm -Rf $UB_INSTALLDIR/usr/include/{cmake,pkgconfig}
