#!/bin/sh -eux

ub_compile \
      --disable-compile-warnings \
      --disable-vala \
      --disable-plugin-devhelp \
      --enable-introspection \
      --enable-plugin-glade \
      --enable-plugin-subversion \
      --enable-glade-catalog
