#!/bin/sh -eux

export QTDIR="/usr/lib/qt5"
export CXXFLAGS='-DIPE_NO_SPELLCHECK'

# ocsmány windows sorvégek vannak a lua szkriptekben
for f in `find -iname \*.lua`; do
    echo $f
    tr -d '\15\32' < $f > $f.tr
    mv $f.tr $f
done

cd src
ub_make IPEPREFIX=/usr LUA_PACKAGE=lua5.3

cd ../figtoipe
make

cd ../ipe5toxml
make

cd ../pdftoipe
make
