#!/bin/sh -eux

rm -f CMakeLists.txt
export CXXFLAGS="-fpermissive"
ub_compile \
	--enable-qt5 \
	--without-included-boost \
	--with-qt-dir=/usr/lib/qt5 \
	--with-qt-includes=/usr/lib/qt5/include \
	--with-qt-libraries=/usr/lib/qt5/lib
