#!/bin/bash -eux

ARCH="x86_64"
export KBUILD_BUILD_TIMESTAMP="$(LC_ALL=C LANG=C date)"

NUMCPUS="$(grep ^processor /proc/cpuinfo|wc -l)"

rm -f localversion*
echo "-$UB_RELEASE" > localversion.10-release
echo ".$ARCH" > localversion.20-arch

cp "$UB_SRCDIR"/config/config."$ARCH" .config
cp "$UB_SRCDIR"/config/config."$ARCH" arch/x86/configs/"$ARCH"_defconfig

make olddefconfig
make -s kernelrelease > version
VERSION=$(<version)

make ARCH="$ARCH" -j"$NUMCPUS" all

bzimage="kernel"

# /boot
mkdir -p "$UB_OBJECTDIR/boot"
cp -a System.map            "$UB_OBJECTDIR/boot/System.map-$VERSION"
cp -a arch/x86/boot/bzImage "$UB_OBJECTDIR/boot/$bzimage-$VERSION"

ln -s "$bzimage-$VERSION" "$UB_OBJECTDIR/boot/$bzimage.$ARCH"

# modules
make \
	INSTALL_PATH="$UB_OBJECTDIR/boot" \
	INSTALL_MOD_PATH="$UB_OBJECTDIR/usr" \
	DEPMOD=/doesnt/exists \
	modules_install

depmod -a -b "$UB_OBJECTDIR" "$VERSION"

if [ -d "$UB_OBJECTDIR"/lib ]; then
    mv -f "$UB_OBJECTDIR"/lib/modules/"$VERSION"/* "$UB_OBJECTDIR"/usr/lib/modules/"$VERSION"/
    rm -Rf "$UB_OBJECTDIR"/lib
fi

cp version "$UB_OBJECTDIR"/usr/lib/modules/version

# check module symbols
if depmod -nea -b "$UB_OBJECTDIR" -F "$UB_OBJECTDIR"/boot/System.map "$VERSION" 2>&1 | grep "^WARNING:"; then
	echo "fix WARNINGs above!"
	exit 1
fi

# install headers
make \
	INSTALL_HDR_PATH="$UB_OBJECTDIR"/usr/ \
	headers_install

find $UB_OBJECTDIR/usr/include \
     \( -name .install -o -name .check -o \
     	-name ..install.cmd -o -name ..check.cmd \) | xargs rm -f

# And save the headers/makefiles etc for building modules against

mkdir -p "$UB_OBJECTDIR/usr/src/linux-$VERSION"
rm -f "$UB_OBJECTDIR/usr/src/linux"
ln -sf "linux-$VERSION" "$UB_OBJECTDIR/usr/src/linux"

cp -av --parents .config Makefile Module.symvers arch/x86/Makefile arch/x86/Makefile_32.cpu scripts "$UB_OBJECTDIR"/usr/src/linux/
cp --parents `find  -type f -name "Makefile*" -o -name "Kconfig*"` "$UB_OBJECTDIR"/usr/src/linux/
cp -av include "$UB_OBJECTDIR"/usr/src/linux/
cp -av arch/x86/include/asm/. "$UB_OBJECTDIR"/usr/src/linux/include/asm/
cp -a --parents arch/x86/include "$UB_OBJECTDIR"/usr/src/linux/

if [ -s Module.markers ]; then
  cp Module.markers $UB_OBJECTDIR/usr/lib/modules/$VERSION/build
fi
if [ -d arch/$ARCH/scripts ]; then
	cp -a arch/$ARCH/scripts $UB_OBJECTDIR/usr/lib/modules/$VERSION/build/arch/$ARCH/ || :
fi
if [ -f arch/$ARCH/*lds ]; then
	cp -a arch/$ARCH/*lds $UB_OBJECTDIR/usr/lib/modules/$VERSION/build/arch/$ARCH/ || :
fi

if [ -d $UB_OBJECTDIR/usr/lib/modules/$VERSION/build ]; then
    rm -f $UB_OBJECTDIR/usr/lib/modules/$VERSION/build
fi
ln -sf /usr/src/linux-$VERSION $UB_OBJECTDIR/usr/lib/modules/$VERSION/build
if [ -d $UB_OBJECTDIR/usr/lib/modules/$VERSION/source ]; then
    rm $UB_OBJECTDIR/usr/lib/modules/$VERSION/source
fi
ln -sf /usr/src/linux-$VERSION $UB_OBJECTDIR//usr/lib/modules/$VERSION/source

# add objtool for external module building and enabled VALIDATION_STACK option
cp $UB_COMPILEDIR/tools/objtool/objtool $UB_OBJECTDIR/usr/src/linux-$VERSION/tools/objtool/

# remove unneeded architectures
for _archs in $UB_OBJECTDIR/usr/src/linux-$VERSION/arch/*/; do
    [[ ${_archs} == */x86/ ]] && continue
    rm -r "${_archs}"
done
for _dtcs in arc arm arm64 c6x cris h8300 metag microblaze mips nios2 openrisc powerpc sh xtensa; do
    rm -f $UB_OBJECTDIR/usr/src/linux-$VERSION/scripts/dtc/include-prefixes/"$_dtcs"
done
# remove link to /usr/src/linux-$VERSION/arch/riscv/boot/dts
rm -f $UB_OBJECTDIR/usr/src/linux-$VERSION/scripts/dtc/include-prefixes/riscv

rm -rf $UB_OBJECTDIR/usr/src/linux-$VERSION/Documentation
find "$UB_OBJECTDIR/usr/src/linux-$VERSION/" -name "*.o" -print0 | xargs -r0 rm -v
find "$UB_OBJECTDIR/usr/src/linux-$VERSION/" -name "*.cmd" -print0 | xargs -r0 rm -v

# remove mISDN headers
rm -f "$UB_OBJECTDIR"/usr/src/linux/include/linux/mISDN*

# System.map
cp -a System.map "$UB_OBJECTDIR/usr/lib/modules/$VERSION/"

# bzImage symlink
ln -s "$bzimage.$ARCH" "$UB_OBJECTDIR/boot/$bzimage"

# cpupower
cd tools/power/cpupower
ub_make VERSION=${UB_VERSION}
