#!/bin/bash -eux

case "$UB_VERSION" in
	*.*.*)
		VERSION_BASE="${UB_VERSION/\~/-}-${UB_RELEASE}"
		;;
	*.*~*)
		VERSION_BASE="${UB_VERSION/\~/.0-}-${UB_RELEASE}"
		;;
	*.*)
		VERSION_BASE="${UB_VERSION}.0-${UB_RELEASE}"
		;;
	*)
		exit 1
		;;
esac

VERSION="$VERSION_BASE"

export KBUILD_BUILD_TIMESTAMP="$(LC_ALL=C LANG=C date)"

# mkinitrd

if [ "$UB_ARCH" != "amd64" ];then

cat >"$UB_INSTALLDIR"/usr/sbin/mkinitrd-installedkernel <<END
#!/bin/sh

mkinitrd $VERSION.i386
mkinitrd $VERSION.x86_64

rm -f /boot/initrd.i386.gz
ln -s initrd-$VERSION.i386.gz /boot/initrd.i386.gz

rm -f /boot/initrd.x86_64.gz
ln -s initrd-$VERSION.x86_64.gz /boot/initrd.x86_64.gz

rm -f /boot/initrd.gz
ln -s initrd.i386.gz /boot/initrd.gz

# update grub config
if [ -f /boot/grub/grub.cfg ]; then
	mv /boot/grub/grub.cfg /boot/grub/grub.cfg.`date '+%F'`
fi
exec grub-mkconfig -o /boot/grub/grub.cfg

END

else

cat >"$UB_INSTALLDIR"/usr/sbin/mkinitrd-installedkernel <<END
#!/bin/sh

mkinitrd $VERSION.x86_64

rm -f /boot/initrd.x86_64.gz
ln -s initrd-$VERSION.x86_64.gz /boot/initrd.x86_64.gz

rm -f /boot/initrd.gz
ln -s initrd.x86_64.gz /boot/initrd.gz

# update grub config
if [ -f /boot/grub/grub.cfg ]; then
	mv /boot/grub/grub.cfg /boot/grub/grub.cfg.`date '+%F'`
fi
exec grub-mkconfig -o /boot/grub/grub.cfg

END

fi

chmod 755 "$UB_INSTALLDIR"/usr/sbin/mkinitrd-installedkernel

cp -al "$UB_OBJECTDIR"/. "$UB_INSTALLDIR"/

chmod -R a+rX,u+w,go-w "$UB_INSTALLDIR"

# cpupower
cd tools/power/cpupower
ub_make VERSION=${UB_VERSION}
ub_install mandir=/usr/share/man

# install startup scripts
install -Dm 644 cpupower.default "$UB_INSTALLDIR/etc/default/cpupower"
install -Dm 644 cpupower.service "$UB_INSTALLDIR/usr/lib/systemd/system/cpupower.service"
install -Dm 755 cpupower.systemd "$UB_INSTALLDIR/usr/lib/systemd/scripts/cpupower"

install -Dm 644 lib/cpupower.h "$UB_INSTALLDIR/usr/include/"
rm -rf ${UB_INSTALLDIR}/usr/share/doc/packages
