#!/bin/sh -e

if [ ! -f /var/lib/uhu-pkg/gdk-pixbuf-loaders ]; then
	exit 0
fi

if grep -q '^/usr/lib/gdk-pixbuf-2\.0/2\.10\.0/loaders/' /var/lib/dpkg/info/"$1".list; then
	rm -f /var/lib/uhu-pkg/gdk-pixbuf-loaders
fi
