#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR"/usr/share/truecrypt/doc

cp Main/truecrypt "$UB_INSTALLDIR"/usr/bin/
cp Resources/Icons/TrueCrypt-48x48.xpm "$UB_INSTALLDIR"/usr/share/pixmaps/truecrypt.xpm
cp Release/Setup\ Files/TrueCrypt\ User\ Guide.pdf "$UB_INSTALLDIR"/usr/share/truecrypt/doc/
