#!/bin/sh -eux

export DESTDIR="$UB_INSTALLDIR"
jam  -sBUILD_ICON_THEMES=1 install
cp -a ede-about/icons/ede.xpm "$UB_INSTALLDIR"/usr/share/pixmaps/
mv "$UB_INSTALLDIR"/usr/bin/ede-conf "$UB_INSTALLDIR"/usr/bin/ede-config
