#!/bin/sh -eux

# autoreconf -vif
export CPPFLAGS+=" -DBOOST_ERROR_CODE_HEADER_ONLY"
export WX_CONFIG_PATH=/usr/bin/wx-config2
export CPPFLAGS+=" -fno-delete-null-pointer-checks"
export CXXFLAGS+=' -std=c++11 -fpermissive'
ub_compile \
	--with-contrib-plugins=all \
	--with-boost-libdir=/usr/lib
