#!/bin/sh -eux

cd sphinx
python setup.py install --root="$UB_INSTALLDIR"
cd ../sphinx3
python3 setup.py install --root="$UB_INSTALLDIR"
cp AUTHORS CHANGES LICENSE README.rst ../
mkdir -p ${UB_INSTALLDIR}/usr/share/doc/Packages/python3-sphinx
cp AUTHORS CHANGES LICENSE README.rst ${UB_INSTALLDIR}/usr/share/doc/Packages/python3-sphinx/
