#!/bin/sh -eux

runghc Setup.hs configure \
    --prefix=/usr \
    --datasubdir=alex \
    --enable-executable-dynamic \
    --disable-library-vanilla \
    --ghc-option=-optl-Wl\,-z\,relro\,-z\,now  \
    --ghc-option='-pie'

 runghc Setup.hs build
