#!/bin/sh -eux

ub_install

mv ${UB_INSTALLDIR}/usr/local/bin/sbiload ${UB_INSTALLDIR}/usr/bin/sbiload

rm -rf ${UB_INSTALLDIR}/etc/hotplug
rm -rf ${UB_INSTALLDIR}/usr/include
rm -rf ${UB_INSTALLDIR}/usr/local
rm -rf ${UB_INSTALLDIR}/usr/share/aclocal
