#!/bin/sh -eux

cd pyicu
python setup.py install --root=${UB_INSTALLDIR}
cd ../py3icu
python3 setup.py install --root=${UB_INSTALLDIR}
mkdir -p ${UB_INSTALLDIR}/usr/share/doc/Packages/py3icu
cp CHANGES CREDITS LICENSE README.md ${UB_INSTALLDIR}/usr/share//doc/Packages/py3icu/
