#!/bin/sh -eux

cd wpa_supplicant
ub_install
mkdir -p "$UB_INSTALLDIR"/etc/dbus-1/system.d
cp dbus/dbus-wpa_supplicant.conf "$UB_INSTALLDIR"/etc/dbus-1/system.d/wpa-supplicant.conf
mkdir -p "$UB_INSTALLDIR/usr/lib/systemd/system"
cp systemd/*.service "$UB_INSTALLDIR/usr/lib/systemd/system/"
