#!/bin/sh -eux

ub_install
rm -rf "$UB_INSTALLDIR"/usr/share/info
sed -i '1s/guile/guile2.2/' -i "$UB_INSTALLDIR"/usr/bin/guile-config2.2
mv "$UB_INSTALLDIR"/usr/share/aclocal/guile.m4 "$UB_INSTALLDIR"/usr/share/aclocal/guile22.m4
rm -f "$UB_INSTALLDIR"/usr/lib/libguile-2.?.so.*-gdb.scm
