#!/bin/sh -eux

# use system libs
rm -rf apr
rm -rf apr-util
rm -rf neon

export PYTHON=/usr/bin/python2
autoreconf -vif
ub_compile \
	--with-apache-libexecdir=/usr/lib/apache \
	--with-utf8proc=internal

ub_make swig-pl
ub_make swig-py
