#!/bin/sh -eux

export SETUPTOOLS_SCM_PRETEND_VERSION=${UB_VERSION}
cd py3
python3 setup.py install --root="$UB_INSTALLDIR"

cd ../py2
python2 setup.py install --root="$UB_INSTALLDIR"

py3docdir="$UB_INSTALLDIR"/usr/share/doc/Packages/python3-setuptools-scm
mkdir -p $py3docdir
cp CHANGELOG.rst LICENSE README.rst $py3docdir/
