#!/bin/sh -eux

ub_replace -O3 -O2 configure
ub_compile \
	--with-terminfo=/usr/share/terminfo \
	--with-term=rxvt-256color \
	--enable-everything \
	--enable-smart-resize \
	--enable-xim \
	--disable-iso14755
