#!/bin/sh -e

if [ ! -f /var/lib/uhu-pkg/glib-compile-schemas ]; then
	exit 0
fi

if grep -q '^/usr/share/glib-2.0/shemas/' /var/lib/dpkg/info/"$1".list; then
	rm -f /var/lib/uhu-pkg/glib-compile-schemas
fi
