#!/bin/sh -eux

export PYTHON=python2
python2 ./waf configure \
	--prefix=/usr \
	--with-optionals=python,launcher,xmmsclient++,xmmsclient++-glib,perl,nycli \
	--with-default-output-plugin=pulse

python2 ./waf build
