#!/bin/sh -eux

cp -a py2 py3
cd py2
ub_configure \
	--enable-static \
	--with-python=/usr/bin/python2
ub_make \
	HTML_DIR=/usr/share/doc
cd ../py3
ub_configure \
	--enable-static \
	--with-python=/usr/bin/python3
ub_make \
	HTML_DIR=/usr/share/doc
