#!/bin/sh -xeu

git clone https://github.com/itay-grudev/SingleApplication src/third-party/singleapplication
git clone https://github.com/HatScripts/circle-flags.git data/icons/third-party/circle-flags
git clone https://github.com/masalla-art/masalla-icon-theme data/icons/third-party/masalla-icon-theme

ub_compile
