#!/bin/sh -eux

if [ -z "$(ls -A subprojects/gvc)" ]; then
git clone https://gitlab.gnome.org/GNOME/libgnome-volume-control.git subprojects/gvc
fi

ub_compile \
    -Dprivileged_group=root \
    -Dwayland=true
