#!/bin/sh -eux

ub_compile \
	--enable-facebook \
	--enable-twitter \
	--enable-yahoo \
	--enable-windows-live \
	--enable-exchange \
	--enable-kerberos \
	--enable-media-server \
	--enable-lastfm \
	--enable-foursquare \
	--enable-telepathy \
	--enable-vala
