#!/bin/sh -eux

cp -R fuse fuse-gtk
cd fuse
ub_compile \
	PACKAGE_NAME=free-unix-spectrum-emulator \
	--with-sdl
	mv fuse fuse-sdl
cd ../fuse-gtk
ub_compile \
	PACKAGE_NAME=free-unix-spectrum-emulator \
	--with-gtk \
	--enable-gtk3
