#!/bin/sh -eux

autoreconf -vif
./configure \
	--prefix=/usr \
	--enable-gnomeui3 \
	--enable-ethernet \
	--enable-fullscreen \
	--enable-external-ffmpeg \
	--enable-lame \
	--enable-vte \
	--disable-static-lame \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--mandir=/usr/share/man \
	--infodir=/usr/share/info \
	--build=i686-uhu-linux \
	--host=i686-uhu-linux
ub_make
