#!/bin/sh -eux

autoreconf -vif
./configure \
	--prefix=/usr \
	--enable-ethernet \
	--enable-external-ffmpeg \
	--enable-lame \
	--disable-static-lame \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--mandir=/usr/share/man \
	--infodir=/usr/share/info \
	--libdir=/usr/lib
ub_make
