#!/bin/sh -eux

ub_install

# this file is not a png but an adobe image, lets just overwrite it with the english version
cp "$UB_INSTALLDIR"/usr/share/gnome/help/ekiga/{C,sv}/figures/audio_codecs.png
