#!/bin/sh -eux

# sed -ri 's/^=item ([0-9]+)/=item C<\1>/' doc/{apps,crypto,ssl}/*.pod

# A -O3 veszélyes
ub_replace -O3 -O2 Configure

./Configure \
	--prefix=/usr \
	--libdir=lib \
	--openssldir=/etc/ssl \
	linux-x86_64 \
	shared enable-ktls \
	enable-ec_nistp_64_gcc_128 \
	shared \
	zlib-dynamic \
	-Wa,--noexecstack

ub_make depend
ub_make
