#!/bin/sh -eux

python2 setup.py install \
	--root="$UB_INSTALLDIR"
python3 setup.py install \
	--root="$UB_INSTALLDIR"
mkdir -p ${UB_INSTALLDIR}/usr/share/doc/Packages/py3cairo
cp COPYING* NEWS README* ${UB_INSTALLDIR}/usr/share/doc/Packages/py3cairo/
