#!/bin/sh -eux

mkdir -p ${UB_INSTALLDIR}/usr/share/stuntrally
mv lib/64/* lib/
cp -r share ${UB_INSTALLDIR}/usr/
rm -rf lib/64/ lib/32 share
rm lib/libstdc++.so.6 lib/libSDL2-2.0.so.1 bin/*_x86
cp /usr/lib/libSDL2-2.0.so.0 lib/libSDL2-2.0.so.1
patchelf --set-interpreter /usr/lib/ld-linux-x86-64.so.2 bin/stuntrally_x86_64
patchelf --set-interpreter /usr/lib/ld-linux-x86-64.so.2 bin/sr-editor_x86_64
cp -r * ${UB_INSTALLDIR}/usr/share/stuntrally/
ln -s ${UB_INSTALLDIR}/usr/share/stuntrally/stuntrally ${UB_INSTALLDIR}/usr/bin/stuntrally
ln -s ${UB_INSTALLDIR}/usr/share/stuntrally/sr-editor ${UB_INSTALLDIR}/usr/bin/sr-editor
