#!/bin/sh -eux

cp -a doublecmd ${UB_INSTALLDIR}/usr/lib/
mkdir -p ${UB_INSTALLDIR}/usr/share/pixmaps
ln -s /usr/lib/doublecmd/doublecmd ${UB_INSTALLDIR}/usr/bin
cp doublecmd/doublecmd.png ${UB_INSTALLDIR}/usr/share/pixmaps/
rm -rf ${UB_INSTALLDIR}/usr/lib/doublecmd/doc
