#!/bin/sh -eux

pythonver=$(python -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')

sip-build \
    --confirm-license \
	--verbose \
	--no-designer-plugin \
	--target-dir /usr/lib/python$pythonver/site-packages \
	--pep484-pyi \
	--no-make

cd build
ub_make
