#!/bin/sh -eux

cd build
ub_install INSTALL_ROOT="$UB_INSTALLDIR"

mv "$UB_INSTALLDIR"/bin/* "$UB_INSTALLDIR"/usr/bin/
rm -Rf "$UB_INSTALLDIR"/bin
rm -r "$UB_INSTALLDIR"/usr/lib/python*/site-packages/PyQt5/uic/port_v2
