#!/bin/sh -eux

python setup.py install --root="$UB_INSTALLDIR"

2to3 -w --no-diffs pygments

python3 setup.py install --root="$UB_INSTALLDIR"

py3docdir=${UB_INSTALLDIR}/usr/share/doc/Packages/python3-pygments
mkdir -p $py3docdir
cp AUTHORS CHANGES LICENSE $py3docdir/
