#!/bin/sh -e

if [ ! -f /var/lib/uhu-pkg/gtk-icon-cache ]; then
	exit 0
fi

for i in /usr/share/icons/*; do
	if [ -f "$i/icon-theme.cache" ]; then
		rm -f "$i/icon-theme.cache"
		rmdir --ignore-fail-on-non-empty "$i"
	fi
done
	
if grep -q '^/usr/share/icons/' /var/lib/dpkg/info/"$1".list; then
	rm -f /var/lib/uhu-pkg/gtk-icon-cache
fi
