#!/bin/sh -eux

rm resources/translations/po/*.po
dellinguas="
af
ar
bg
br
ca
cy
da_DK
de_1901
de_CH
el
en_AU
en_GB
en_US
eo
es_ES
et
eu
fi
gl
id
ja
ko
lt_LT
nb_NO
nl
pt_BR
pt
ru
sa
sq
sr
th_TH
tr
zh_CN
zh_TW"
for delts in $dellinguas;do
rm resources/translations/po/scribus.$delts.ts
done

ub_compile
