#!/bin/sh -eux

ub_install

# rm "$UB_INSTALLDIR"/usr/share/scribus/dicts/hyph_hu.dic
# ln -s /usr/share/hyphen/hyph_hu_HU.dic "$UB_INSTALLDIR"/usr/share/scribus/dicts/hyph_hu.dic

mkdir -p "$UB_INSTALLDIR"/usr/share/{applications,pixmaps}
cp scribus.desktop "$UB_INSTALLDIR"/usr/share/applications/
cp resources/icons/scribus.png "$UB_INSTALLDIR"/usr/share/pixmaps/
