#!/bin/sh -eux

ub_compile \
	-Dintel=enabled \
	-Dradeon=enabled \
	-Damdgpu=enabled \
	-Dnouveau=enabled \
    -Detnaviv=disabled \
    -Dfreedreno=disabled \
    -Dvc4=disabled \
    -Dvalgrind=disabled \
    -Dinstall-test-programs=true \
	-Dudev=false
