#!/bin/sh -eux

cd pyicu
python2 setup.py install --root=${UB_INSTALLDIR}
cd ../py3icu
python3 setup.py install --root=${UB_INSTALLDIR}
mkdir -p ${UB_INSTALLDIR}/usr/share/doc/Packages/python3-pyicu
cp CHANGES CREDITS LICENSE README.md ${UB_INSTALLDIR}/usr/share//doc/Packages/python3-pyicu/
