#!/bin/sh -eux

autoreconf -vif
export LIBPOSTFIX=/
export LUA=lua5.1
export PYTHON=python2
export PERL=perl5
./configure \
    --prefix=/usr \
	--enable-ocaml=no \
	--with-tclsh=/usr/bin/tclsh \
	--enable-tcl=yes \
	--enable-perl=yes
ub_make
