#!/bin/sh -eux

ub_install

mkdir -p "$UB_INSTALLDIR"/usr/lib/lua/5.1
ln -s "$UB_INSTALLDIR"/usr/lib/graphviz/lua/libgv_lua.so "$UB_INSTALLDIR"/usr/lib/lua/5.1/gv.so
rm -rf "$UB_INSTALLDIR"/usr/share/graphviz/doc
