#!/bin/sh -eux

export PKG_CONFIG_PATH='/usr/lib/ffmpeg4.4/pkgconfig'
mkdir -p build
cd build
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="/usr" \
	-DNOSERVER=1 \
	-DMINIMAL_FLAGS=1 \
	-DNOVIDEOREC=0 \
	-DGHFLAGS=-dynamic \
	-DFONTS_DIRS="/usr/share/fonts/truetype" \
	-DBUILD_ENGINE_C=on \
	..

ub_make
