#!/bin/sh -eux

ub_install LIBRARY_REL=lib

# install pkg-config file
sed -i -e "s/@UPSTREAM_VER@/${UB_VERSION}/" libargon2.pc
sed -i -e "s/\/@HOST_MULTIARCH@//" libargon2.pc
install -D -m0644 libargon2.pc ${UB_INSTALLDIR}/usr/lib/pkgconfig/libargon2.pc
