#!/bin/sh -eux

chmod +x waf-2.0.9

./waf-2.0.9 configure \
	--prefix=/usr \
	--confdir=/etc/mpv \
	--enable-cdda \
	--enable-dvb \
	--enable-dvdnav \
	--enable-libarchive \
	--enable-libmpv-shared \
	--enable-libsmbclient \

./waf-2.0.9 build
