#!/bin/bash -e

export PATH=/bin:/usr/bin

for _envfeed in /etc/envfeed.d/*.sh; do
	if [ -f "$_envfeed" -a -r "$_envfeed" ]; then
		. "$_envfeed"
	fi
done

for _envfeed in ${!ENVFEED_*}; do
	echo -n "${_envfeed#ENVFEED_}=${!_envfeed}"
	echo -ne '\000'
done
