#!/bin/sh -eux

ub_install
ln -sf /usr/share/zenmap/pixmaps/zenmap.png "$UB_INSTALLDIR"/usr/share/pixmaps/
ln -s ncat "$UB_INSTALLDIR"/usr/bin/nc
rm -rf "$UB_INSTALLDIR"/usr/bin/uninstall_zenmap
rm -rf "$UB_INSTALLDIR"/usr/share/applications/zenmap{,-root}.desktop
rm -rf "$UB_INSTALLDIR"/usr/share/zenmap/su-to-zenmap.sh
