#!/bin/sh -eux

python3 setup.py install --root="$UB_INSTALLDIR"

mv "$UB_INSTALLDIR"/usr/bin/dip-automate "$UB_INSTALLDIR"/usr/bin/dip-automate3
mv "$UB_INSTALLDIR"/usr/bin/dip-builder "$UB_INSTALLDIR"/usr/bin/dip-builder3
