#!/bin/sh -eux

install -Dm755 gmakeself "$UB_INSTALLDIR"/usr/bin/gmakeself
install -Dm644 gmakeself.desktop "$UB_INSTALLDIR"/usr/share/applications/gmakeself.desktop
install -Dm644 gmakeself.png "$UB_INSTALLDIR"/usr/share/pixmaps/gmakeself.png
