#!/bin/sh -eux

# Do not run fixincludes
sed -i 's@\./fixinc\.sh@-c true@' gcc/Makefile.in

cd "$UB_OBJECTDIR"

arch="x86_64-linux-gnu"

OPT_FLAGS="-march=k8 -m64 -O2 -mtune=generic"

export CFLAGS="$OPT_FLAGS"
export CXXFLAGS="$OPT_FLAGS"
SED=sed \

"$UB_COMPILEDIR"/configure \
    --build=$arch \
    --host=$arch \
    --target=$arch \
	--prefix=/usr \
	--infodir=/usr/share/info \
	--mandir=/usr/share/man \
	--enable-languages=c,c++,objc,fortran \
	--enable-targets=all \
	--enable-checking=release \
	--enable-shared \
	--enable-threads=posix \
	--enable-lto \
	--enable-plugin \
	--enable-libmpx \
	--enable-libssp \
	--enable-tls \
	--enable-install-libiberty \
	--disable-multilib \
	--disable-libstdcxx-pch \
	--disable-libunwind-exceptions \
	--disable-werror \
	--with-gnu-as \
	--with-gnu-ld \
	--with-system-zlib \
	--with-arch-32=i686 \
	--with-arch-64=k8 \
	--with-cpu-32=i686 \
	--with-cpu-64=k8 \
	--with-tune=generic

ub_make -j4
