#!/bin/sh -eux

arch="x86_64-unknown-linux-gnu"

cd "$UB_OBJECTDIR"

make \
	prefix="$UB_INSTALLDIR"/usr \
	infodir="$UB_INSTALLDIR"/usr/share/info \
	mandir="$UB_INSTALLDIR"/usr/share/man \
	install

# delete .py file for gdb from /usr/lib
rm -f "$UB_INSTALLDIR"/usr/lib/libstdc++*.py

# Use symbolic links instead of hard ones.
ln -sf "$arch"-gcc-"$UB_VERSION" "$UB_INSTALLDIR"/usr/bin/cc
ln -sf "$arch"-gcc-"$UB_VERSION" "$UB_INSTALLDIR"/usr/bin/gcc
ln -sf "$arch"-gcc-"$UB_VERSION" "$UB_INSTALLDIR"/usr/bin/"$arch"-gcc
ln -sf "$arch"-g++ "$UB_INSTALLDIR"/usr/bin/g++
ln -sf "$arch"-g++ "$UB_INSTALLDIR"/usr/bin/c++
ln -sf "$arch"-g++ "$UB_INSTALLDIR"/usr/bin/"$arch"-c++
ln -sf "$arch"-gcc-ar "$UB_INSTALLDIR"/usr/bin/gcc-ar
ln -sf "$arch"-gcc-nm "$UB_INSTALLDIR"/usr/bin/gcc-nm
ln -sf "$arch"-gcc-ranlib "$UB_INSTALLDIR"/usr/bin/gcc-ranlib
ln -sf "$arch"-gfortran "$UB_INSTALLDIR"/usr/bin/gfortran

ln -s ../../usr/bin/cpp "$UB_INSTALLDIR"/usr/lib/cpp
