#!/bin/sh -eux

autoreconf -vif
export PYTHON=/usr/bin/python2
ub_compile \
	--enable-python \
	--enable-python-plugin \
	--disable-eds-backend \
	--disable-eds \
	--disable-update-mimedb \
	--disable-schemas-install
