#!/bin/sh -eux

ub_install

mkdir -p ${UB_INSTALLDIR}/usr/share/doc/Packages/planner
mv ${UB_INSTALLDIR}/usr/share/doc/planner/* ${UB_INSTALLDIR}/usr/share/doc/Packages/planner/
rm -rf ${UB_INSTALLDIR}/usr/share/doc/planner
rm -rf ${UB_INSTALLDIR}/libplanner
