#!/bin/sh -eux

mv fftw-"$UB_VERSION" single
# nem jó nekem még a cmake
rm -f single/CMakeLists.txt
cp -a single double
cp -a single long
export CFLAGS+=" -O2 -fomit-frame-pointer -malign-double -fstrict-aliasing -ffast-math"

cd double
ub_compile \
	--enable-threads \
	--enable-openmp \
	--enable-avx
cd ../single
ub_compile \
	--enable-threads \
	--enable-openmp \
	--enable-avx \
	--enable-float
cd ../long
ub_compile \
	--enable-threads \
	--enable-openmp \
	--enable-long-double
