#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR"/usr/share/fonts/truetype
for dir in Roboto RobotoCondensed; do
	pushd "$dir"
	cp -a *.ttf "$UB_INSTALLDIR"/usr/share/fonts/truetype/
	popd
done
mkfontscale "$UB_INSTALLDIR"/usr/share/fonts/truetype
sed 1d \
  <"$UB_INSTALLDIR"/usr/share/fonts/truetype/fonts.scale \
  >"$UB_INSTALLDIR"/usr/share/fonts/truetype/fonts.scale.roboto
rm "$UB_INSTALLDIR"/usr/share/fonts/truetype/fonts.scale
cp -a "$UB_INSTALLDIR"/usr/share/fonts/truetype/fonts.{scale,dir}.roboto
