#!/bin/sh -eux

chmod +x et${UB_VERSION/./}b.x86_keygen_V03.run
./et260b.x86_keygen_V03.run --noexec --nox11 --target enemy-territory

mkdir -p $UB_INSTALLDIR/usr/share/enemy-territory/etmain
cp enemy-territory/etmain/{pak0,pak1,pak2}.pk3 $UB_INSTALLDIR/usr/share/enemy-territory/etmain/
cp -r enemy-territory/Docs ./
