#!/bin/sh -eux

cd py2
python setup.py --berkeley-db=/usr install --root=${UB_INSTALLDIR} --skip-build
cd ../py3
python3 setup.py --berkeley-db=/usr install --root=${UB_INSTALLDIR} --skip-build
mkdir -p ${UB_INSTALLDIR}/usr/share/doc/Packages/python3-bsddb3
cp ChangeLog TODO.txt LICENSE.txt README.txt ${UB_INSTALLDIR}/usr/share/doc/Packages/python3-bsddb3/
