#!/bin/sh -eux

cd googletest
sed -r "s|(Version:) .+|\1 ${UB_VERSION}|" -i gtest.pc.in
ub_compile \
	-DBUILD_SHARED_LIBS=ON \
	-DCMAKE_SKIP_BUILD_RPATH=TRUE \
	-DPYTHON_EXECUTABLE=/usr/bin/python2 \
	-Dgtest_build_tests=ON \
	-Dgtest_disable_pthreads=OFF

cd ../googlemock
ub_compile \
    -DBUILD_SHARED_LIBS=ON
