#!/bin/sh -eux

ub_compile \
	-DBUILD_SHARED_LIBS=ON \
	-DBUILD_GMOCK=ON \
	-DCMAKE_SKIP_BUILD_RPATH=TRUE \
	-DPYTHON_EXECUTABLE=/usr/bin/python3 \
	-Dgtest_build_tests=ON \
	-Dgtest_disable_pthreads=OFF
