#!/bin/sh -eux

ub_install

cd googletest
install -Dm 644 cmake/* -t "${UB_INSTALLDIR}/usr/src/googletest/cmake"
install -Dm 644 src/* -t "${UB_INSTALLDIR}/usr/src/googletest/src"
install -Dm 644 CMakeLists.txt -t "${UB_INSTALLDIR}/usr/src/googletest"

cd ../googlemock
install -Dm 644 cmake/* -t "${UB_INSTALLDIR}/usr/src/gmock/cmake"
install -Dm 644 src/* -t "${UB_INSTALLDIR}/usr/src/gmock/src"
install -Dm 644 CMakeLists.txt -t "${UB_INSTALLDIR}/usr/src/gmock"

sed -i 's|src/||' "${UB_INSTALLDIR}/usr/src/gmock/src/gmock-all.cc"
