#!/bin/sh -eux

ub_install

rm -Rf "$UB_INSTALLDIR"/usr/share/doc/readline

# Compatibility...
ln -s libhistory.so.8  "$UB_INSTALLDIR"/usr/lib/libhistory.so.7
ln -s libreadline.so.8 "$UB_INSTALLDIR"/usr/lib/libreadline.so.7
