#!/bin/sh -eux

ub_install

# Compatibility...
ln -s libhistory.so.6  "$UB_INSTALLDIR"/lib/libhistory.so.4
ln -s libreadline.so.6 "$UB_INSTALLDIR"/lib/libreadline.so.4
ln -s libhistory.so.6  "$UB_INSTALLDIR"/lib/libhistory.so.5
ln -s libreadline.so.6 "$UB_INSTALLDIR"/lib/libreadline.so.5
ln -s libhistory.so.7  "$UB_INSTALLDIR"/lib/libhistory.so.6
ln -s libreadline.so.7 "$UB_INSTALLDIR"/lib/libreadline.so.6
