#!/bin/sh -eux

export LDFLAGS=" -Wl,-dynamic-linker,/usr/lib/ld-linux-x86-64.so.2 "

ub_configure \
    --with-lib-path=/lib:/usr/lib:/usr/local/lib \
    --enable-cet \
    --enable-default-execstack=no \
    --enable-deterministic-archives \
    --enable-gold \
    --enable-install-libiberty \
    --enable-ld=default \
    --enable-pgo-build=lto \
    --enable-plugins \
    --enable-relro \
    --enable-targets=x86_64-pep,bpf-unknown-none \
    --enable-threads \
    --disable-gdb \
    --disable-gdbserver \
    --disable-jansson \
    --disable-libdecnumber \
    --disable-readline \
    --disable-sim \
    --disable-werror \
    --with-pic \
    --with-system-zlib

make configure-host
make -e \
	tooldir=/usr
