#!/bin/sh -eux

make \
	prefix="$UB_INSTALLDIR"/usr \
	mandir="$UB_INSTALLDIR"/usr/share/man \
	infodir="$UB_INSTALLDIR"/usr/share/info \
	tooldir="$UB_INSTALLDIR"/usr \
	install
make \
	prefix="$UB_INSTALLDIR"/usr \
	mandir="$UB_INSTALLDIR"/usr/share/man \
	infodir="$UB_INSTALLDIR"/usr/share/info \
	tooldir="$UB_INSTALLDIR"/usr \
	install-info

cp -f include/plugin-api.h "$UB_INSTALLDIR"/usr/include/

# No shared linking to these files outside binutils
rm -f "$UB_INSTALLDIR"/usr/lib/lib{bfd,opcodes}.so
echo 'INPUT( /usr/lib/libbfd.a -liberty -lz -ldl )' > "$UB_INSTALLDIR"/usr/lib/libbfd.so
echo 'INPUT( /usr/lib/libopcodes.a -lbfd )' > "$UB_INSTALLDIR"/usr/lib/libopcodes.so

## create a "host" named link like in gcc
ln -sf ar "$UB_INSTALLDIR"/usr/bin/x86_64-gnu-linux-ar
ln -sf as "$UB_INSTALLDIR"/usr/bin/x86_64-gnu-linux-as
