#!/bin/sh -e

query_dconf ()
{
	[ -z "${UHU_PKG_QUIET+x}" ] && echo -n "  Update dconf databases ..."
	dconf update
	true > /var/lib/uhu-pkg/dconf
	while [ ! /var/lib/uhu-pkg/dconf -ot /var/lib/dpkg/info \
	     -a ! /var/lib/uhu-pkg/dconf -nt /var/lib/dpkg/info ]; do
		sleep 0.1
		true > /var/lib/uhu-pkg/dconf
	done
	[ -z "${UHU_PKG_QUIET+x}" ] && echo
}

if [ -f /var/lib/uhu-pkg/dconf -a /var/lib/uhu-pkg/dconf -nt /var/lib/dpkg/info ]; then
	exit 0
fi

if [ "$1" = "dconf" -o "$1" = "+" ]; then
	query_dconf
elif grep -q '^/etc/dconf/db/' /var/lib/dpkg/info/"$1".list; then
	query_dconf
fi
