#!/bin/sh -eux

ub_install
#mv ${UB_INSTALLDIR}/usr/share/doc/icewm/preferences ${UB_INSTALLDIR}/usr/share/icewm/
cp src/genpref ${UB_INSTALLDIR}/usr/bin/
icewmmappa=${UB_INSTALLDIR}/usr/share/icewm
# wallpapers
# Win témák
cp -r data/{SilverXP,xp,xp-new,WinClassic2} $icewmmappa/themes/
# win95
mkdir -p ${UB_INSTALLDIR}/usr/share/themes/win95
cp Original-Windows-951.jpg $icewmmappa/themes/win95/win95.jpg
# xp wallpaper
cp windows-xp-bliss-4k-lu.jpg $icewmmappa/themes/xp/winxp.jpg
cp windows-xp-bliss-4k-lu.jpg $icewmmappa/themes/xp-new/winxp.jpg
cp windows-xp-bliss-4k-lu.jpg $icewmmappa/themes/SilverXP/winxp.jpg

# hiányzó xpm
rm -f $icewmmappa/themes/xp/icons/folder* $icewmmappa/themes/xp-new/icons/folder*
cp -r data/CoolSteel/icons/folder_32x32.xpm $icewmmappa/themes/xp/icons/
cp -r data/CoolSteel/icons/folder_32x32.xpm $icewmmappa/themes/xp-new/icons/
cp -r data/blueHeart/icons/folder_16x16.xpm $icewmmappa/themes/xp/icons/
cp -r data/blueHeart/icons/folder_16x16.xpm $icewmmappa/themes/xp-new/icons/

# win95 taskbarbutton
cp -r data/fake95/taskbar $icewmmappa/themes/win95/

# nem kell html
rm -rf ${UB_INSTALLDIR}/usr/share/doc/icewm

# nem kell FreeBSD
rm -rf $icewmmappa/themes/SilverXP/FreeBSD
