#!/bin/sh -eux

make DESTDIR="${UB_INSTALLDIR}" PREFIX="/usr" install

mkdir -p "${UB_INSTALLDIR}/usr/share/mercurial"
cp -a hgweb.cgi "${UB_INSTALLDIR}/usr/share/mercurial"

cp -a hgeditor "${UB_INSTALLDIR}/usr/bin"
