#!/bin/sh -eux

cd py2
ub_install
cd ../py3
ub_install

# remove dbus-python-dev conflicting files
rm -rf "$UB_INSTALLDIR"/usr/include
rm -rf "$UB_INSTALLDIR"/usr/lib/pkgconfig
rm -rf "$UB_INSTALLDIR"/usr/share/doc/dbus-python
