#!/bin/sh -eux

ub_install

# cd desktopfiles
# mkdir -p "${UB_INSTALLDIR}/usr/share/icons/hicolor/"{22x22,32x32,48x48}"/mimetypes/"
# cp -a "${UB_INSTALLDIR}/usr/share/icons/hicolor/hi22-djvu.png" "${UB_INSTALLDIR}/usr/share/icons/hicolor/22x22/mimetypes/image-vnd.djvu.mime.png"
# cp -a "hi32-djvu.png" "${UB_INSTALLDIR}/usr/share/icons/hicolor/32x32/mimetypes/image-vnd.djvu.mime.png"
# cp -a "hi48-djvu.png" "${UB_INSTALLDIR}/usr/share/icons/hicolor/48x48/mimetypes/image-vnd.djvu.mime.png"

# mkdir -p "${UB_INSTALLDIR}/usr/share/mime/packages/"
# cp -a "djvulibre-mime.xml" "${UB_INSTALLDIR}/usr/share/mime/packages/djvulibre-mime.xml"
# mkdir -p "${UB_INSTALLDIR}/usr/share/mimelnk/image/"
# cp -a "vnd.djvu.desktop" "${UB_INSTALLDIR}/usr/share/mimelnk/image/vnd.djvu.desktop"
