#!/bin/sh -e

if [ ! -f /var/lib/uhu-pkg/desktop-file-utils ]; then
	exit 0
fi

if grep -q '^/usr/share/applications/' /var/lib/dpkg/info/"$1".list; then
	rm -f /var/lib/uhu-pkg/desktop-file-utils
fi
