#!/bin/sh -eux

cd alabaster
python setup.py install --root="$UB_INSTALLDIR"
cd ../alabaster3
python3 setup.py install --root="$UB_INSTALLDIR"

py3docdir=${UB_INSTALLDIR}/usr/share/doc/Packages/python3-sphinx-alabaster-theme
mkdir -p $py3docdir
cp LICENSE README.rst $py3docdir/
