#!/bin/sh -eux

ub_install
mkdir -p "$UB_INSTALLDIR"/usr/share/{applications,pixmaps}
cp ICONS/prboom-plus.desktop "$UB_INSTALLDIR"/usr/share/applications/
cp ICONS/prboom-plus.svg "$UB_INSTALLDIR"/usr/share/pixmaps/
