#!/bin/sh -eux

cd py3
python3 setup.py install --root="$UB_INSTALLDIR"

cd ../py2
python2 setup.py install --root="$UB_INSTALLDIR"

py3docdir="$UB_INSTALLDIR"/usr/share/doc/Packages/python3-setuptools-git
mkdir -p $py3docdir
cp AUTHORS.txt LICENSE.txt README.rst $py3docdir/
