#!/bin/sh -eux

ub_install \
	PREFIX="$UB_INSTALLDIR"/usr \
	BINDIR="$UB_INSTALLDIR"/usr/bin \
	ASLDDIR="$UB_INSTALLDIR"/usr/bin \
	LIBDIR="$UB_INSTALLDIR"/usr/lib/bcc \
	DISTINCL="$UB_INSTALLDIR"/usr/lib/bcc \
	MANDIR="$UB_INSTALLDIR"/usr/share/man \
