#!/bin/sh -eux

python3 setup.py install --root="$UB_INSTALLDIR"

mkdir -p ${UB_INSTALLDIR}/usr/share/{pixmaps,applications}
cp icon.png ${UB_INSTALLDIR}/usr/share/pixmaps/ipython.png

cd "examples/IPython Kernel/"
sed -i 's/gnome-netstatus-idle/ipython/' *.desktop
cp ipython.desktop $UB_INSTALLDIR/usr/share/applications/ipython.desktop
