#!/bin/sh -eux

ub_compile \
    -Dalsa=enabled \
    -Dappmenu=enabled \
    -Dbluez=enabled \
    -Dnm=enabled \
    -Dncenter=enabled \
    -Dnetwork=enabled \
    -Dpulse=enabled \
    -Dxkb=enabled \
