#!/bin/sh -eux

SBCL_HOME="" INSTALL_ROOT=${UB_INSTALLDIR}/usr sh install.sh

mkdir -p ${UB_INSTALLDIR}/usr/share/sbcl-source

src/runtime/sbcl --core output/sbcl.core --script "${UB_SRCDIR}/patches/arch-fixes.skip"
mv sbcl-new.core "${UB_INSTALLDIR}/usr/lib/sbcl/sbcl.core"

cp -R src contrib ${UB_INSTALLDIR}/usr/share/sbcl-source/

find ${UB_INSTALLDIR}/usr/share/sbcl-source -type f \
    \( -name \*.fasl -o -name \*.o -o -name \*.log -o -name \*.so -o -name a.out \) -delete

rm "${UB_INSTALLDIR}/usr/share/sbcl-source/src/runtime/sbcl"
rm -rf ${UB_INSTALLDIR}/usr/share/doc/sbcl
