#!/bin/sh -eux

extlibs="
  --enable-avisynth \
  --enable-ladspa \
  --enable-libbluray \
  --enable-libcaca \
  --enable-libcelt \
  --enable-libcdio \
  --enable-libfdk-aac \
  --enable-libflite \
  --enable-libfontconfig \
  --enable-libfreetype \
  --enable-libfribidi \
  --enable-libgme \
  --enable-libgsm \
  --enable-libiec61883 \
  --enable-libmodplug \
  --enable-libmp3lame \
  --enable-libopencore-amrnb \
  --enable-libopencore-amrwb \
  --enable-libopenjpeg \
  --enable-libopus \
  --enable-libpulse \
  --enable-librsvg \
  --enable-libsmbclient \
  --enable-libspeex \
  --enable-libssh \
  --enable-libsoxr \
  --enable-libtesseract \
  --enable-libtheora \
  --enable-libv4l2 \
  --enable-libvidstab \
  --enable-libvpx \
  --enable-libwavpack \
  --enable-libwebp \
  --enable-libx264 \
  --enable-libx265 \
  --enable-libxml2 \
  --enable-libzvbi \
  --enable-libzmq \
  --enable-openal \
  --enable-opengl \
  --enable-gnutls \
  --enable-libvorbis \
  --enable-libxvid \
  --enable-libass \
  --enable-libdc1394
  "
licensing="
	--enable-gpl \
	--enable-nonfree \
	--enable-version3
"
hwaccels="
	--enable-libdrm
"
components="
    --enable-avfilter \
    --enable-avresample \
    --enable-pthreads \
	--enable-postproc \
	--enable-swresample \
	--enable-swscale
"
doksik="
    --disable-podpages \
    --disable-htmlpages \
    --disable-txtpages
"
./configure \
	--prefix=/usr \
	--incdir=/usr/include/ffmpeg3 \
	--libdir=/usr/lib/ffmpeg3 \
	--mandir=/usr/share/man \
	--disable-programs \
	--enable-shared \
	--disable-static \
	--disable-debug \
	--enable-gray \
	--enable-pic \
    $extlibs \
    $hwaccels \
    $licensing \
    $components \
    $doksik

ub_make
