#!/bin/sh -eux

ub_install

mkdir -p "$UB_INSTALLDIR"/usr/include/libavutil/x86  "$UB_INSTALLDIR"/usr/include/libavformat
cp libavutil/x86/*.h "$UB_INSTALLDIR"/usr/include/libavutil/x86/
cp libavformat/*.h "$UB_INSTALLDIR"/usr/include/libavformat/

cp config.h "$UB_INSTALLDIR"/usr/include/libavformat/

rm -Rf "$UB_INSTALLDIR"/usr/share/ffmpeg
