#!/bin/sh -eux

ub_replace -O3 -O2 Makefile.am
ub_replace -O3 -O2 lib/util.c
ub_replace -O3 -O2 imap/imapparse.c

autoreconf -vif
rm -rf et
rm -rf syslog

UB_MAKE_PROCS=1 \
ub_compile \
	--enable-murder \
	--with-com_err=/usr \
	--with-syslogfacility=MAIL
