#!/bin/sh -eux

# rename "master" to "cyrus-master" to avoid conflict with postfix
for f in man/*.{5,8}; do
	ub_replace "master(8)" "cyrus-master(8)" "$f"
done

ub_install

# rename "master" to "cyrus-master" to avoid conflict with postfix
mv "$UB_INSTALLDIR"/usr/libexec/{,cyrus-}master
mv "$UB_INSTALLDIR"/usr/share/man/man8/{,cyrus-}master.8

ln -s ../libexec/cyrus-master "$UB_INSTALLDIR"/usr/sbin/

cp doc/examples/cyrus_conf/prefork.conf "$UB_INSTALLDIR"/etc/cyrus.conf
