#!/bin/sh -eux

ub_compile	\
    --libexecdir="/usr/lib/lightdm" \
    --disable-libindicator \
    --disable-indicator-services-command \
    --enable-kill-on-sigterm \
    --disable-at-spi-command \
    --disable-libido \
    --with-libxklavier
