#!/bin/sh -eux

python2 setup.py clean
python2 setup.py install --root="${UB_INSTALLDIR}"

python3 setup.py clean
python3 setup.py install --root="${UB_INSTALLDIR}"

mkdir -p ${UB_INSTALLDIR}/usr/share/doc/Packages/libvirt-python3

cp AUTHORS ChangeLog COPYING COPYING.LESSER README ${UB_INSTALLDIR}/usr/share/doc/Packages/libvirt-python3/
