#!/bin/sh -eux

autoreconf -vif

sed 's:-DGIMP_protect_DISABLE_DEPRECATED:-DGIMP_DISABLE_DEPRECATED:g' -i configure #615144
	fgrep -q GIMP_DISABLE_DEPRECATED configure

export XDG_DATA_DIRS=/usr/share

ub_compile \
    --disable-check-update \
	--disable-python \
	--disable-gtk-doc \
	--without-webkit \
	--without-xvfb-run
