#!/bin/sh -eux

ub_compile \
	--enable-application=composer \
	--enable-default-toolkit=gtk2 \
	--enable-system-myspell \
	--enable-jsd \
	--enable-xterm-updates \
	--enable-pango \
	--enable-image-encoder=all \
	--enable-canvas \
	--with-system-nspr \
	--with-system-nss \
	--enable-oji \
	--enable-mathml \
	--enable-storage \
	--enable-places \
	--disable-installer \
	--enable-java \
	--enable-javaxpcom
