#!/bin/sh -eux

ub_install

ub_install -C contrib

# remove and rename conflicting files with wxGTK3
rm "$UB_INSTALLDIR"/usr/share/bakefile/presets/*
mv "$UB_INSTALLDIR"/usr/bin/wx-config{,2}
mv "$UB_INSTALLDIR"/usr/bin/wxrc{,2}
mv "$UB_INSTALLDIR"/usr/share/aclocal/wxwin{,2}.m4
