#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR"/usr/share/ploticus/examples
cp -a src/pl "$UB_INSTALLDIR"/usr/bin/
cp -a src/libploticus.h "$UB_INSTALLDIR"/usr/include/
cp -a src/libploticus.a "$UB_INSTALLDIR"/usr/lib/
cp -a src/libploticus.so "$UB_INSTALLDIR"/usr/lib/libploticus.so.0
ln -s libploticus.so.0 "$UB_INSTALLDIR"/usr/lib/libploticus.so
cp -a man/man1/. "$UB_INSTALLDIR"/usr/share/man/man1/
cp -a man/man3/. "$UB_INSTALLDIR"/usr/share/man/man3/
cp -a prefabs/. "$UB_INSTALLDIR"/usr/share/ploticus/
cp -a pltestsuite/. "$UB_INSTALLDIR"/usr/share/ploticus/examples/
mkdir -p "$UB_INSTALLDIR"/usr/share/ploticus/doc
cp -a doc/. "$UB_INSTALLDIR"/usr/share/ploticus/doc/
cp -a index.html "$UB_INSTALLDIR"/usr/share/ploticus/
