#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR"/usr/share/ploticus/examples
cp -a src/pl "$UB_INSTALLDIR"/usr/bin/
cp -a man/man1/. "$UB_INSTALLDIR"/usr/share/man/man1/
cp -a prefabs/. "$UB_INSTALLDIR"/usr/share/ploticus/
cp -a pltestsuite/. "$UB_INSTALLDIR"/usr/share/ploticus/examples/
mkdir -p "$UB_INSTALLDIR"/usr/share/ploticus/doc
cp -a doc/. "$UB_INSTALLDIR"/usr/share/ploticus/doc/
cp -a index.html "$UB_INSTALLDIR"/usr/share/ploticus/
