#!/bin/sh -eux

builds="build build-py2 build-pyqt5 build-pyqt5-py2"
for builddir in $builds;do
    cd $builddir
        make DESTDIR=${UB_INSTALLDIR} install
    cd ..
done

install -Dm644 siplib/sip.h -t ${UB_INSTALLDIR}/usr/include

doksidir=${UB_INSTALLDIR}/usr/share/doc/Packages
mkdir -p ${doksidir}/python{2,3}-sip

for doksi in `cat ${UB_SRCDIR}/doc`;do
    cp $doksi ${doksidir}/python3-sip/
    cp $doksi ${doksidir}/python2-sip/
done
