#!/bin/sh -eux

builds="build build-pyqt5"
for builddir in $builds;do
    cd $builddir
        make DESTDIR=${UB_INSTALLDIR} install
    cd ..
done

install -Dm644 siplib/sip.h -t ${UB_INSTALLDIR}/usr/include

doksidir=${UB_INSTALLDIR}/usr/share/doc/Packages
mkdir -p ${doksidir}/python3-sip

for doksi in `cat ${UB_SRCDIR}/doc`;do
    cp $doksi ${doksidir}/python3-sip/
done
