#!/bin/sh -eux

procs=$(grep ^processor /proc/cpuinfo | wc -l)
jobs=$(($procs / 2))

export LDFLAGS=" -Wl,--no-keep-memory "
export NINJAFLAGS=" -j$jobs "

ub_compile \
    -G Ninja \
	-DQT_QMAKE_TARGET_MKSPEC=linux-g++ \
	-DCMAKE_INSTALL_PREFIX=/usr \
    -DINSTALL_ARCHDATADIR=lib/qt6 \
    -DINSTALL_BINDIR=lib/qt6/bin \
    -DINSTALL_DATADIR=lib/qt6 \
    -DINSTALL_DOCDIR=share/doc/qt6 \
    -DINSTALL_EXAMPLESDIR=share/doc/qt6/examples \
    -DINSTALL_INCLUDEDIR=include/qt6 \
    -DINSTALL_LIBDIR=lib \
    -DINSTALL_LIBEXECDIR=lib/qt6/libexec \
    -DINSTALL_MKSPECSDIR=lib/qt6/mkspecs \
    -DINSTALL_PUBLICBINDIR=usr/bin \
	-DINSTALL_SYSCONFDIR=/etc/xdg \
	-DINSTALL_TRANSLATIONSDIR=lib/qt6/translations \
	\
	-DCMAKE_BUILD_TYPE=Release \
	-DBUILD_SHARED_LIBS=ON \
	-DBUILD_WITH_PCH=OFF \
	-DQT_USE_CCACHE=ON \
    -DQT_FEATURE_rpath=OFF \
    -DQT_FEATURE_clang=ON \
	-DQT_FEATURE_journald=ON \
	-DQT_FEATURE_qml_debug=ON \
    -DQT_FEATURE_reduce_relocations=ON \
	\
	-DQT_BUILD_EXAMPLES=FALSE \
	-DQT_BUILD_TESTS=FALSE \
	-DBUILD_qtwebengine=ON \
	-DBUILD_qttranslations=ON \
	\
	-DQT_FEATURE_accessibility=ON \
	\
	-DQT_FEATURE_sql_sqlite=ON \
	\
	-DINPUT_freetype=system \
	-DINPUT_harfbuzz=system \
	-DINPUT_libjpeg=system \
	-DINPUT_libpng=system \
	-DINPUT_pcre=system \
	-DQT_FEATURE_system_sqlite=ON \
	-DQT_FEATURE_system_zlib=ON \
	\
	-DINPUT_dbus=linked \
	-DINPUT_openssl=linked \
	-DQT_FEATURE_ssl=ON \
	\
    -DQT_FEATURE_cups=ON \
    -DQT_FEATURE_glib=ON \
    -DQT_FEATURE_gtk3=ON \
    -DQT_FEATURE_opengl=ON \
    -DQT_FEATURE_linuxfb=OFF \
    -DQT_FEATURE_eglfs=ON \
    -DQT_FEATURE_kms=OFF \
    -DQT_FEATURE_libproxy=OFF \
	\
    -DQT_FEATURE_fontconfig=ON \
    -DQT_FEATURE_evdev=ON \
    -DQT_FEATURE_mtdev=ON \
    -DQT_FEATURE_libinput=ON \
    -DQT_FEATURE_tslib=ON
