#!/bin/sh -eux

# cd $UB_OBJECTDIR

ub_install

# Drop QMAKE_PRL_BUILD_DIR because reference the build dir
find "$UB_INSTALLDIR/usr/lib" -type f -name '*.prl' \
	-exec sed -i -e '/^QMAKE_PRL_BUILD_DIR/d' {} \;

# ikonok a desktop fájlokhoz
install -Dm644 $UB_COMPILEDIR/qttools/src/assistant/assistant/images/assistant-128.png \
                  "$UB_INSTALLDIR"/usr/share/pixmaps/assistant-qt6.png
install -Dm644 $UB_COMPILEDIR/qttools/src/designer/src/designer/images/designer.png \
                  "$UB_INSTALLDIR"/usr/share/pixmaps/designer-qt6.png
install -Dm644 $UB_COMPILEDIR/qttools/src/linguist/linguist/images/icons/linguist-128-32.png \
                  "$UB_INSTALLDIR"/usr/share/pixmaps/linguist-qt6.png
install -Dm644 $UB_COMPILEDIR/qttools/src/qdbus/qdbusviewer/images/qdbusviewer-128.png \
                  "$UB_INSTALLDIR"/usr/share/pixmaps/qdbusviewer-qt6.png

while read _s _t; do
    ln -s $_s "$UB_INSTALLDIR"/$_t
done < "$UB_COMPILEDIR"/build/qttools/user_facing_tool_links.txt

rm -Rf "$UB_INSTALLDIR"/usr/lib/objects-Release
rm -Rf "$UB_INSTALLDIR"/usr/lib/cmake/Qt6/{macos,ios}
rm -Rf "$UB_INSTALLDIR"/usr/lib/cmake/Qt6/QtBuildInternals/QtStandaloneTestTemplateProject
