#!/bin/sh -eux

cd py2
python2 setup.py install --root="$UB_INSTALLDIR"
mv ${UB_INSTALLDIR}/usr/bin/markdown_py ${UB_INSTALLDIR}/usr/bin/markdown_py2
cd ../py3
python3 setup.py install --root="$UB_INSTALLDIR"
mkdir -p $UB_INSTALLDIR/usr/share/doc/Packages/python3-markdown
cp LICENSE.md README.md $UB_INSTALLDIR/usr/share/doc/Packages/python3-markdown
