#!/bin/sh -eux

doksik="CHANGES.rst CONTRIBUTORS.txt LICENSE.txt README.rst"
cp -a py2 py3
cd py2
cp $doksik ../
python2 setup.py install --root="$UB_INSTALLDIR"
cd ../py3
python3 setup.py install --root="$UB_INSTALLDIR"
py3docdir=${UB_INSTALLDIR}/usr/share/doc/Packages/python3-urllib
mkdir -p ${py3docdir}
cp $doksik ${py3docdir}/
