#!/bin/sh -eux

./configure \
	--destdir="$UB_INSTALLDIR" \
	--prefix="/usr"             \
	--libdir="/usr/lib"         \
	--sysconfdir="/etc"         \
	--localstatedir="/var"      \
	--mandir="/usr/share/man"   \
	--infodir="/usr/share/info" \
	--disable-rpath \
	--disable-rpath-install \
	--bundled-libraries=NONE \
	--builtin-libraries=replace \
	--with-modulesdir=/usr/lib/ldb/modules \
	--with-privatelibdir=/usr/lib/ldb
make
