#!/bin/sh -eux

# Use hwdb builtin, instead of the obsolete usb-db in the udev rules.
    sed -i 's:^TEST=="/lib/udev/usb-db", IMPORT{program}="usb-db %p":IMPORT{builtin}="hwdb --subsystem=usb":' usb/55-Argyll.rules

export CFLAGS="-DUNIX -D_THREAD_SAFE -m64"

CCOPTFLAG="$CFLAGS"
jam -q -fJambase -sPREFIX=/usr -sDESTDIR="${UB_INSTALLDIR}" -sREFSUBDIR=share/argyllcms/ref all
