#!/bin/sh -eux

jam -q -fJambase -sPREFIX=/usr -sDESTDIR="${UB_INSTALLDIR}" -sREFSUBDIR=share/argyllcms/ref install

rm "${UB_INSTALLDIR}"/usr/bin/License.txt
rm {doc,ref}/afiles

refdir=${UB_INSTALLDIR}/usr/share/argyllcms
rulesdir=${UB_INSTALLDIR}/usr/lib/udev/rules.d
mkdir -p $refdir $rulesdir
cp -r ref $refdir/
cp usb/55-Argyll.rules $rulesdir/
