#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR"/usr/lib/lazarus $UB_INSTALLDIR/usr/share/man/man1 $UB_INSTALLDIR/usr/share/doc

rm -f *.o
rsync -a \
    --exclude="CVS"     --exclude=".cvsignore" \
    --exclude="*.ppw"   --exclude="*.ppl" \
    --exclude="*.ow"    --exclude="*.a"\
    --exclude="*.rst"   --exclude=".#*" \
    --exclude="*.~*"    --exclude="*.bak" \
    --exclude="*.orig"  --exclude="*.rej" \
    --exclude=".xvpics" \
    --exclude="killme*" --exclude=".gdb_hist*" \
    --exclude="debian"  --exclude="COPYING*" \
    --exclude="*.app"   --exclude="tools/install" \
    . "$UB_INSTALLDIR"/usr/lib/lazarus

mv "$UB_INSTALLDIR"/usr/lib/lazarus/README.txt .
install -Dm644 install/lazarus.desktop "$UB_INSTALLDIR"/usr/share/applications/lazarus.desktop
install -Dm644 images/ide_icon48x48.png "$UB_INSTALLDIR"/usr/share/pixmaps/lazarus.png
ln -sf /usr/lib/lazarus/lazarus "$UB_INSTALLDIR"/usr/bin/lazarus
ln -sf /usr/lib/lazarus/startlazarus "$UB_INSTALLDIR"/usr/bin/startlazarus
ln -s /usr/lib/lazarus/lazbuild $UB_INSTALLDIR/usr/bin/lazbuild
cp -R install/man/man1/* $UB_INSTALLDIR/usr/share/man/man1/
mv $UB_INSTALLDIR/usr/lib/lazarus/docs $UB_INSTALLDIR/usr/share/doc/lazarus
mkdir -p $UB_INSTALLDIR/usr/lib/lazarus/docs
ln -s /usr/share/doc/lazarus/chm $UB_INSTALLDIR/usr/lib/lazarus/docs/html
rm -r $UB_INSTALLDIR/usr/lib/lazarus/install
