#!/bin/sh -eux

ub_install
mkdir -p "$UB_INSTALLDIR"/usr/share/PieDock
cp -a res/piedockrc.sample "$UB_INSTALLDIR"/usr/share/PieDock/
cp -a res/active-indicators/gnome-emblem-new.png "$UB_INSTALLDIR"/usr/share/pixmaps/PieDock.png
