#!/bin/sh -eux

ub_compile \
    -DSD_DATADIR=/usr/share/games/speed-dreams-2 \
    -DSD_LIBDIR=/usr/lib/games/speed-dreams-2 \
    -DSD_BINDIR=/usr/bin \
    -DSD_DATADIR_SRC=/usr/share/games/speed-dreams-2
