#!/bin/sh -eux

mkdir -p ${UB_INSTALLDIR}/usr/lib/calibre
tar x -f calibre-${UB_VERSION}-x86_64.txz -C ${UB_INSTALLDIR}/usr/lib/calibre
ln -s /usr/lib/calibre/calibre ${UB_INSTALLDIR}/usr/bin/calibre
