#!/bin/sh -eux

celdir=usr/share/games/quake2
buildceldir="$UB_INSTALLDIR"/$celdir
buildbindir="$UB_INSTALLDIR"/usr/bin
buildbasedir="$buildceldir"/baseq2

mkdir -p $buildceldir buildbasedir

install -Dm755 build/release/quake2 $buildceldir/quake2
install -Dm755 build/release/q2ded $buildceldir
ln -s /usr/share/games/quake2/quake2 $buildbindir/quake2
ln -s /usr/share/games/quake2/q2ded $buildbindir/q2ded

install -m644 build/release/*.so $buildceldir
install -Dm644 build/release/baseq2/game.so $buildbasedir/game.so
