#!/bin/sh -eux

chmod +x txt2c.sh

ub_compile \
	--enable-gpgme \
	--enable-pop \
	--enable-imap \
	--enable-smtp \
	--enable-hcache \
	--enable-sidebar \
	--enable-autocrypt \
	--with-curses=/usr \
	--with-gss=/usr \
	--with-ssl=/usr \
	--with-sqlite3 \
	--with-sasl \
	--with-idn2 \
	--with-docdir=/usr/share/doc/Packages/mutt
