#!/bin/sh -eux

export CXXFLAGS+=' -DNDEBUG'
export LANG='en_US.UTF-8'
ub_make HAVE_RULES=yes CFGDIR=/usr/share/cppcheck/cfg USE_MATCHCOMPILER=yes

ub_make DB2MAN=/usr/share/sgml/docbook/xsl-stylesheets/manpages/docbook.xsl  CFGDIR=/usr/share/cppcheck/cfg man

export QTDIR="/usr/lib/qt5"

cd gui
lrelease gui.pro
qmake HAVE_RULES=yes CFGDIR=/usr/share/cppcheck/cfg
ub_make HAVE_RULES=yes CFGDIR=/usr/share/cppcheck/cfg USE_MATCHCOMPILER=yes
