#!/bin/bash -eux

# mkdir -p ${UB_INSTALLDIR}/lib/firmware

# cp -a linux-firmware/* ${UB_INSTALLDIR}/lib/firmware/

make -C linux-firmware DESTDIR=${UB_INSTALLDIR} install

cp -a dvb-firmware/* ${UB_INSTALLDIR}/lib/firmware

rm -Rf ${UB_INSTALLDIR}/lib/firmware/.git

docdir=${UB_INSTALLDIR}/usr/share/doc/Packages/linux-firmware
mkdir -p ${docdir}
mv linux-firmware/GPL-* ${docdir}/
mv linux-firmware/LICENCE* ${docdir}/
mv linux-firmware/LICENSE* ${docdir}/
mv linux-firmware/README* ${docdir}/
mv linux-firmware/WHENCE ${docdir}/
mv dvb-firmware/LICENCE* ${docdir}/
mv dvb-firmware/license-*.txt ${docdir}/
mv ${UB_INSTALLDIR}/lib/firmware/dvb-*.fw.license.txt ${docdir}/
mv ${UB_INSTALLDIR}/lib/firmware/LICENCE* ${docdir}/
mv ${UB_INSTALLDIR}/lib/firmware/license*.txt ${docdir}/

rm -Rf ${UB_INSTALLDIR}/lib/firmware/{Makefile,configure,README*,*.txt,*.py}

# ütközések törlése
# az if [ -f $i ] kell, mert a dpkg -L listázza a "/."-t is, ami hibát okoz
for i in $(dpkg -L kernel); do
	if [ -f $i ]; then
		rm -rf ${UB_INSTALLDIR}/$i
	fi
done

# ez mégis bennmaradt
rm -rf ${UB_INSTALLDIR}/yamaha
# üres könyvtárak törlése
find ${UB_INSTALLDIR} -type d -empty -delete

# Trigger a microcode reload for configurations not using early updates
install -d "${UB_INSTALLDIR}/usr/lib/tmpfiles.d"
echo 'w /sys/devices/system/cpu/microcode/reload - - - - 1' \
	>"${UB_INSTALLDIR}/usr/lib/tmpfiles.d/linux-firmware.conf"
