#!/bin/sh -eux

make \
    DESTDIR="${UB_INSTALLDIR}/" \
    libdir="/usr/lib/" \
    bindir="/usr/bin/" \
    mandir="/usr/share/man/" \
    includedir="/usr/include/" \
    ENABLE_DOCS=0 \
    V=1 -j1 install
