#!/bin/sh -eux

make install \
    DESTDIR="$UB_INSTALLDIR"

# remove stupid camlp4o.opt which can't work (MDK)
rm -f "$UB_INSTALLDIR"/usr/bin/camlp4*.opt
rm -f "$UB_INSTALLDIR"/usr/share/man/man1/camlp4*.opt.*
rm -Rf "$UB_INSTALLDIR"/usr/local

# fix
ub_replace "$UB_INSTALLDIR" "" "$UB_INSTALLDIR"/usr/lib/ocaml/ld.conf
