#!/bin/sh -eux

make install \
	BINDIR="$UB_INSTALLDIR"/usr/bin \
	LIBDIR="$UB_INSTALLDIR"/usr/lib/ocaml \
	MANDIR="$UB_INSTALLDIR"/usr/share/man

# remove stupid camlp4o.opt which can't work (MDK)
rm -f "$UB_INSTALLDIR"/usr/bin/camlp4*.opt
rm -f "$UB_INSTALLDIR"/usr/share/man/man1/camlp4*.opt.*

# fix
ub_replace "$UB_INSTALLDIR" "" "$UB_INSTALLDIR"/usr/lib/ocaml/ld.conf
