#!/bin/sh -eux

cd rust-std-x86_64-unknown-linux-gnu
cp -r lib ${UB_INSTALLDIR}/usr

cd ../rustc
cp -r bin ${UB_INSTALLDIR}/usr
cp -r lib ${UB_INSTALLDIR}/usr
cp -r share ${UB_INSTALLDIR}/usr

cd ../cargo
cp -r bin ${UB_INSTALLDIR}/usr
cp -r share/doc ${UB_INSTALLDIR}/usr/share
cp -r share/man ${UB_INSTALLDIR}/usr/share

# patchelf
find ${UB_INSTALLDIR}/usr/bin -type f -exec patchelf --set-interpreter /usr/lib/ld-linux-x86-64.so.2 &> /dev/null {} \;
find ${UB_INSTALLDIR}/usr/lib -type f -exec patchelf --set-interpreter /usr/lib/ld-linux-x86-64.so.2 &> /dev/null {} \;
