#!/bin/sh -eux

ub_install

mkdir -p ${UB_INSTALLDIR}/usr/share/icons/hicolor/48x48/apps/ ${UB_INSTALLDIR}/usr/share/icons/hicolor/scalable/apps
mv data/icons/48x48/apps/gufw.png ${UB_INSTALLDIR}/usr/share/icons/hicolor/48x48/apps/gufw.png
mv data/icons/scalable/apps/gufw* ${UB_INSTALLDIR}/usr/share/icons/hicolor/scalable/apps/

mv $UB_INSTALLDIR/usr/bin/gufw-pkexec $UB_INSTALLDIR/usr/sbin/gufw
rm $UB_INSTALLDIR/usr/bin/gufw
rm -rf ${UB_INSTALLDIR}/usr/share/doc/gufw
