#!/bin/sh -eux

mkdir -p build
cd build
export CXXFLAGS='-std=gnu++11 -Wno-write-strings -fno-strict-aliasing -Wno-unused -Wno-unused-but-set-variable -Wno-unused-result -Wno-sign-compare -Wno-reorder'
cmake \
	-DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG \
	-DCMAKE_CXX_FLAGS_DEBUG= \
	-DWITH_OPENGL=Y \
	-DDATADIR=share/games/vavoom\
	-DWITH_SDL=Y \
	-DWITH_LIBMAD:BOOL=OFF \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_BUILD_RYPE=Release \
..
ub_make
