#!/bin/sh -eux

export CXXFLAGS='-std=gnu++11 -Wno-write-strings -fno-strict-aliasing -Wno-unused -Wno-unused-but-set-variable -Wno-unused-result -Wno-sign-compare -Wno-reorder'
ub_compile \
	-DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG \
	-DCMAKE_CXX_FLAGS_DEBUG= \
	-DWITH_OPENGL=Y \
	-DDATADIR=share/games/vavoom\
	-DWITH_SDL=Y \
	-DWITH_LIBMAD:BOOL=OFF
