#!/bin/sh -eux

ub_install
rm -rf "$UB_INSTALLDIR"/usr/share/info
sed -i '1s/guile/guile1.8/' -i "$UB_INSTALLDIR"/usr/bin/guile-config1.8
mv "$UB_INSTALLDIR"/usr/share/aclocal/guile.m4 "$UB_INSTALLDIR"/usr/share/aclocal/guile18.m4
