#!/bin/sh -eux

rm -r ROX-Filer/src
rm -r ROX-Filer/build

mkdir -p "$UB_INSTALLDIR"/usr/share/ROX-Filer
cp -a ROX-Filer/. "$UB_INSTALLDIR"/usr/share/ROX-Filer/
cp -a rox.1 "$UB_INSTALLDIR"/usr/share/man/man1/
mkdir -p "$UB_INSTALLDIR"/etc/xdg/rox.sourceforge.net/MIME-types
cp -a Choices/MIME-types/. \
	"$UB_INSTALLDIR"/etc/xdg/rox.sourceforge.net/MIME-types/
mkdir -p "$UB_INSTALLDIR"/usr/share/locale/hu/LC_MESSAGES
cp -a ROX-Filer/Messages/hu/LC_MESSAGES/ROX-Filer.mo \
	"$UB_INSTALLDIR"/usr/share/locale/hu/LC_MESSAGES/
