#!/bin/sh -eux

#make \
#	prefix=/usr \
#	mandir=/usr/share/man \
#	DESTDIR="$UB_INSTALLDIR" \
#	install-wrapper
#exit 0
install -m 755 cfv   "$UB_INSTALLDIR"/usr/bin/
install -m 644 cfv.1 "$UB_INSTALLDIR"/usr/share/man/man1/
