#!/bin/sh -eux

# install the binaries
install -m 0755 neverball "${UB_INSTALLDIR}"/usr/bin/
install -m 0755 neverputt "${UB_INSTALLDIR}"/usr/bin/

# chmod 644 for all files in data dir
find data -depth -name "*.sol" -print0 | xargs -0 chmod 644

# install the datas
mkdir -p "${UB_INSTALLDIR}"/usr/share/games/neverball
cp -a data "${UB_INSTALLDIR}"/usr/share/games/neverball/

# install icons
for i in 16 24 32 48 64 128 256 512; do
	mkdir -p "${UB_INSTALLDIR}"/usr/share/icons/hicolor/"$i"x"$i"/apps
	install -m 0644 dist/neverball_"$i".png "${UB_INSTALLDIR}"/usr/share/icons/hicolor/"$i"x"$i"/apps/neverball.png
	install -m 0644 dist/neverputt_"$i".png "${UB_INSTALLDIR}"/usr/share/icons/hicolor/"$i"x"$i"/apps/neverputt.png
done
mkdir -p "${UB_INSTALLDIR}"/usr/share/icons/hicolor/scalable/apps
install -m 0644 dist/neverlogos.svg "${UB_INSTALLDIR}"/usr/share/icons/hicolor/scalable/apps/
install -m 0644 dist/neverball_replay.png "${UB_INSTALLDIR}"/usr/share/pixmaps/

# install desktop files
install -m 0644 dist/neverball.desktop "${UB_INSTALLDIR}"/usr/share/applications/
install -m 0644 dist/neverputt.desktop "${UB_INSTALLDIR}"/usr/share/applications/

# install man pages
install -m 0644 dist/neverball.6 "${UB_INSTALLDIR}"/usr/share/man/man6/
install -m 0644 dist/neverputt.6 "${UB_INSTALLDIR}"/usr/share/man/man6/

# install locale files
cp -a locale/. "${UB_INSTALLDIR}"/usr/share/locale/
