#!/bin/sh -eux

ub_install
rm "$UB_INSTALLDIR"/usr/lib/libguile-2.?.so.*-gdb.scm
# just for compatibility
ln -sf guile "$UB_INSTALLDIR"/usr/bin/guile2
ln -sf guile-tools "$UB_INSTALLDIR"/usr/bin/guile2-tools
