#!/bin/sh -eux

ub_install

mkdir -p ${UB_INSTALLDIR}/usr/lib/ccache/bin

_host="x86_64-linux-gnu"

for _prog in gcc g++ c++; do
    ln -s /usr/bin/ccache "${UB_INSTALLDIR}/usr/lib/ccache/bin/$_prog"
    ln -s /usr/bin/ccache "${UB_INSTALLDIR}/usr/lib/ccache/bin/$_host-$_prog"
done
for _prog in cc clang clang++; do
    ln -s /usr/bin/ccache "${UB_INSTALLDIR}/usr/lib/ccache/bin/$_prog"
done
