#!/bin/sh -eux

ub_install \
	PKG_BIN_DIR="$UB_INSTALLDIR"/usr/bin \
	PKG_LIB_DIR="$UB_INSTALLDIR"/usr/lib \
	PKG_DEVLIB_DIR="$UB_INSTALLDIR"/usr/lib \
	PKG_SBIN_DIR="$UB_INSTALLDIR"/usr/sbin \
	PKG_MAN_DIR="$UB_INSTALLDIR"/usr/share/man \
	PKG_USER=root \
	PKG_GROUP=root \
	install-lib \
	install-dev
