#!/bin/sh -eux

ub_install

cp examples/chrony.conf.example1 "$UB_INSTALLDIR"/etc/chrony.conf

cp examples/chronyd.service "$UB_INSTALLDIR"/usr/lib/systemd/system/chronyd.service

mkdir -p "$UB_INSTALLDIR"/etc/NetworkManager/dispatcher.d
cp examples/chrony.nm-dispatcher.onoffline "$UB_INSTALLDIR"/etc/NetworkManager/dispatcher.d/chrony.nm-dispatcher
