#!/bin/sh -eux

ub_install

# Back to python script variant of python-config instead of the shell script one
# to let other packages (like waf) happy
sed -i "s,@EXENAME@,/usr/bin/python3," Misc/python-config.in
cp Misc/python-config.in "$UB_INSTALLDIR"/usr/bin/python3.6m-config
