#!/bin/sh -eux

ub_install
mkdir -p ${UB_INSTALLDIR}/etc/xdg/autostart
ln -s /usr/share/applications/polkit-cinnamon-authentication-agent-1.desktop ${UB_INSTALLDIR}/etc/xdg/autostart/
rm -f "${UB_INSTALLDIR}"/etc/xdg/menus/cinnamon-applications-merged
mv ${UB_INSTALLDIR}/usr/bin/cinnamon-settings ${UB_INSTALLDIR}/usr/bin/cinnamon-settings.bin
