#!/bin/sh -eux

cp wolf4sdl-wl6 wolf4sdl-sdm wolf4sdl-sod wolf4sdl-wl6a1 wolf4sdl-wl11d wolf4sdl-wl1 wolf4sdl-wl12d "$UB_INSTALLDIR"/usr/bin/

#for i in \
#	wolf3d-shareware-v11\
#	wolf3d-shareware-v12\
#	wolf3d-shareware-v14\
#	wolf3d-full-apogee-v11\
#	wolf3d-full-gt-id-activision-v14\
#	spear-demo\
#	spear-full
#do
#illető könyvtár
#install -d -m 777 "$UB_INSTALLDIR"/usr/share/games/wolf4sdl/"$i"
#illető bináris
#install -m 755 "$i".bin "$UB_INSTALLDIR"/usr/share/games/wolf4sdl/"$i"/wolf4sdl
#done
