#!/bin/sh -eux

ub_install
mkdir -p ${UB_INSTALLDIR}/usr/share/jwm-settings-manager/themes/Default/
cp -f ${UB_SRCDIR}/patches/UHU-default.skip ${UB_INSTALLDIR}/etc/system.jwmrc
cp ${UB_SRCDIR}/patches/UHU-default.skip ${UB_INSTALLDIR}/usr/share/jwm-settings-manager/themes/Default/Default
