#!/bin/sh -eux

ub_install
# data rész külön, 246,5 Mb.
rm -rf ${UB_INSTALLDIR}/usr/share/gcompris/boards/{dataset,mrpatate,music,skins,sounds,voices}
rm -rf ${UB_INSTALLDIR}/usr/share/gcompris/boards/lang/words
rm -rf ${UB_INSTALLDIR}/usr/share/gcompris/boards/piano_composition/{bass_pitches,treble_pitches,playActivities}

rm -f ${UB_INSTALLDIR}/usr/share/gcompris/boards/paintings/{*.png,*.jpg}
rm -rf ${UB_INSTALLDIR}/usr/share/gcompris/boards/babyshapes/{dog1,dog2,dog3,food,*.png}
rm -f ${UB_INSTALLDIR}/usr/share/gcompris/boards/babyshapes/*.png
rm -f ${UB_INSTALLDIR}/usr/share/gcompris/boards/instruments/{*.png,*.ogg}

#verzió a letöltő postinstbe
sed "s/ubversion/$UB_VERSION/" -i $UB_SRCDIR/packages/gcompris-data/postinst
