#!/bin/sh -eux

export PERL5LIB+="$UB_COMPILEDIR"
export CFLAGS+=" -I/usr/include/openssl-1.0"
export CPPFLAGS+=" -I/usr/include/openssl-1.0"
export LDFLAGS+=" -L/usr/lib/openssl-1.0"
ub_compile \
	--prefix=/ \
	--with-ldap-conf-file=/etc/ldap.conf \
	--with-ldap-secret-file=/etc/ldap.secret \
	--libdir=/usr/lib
