#!/bin/sh -eux

ub_install

mkdir -p "$UB_INSTALLDIR"/usr/share/doc/Packages/libvorbis
mv "$UB_INSTALLDIR"/usr/share/doc/libvorbis-"$UB_VERSION" \
	"$UB_INSTALLDIR"/usr/share/doc/Packages/libvorbis/html
