#!/bin/sh -eux

ub_compile \
	--with-opengl \
	--with-gtk=3 \
	--enable-unicode \
	--enable-ipv6 \
	--enable-intl \
	--disable-precomp-headers \
	--enable-graphics_ctx \
	--enable-mediactrl \
	--enable-webview \
	--with-libpng=sys \
	--with-libxpm=sys \
	--with-libjpeg=sys \
	--with-libtiff=sys \
	--with-regex=builtin
