#!/bin/sh -eux

# https://github.com/KhronosGroup/glslang/blob/master/known_good.json
git clone https://github.com/KhronosGroup/SPIRV-Tools.git External/spirv-tools
cd External/spirv-tools
git checkout 40f5bf59c6acb4754a0bffd3c53a715732883a12
cd ../../

git clone https://github.com/KhronosGroup/SPIRV-Headers External/spirv-tools/external/spirv-headers
cd External/spirv-tools/external/spirv-headers
git checkout 1d31a100405cf8783ca7a31e31cdd727c9fc54c3
cd -

ub_compile \
	-DBUILD_SHARED_LIBS=OFF \
	-DENABLE_CTEST=OFF
