#!/bin/sh -eux

ub_compile \
	--enable-optimization \
	--enable-3ds-import \
	--enable-javascript-api \
	--enable-threadsafe \
	--enable-exceptions \
	--with-mesa \
	--disable-debug \
	--disable-maintainer-mode \
	--enable-system-expat
