#!/bin/sh -eux

tar -xzf master-pdf-editor-${UB_VERSION}-qt5.amd64.tar.gz
cd master-pdf-editor-5
patch -i "$UB_SRCDIR"/patches/desktop.patch.skip
mkdir -p ${UB_INSTALLDIR}/usr/lib/master-pdf-editor-5
mv masterpdfeditor5.desktop ${UB_INSTALLDIR}/usr/share/applications/
cp -r * ${UB_INSTALLDIR}/usr/lib/master-pdf-editor-5/
