#!/bin/sh -eux

ub_install

cp server/dhcpd.conf.example "$UB_INSTALLDIR"/etc/dhcpd.conf
cp doc/examples/dhcpd-dhcpv6.conf "$UB_INSTALLDIR"/etc/dhcpd6.conf

# create empty leases file
mkdir -p "$UB_INSTALLDIR"/var/db/
touch "$UB_INSTALLDIR"/var/db/dhcpd.leases
touch "$UB_INSTALLDIR"/var/db/dhcpd6.leases
cp -a doc ${UB_INSTALLDIR}/usr/share/doc/dhcp

rm -rf ${UB_INSTALLDIR}/usr/share/doc
