#!/bin/sh -eux

export TARGET_ARCH=desktop
export UI_TYPE=qt4
export TARGET_STATUS=release

sed -i 's|moc-qt4|moc|g' makefiles/arch/desktop.mk
sed -i 's|-lunibreak|-llinebreak|g' makefiles/config.mk zlibrary/text/Makefile

ub_make \
	ZLSHARED=no
