#!/bin/sh -eux

export GOHOSTARCH=amd64
export GOARCH=$GOHOSTARCH
export GOROOT_FINAL=/usr/lib/go
export GOROOT_BOOTSTRAP=/usr/lib/go
export GOPATH="$UB_COMPILEDIR"/
export GOROOT="$UB_COMPILEDIR"
export GOBIN="$GOROOT/bin"
cd src
./make.bash --no-clean -v
PATH="$GOBIN:$PATH" go install -v -buildmode=shared std
PATH="$GOBIN:$PATH" go install -v -race std
