#!/bin/sh -eux

export GOHOSTARCH=amd64
export GOARCH=$GOHOSTARCH
export GOROOT_FINAL=/usr/lib/go
export GOROOT_BOOTSTRAP=/usr/lib/go

mkdir -p "$UB_INSTALLDIR/usr/lib/go"
mkdir -p "$UB_INSTALLDIR/usr/share/doc/go"
cp -a bin pkg src lib misc api test "$UB_INSTALLDIR/usr/lib/go"

ln -sf linux_${GOARCH} ${UB_INSTALLDIR}/usr/lib/go/pkg/linux_${GOARCH}_shared

cp -r doc/* "$UB_INSTALLDIR/usr/share/doc/go"
ln -sf /usr/lib/go/bin/go "$UB_INSTALLDIR/usr/bin/go"
ln -sf /usr/lib/go/bin/gofmt "$UB_INSTALLDIR/usr/bin/gofmt"
ln -sf /usr/share/doc/go "$UB_INSTALLDIR/usr/lib/go/doc"
cp VERSION "$UB_INSTALLDIR/usr/lib/go/"
rm -rf "$UB_INSTALLDIR/usr/lib/go/pkg/bootstrap"
rm -rf "$UB_INSTALLDIR/usr/lib/go/pkg/tool/*/api"
# TODO: Figure out if really needed
rm -rf "$UB_INSTALLDIR"/usr/lib/go/pkg/obj/go-build/*
rm "$UB_INSTALLDIR"/usr/lib/go/src/*.rc
