#!/bin/sh -eux

rm -f CMakeLists.txt
NOCONFIGURE=1 ./autogen.sh

export CFLAGS=`pkg-config pango --cflags`
export LIBPOSTFIX=/
ub_compile \
	--enable-ocaml=no \
	--enable-perl=no \
	--enable-tk=no \
	--enable-tcl=no \
	--enable-ruby=no \
	--enable-lua=no \
	--enable-python=no
