#!/bin/sh -eux

ub_install

rm -rf "$UB_INSTALLDIR"/usr/share/graphviz/{doc,graphs,lefty,gvpr}
rm -rf "$UB_INSTALLDIR"/usr/include
rm -rf "$UB_INSTALLDIR"/usr/lib
cp "$UB_INSTALLDIR"/usr/bin/gvedit ./
cp "$UB_INSTALLDIR"/usr/share/man/man1/gvedit.1 ./
rm -f "$UB_INSTALLDIR"/usr/bin/*
rm -f "$UB_INSTALLDIR"/usr/share/man/man1/*
rm -rf "$UB_INSTALLDIR"/usr/share/man/{man7,man3}
cp gvedit "$UB_INSTALLDIR"/usr/bin/
cp gvedit.1 "$UB_INSTALLDIR"/usr/share/man/man1/
