#!/bin/sh -eux

autoreconf -vif

ub_compile \
	--enable-password-save \
	--enable-iproute2 \
	--enable-plugins \
	--enable-systemd \
    --enable-x509-alt-username \
    --with-crypto-library=openssl
