#!/bin/sh -e

query_immodules ()
{
	[ -z "${UHU_PKG_QUIET+x}" ] && echo -n "  Querying GTK3 input methods ..."
	touch /usr/lib/gtk-3.0/3.0.0/immodules.cache
	gtk-query-immodules-3.0 --update-cache
	true > /var/lib/uhu-pkg/gtk-immodules
	while [ ! /var/lib/uhu-pkg/gtk-immodules -ot /var/lib/dpkg/info \
	     -a ! /var/lib/uhu-pkg/gtk-immodules -nt /var/lib/dpkg/info ]; do
		sleep 0.1
		true > /var/lib/uhu-pkg/gtk-immodules
	done
	[ -z "${UHU_PKG_QUIET+x}" ] && echo
}

if [ -f /var/lib/uhu-pkg/gtk-immodules -a /var/lib/uhu-pkg/gtk-immodules -nt /var/lib/dpkg/info ]; then
	exit 0
fi

if [ "$1" = "gtk" -o "$1" = "+" ]; then
	query_immodules
elif grep -q '^/usr/lib/gtk-3\.0/3\.0\.0/immodules/' /var/lib/dpkg/info/"$1".list; then
	query_immodules
fi
