#!/bin/sh -eux

INSTALL_ROOT=$UB_INSTALLDIR \
ub_install

mkdir -p $UB_INSTALLDIR/usr/share/{applications,pixmaps,man/man1}
cp install_scripts/environment/desktop/QXmlEdit.desktop $UB_INSTALLDIR/usr/share/applications/
cp install_scripts/environment/icon/qxmledit.png $UB_INSTALLDIR/usr/share/pixmaps/
cp install_scripts/environment/man/qxmledit.1 $UB_INSTALLDIR/usr/share/man/man1/
