#!/bin/sh -eux

rm CMakeLists.txt
sed -i -e "s:-lpcre ::" libpcrecpp.pc.in
ub_compile \
	--enable-pcre32 \
	--enable-pcre16 \
	--enable-utf8 \
	--enable-pcre8 \
	--enable-unicode-properties \
	--enable-jit
