#!/bin/sh -eux

export SETUPTOOLS_INSTALL_WINDOWS_SPECIFIC_FILES=0
cd py3
python3 setup.py install --root="$UB_INSTALLDIR"
mv "$UB_INSTALLDIR"/usr/bin/easy_install "$UB_INSTALLDIR"/usr/bin/easy_install3

cd ../py2
python2 setup.py install --root="$UB_INSTALLDIR"

py3docdir="$UB_INSTALLDIR"/usr/share/doc/Packages/python3-setuptools
mkdir -p $py3docdir
cp docs/*.txt $py3docdir/
