#!/bin/sh -eux

ub_compile \
    -Dx11_backend=true \
    -Dwayland_backend=true \
	-Dbroadway_backend=false \
	-Dcolord=yes \
	-Ddemos=false \
	-Dexamples=false \
	-Dtests=false \
	-Dinstalled_tests=false
