#!/bin/sh -eux

python2 setup.py install --root="$UB_INSTALLDIR"
python3 setup.py install --root="$UB_INSTALLDIR"

py3docdir="$UB_INSTALLDIR"/usr/share/doc/Packages/python3-jinja2
mkdir -p $py3docdir
cp CHANGES.rst README.rst LICENSE.rst $py3docdir/
