#!/bin/sh -eux

export XDG_DATA_DIRS=$UB_INSTALLDIR/usr/share
mkdir -p $UB_INSTALLDIR/usr/share/{icons/hicolor,applications,desktop-directories}

make \
    PREFIX=/usr \
    GNOME_PREFIX=/usr \
    DESTDIR=${UB_INSTALLDIR} \
    install
rm -rf ${UB_INSTALLDIR}/usr/include
