#!/bin/sh -eux

NOCONFIGURE=1 ./autogen.sh
ub_compile \
	--disable-local \
	--enable-aptcc \
	--disable-cron \
	--enable-introspection \
	--enable-gtk-module \
	--enable-gstreamer-plugin \
	--disable-gtk-doc \
	--enable-systemd
