#!/bin/sh -eux

ub_install
rm -f ${UB_INSTALLDIR}/usr/share/PackageKit/pk-upgrade-distro.sh
rm -f ${UB_INSTALLDIR}/var/lib/PackageKit/transactions.db

# Ubuntu-specific, broken
rm -f ${UB_INSTALLDIR}/usr/share/PackageKit/helpers/aptcc/get-distro-upgrade.py
