#!/bin/sh -eux

autoreconf -vif
ub_compile \
	--libexecdir=/usr/lib/genius \
	--localstatedir=/var \
	--disable-update-mimedb \
	--disable-scrollkeeper \
	--disable-extra-gcc-optimization \
	--enable-compile-warnings=minimum
