#!/bin/sh -eux

autoconf
ub_compile \
	--libexecdir=/usr/lib/genius \
	--localstatedir=/var \
	--enable-gtksourceview \
	--disable-update-mimedb \
	--disable-scrollkeeper \
	--disable-extra-gcc-optimization \
	--enable-compile-warnings=minimum
