#!/bin/sh -eux

ub_install
mkdir -p $UB_INSTALLDIR/{usr/lib/systemd/user,etc/conf.d}
cp build/fluidsynth.service $UB_INSTALLDIR/usr/lib/systemd/user/
cp build/fluidsynth.conf $UB_INSTALLDIR/etc/conf.d/fluidsynth
# tuxguitar kompatibitás
ln -s libfluidsynth.so.3 $UB_INSTALLDIR/usr/lib/libfluidsynth.so.2
