#!/bin/sh -eux

# engine
ub_install

# mod
rm -rf $UB_INSTALLDIR/usr/lib/etlegacy/legacy

# assets
ln -s /usr/share/enemy-territory/etmain/{pak0,pak1,pak2}.pk3 $UB_INSTALLDIR/usr/lib/etlegacy/etmain/

#doc
rm -f $UB_INSTALLDIR/usr/lib/etlegacy/COPYING.txt

# systemd
mkdir -p $UB_INSTALLDIR/etc/xdg/etlegacy/etmain
cp misc/etlegacy.conf $UB_INSTALLDIR/etc/xdg/etlegacy/
cp misc/etlegacy.service $UB_INSTALLDIR/usr/lib/systemd/system/

# config linkek
mv $UB_INSTALLDIR/usr/lib/etlegacy/etmain/*.cfg $UB_INSTALLDIR/etc/xdg/etlegacy/etmain/
ln -s /etc/xdg/etlegacy/etmain/{etl_server,legacy,{campaign,lms,mapvote,objective}cycle}.cfg \
$UB_INSTALLDIR/usr/lib/etlegacy/etmain/

# server
mkdir -p $UB_INSTALLDIR/var/lib/etlegacy-server
ln -s /etc/xdg/etlegacy/etmain $UB_INSTALLDIR/var/lib/etlegacy-server/

# mod

# kibontás etlegacy fájlok eljhelyezése

tar -x -f 407
rm 407

cd etlegacy*
mkdir -p $UB_INSTALLDIR/usr/lib/etlegacy/legacy
cp legacy/legacy_v${UB_VERSION}.pk3 $UB_INSTALLDIR/usr/lib/etlegacy/legacy/
cp legacy/qagame.mp.*.so $UB_INSTALLDIR/usr/lib/etlegacy/legacy/

# Geiop helyadatok
ln -s /usr/share/GeoIP/GeoIP.dat $UB_INSTALLDIR/usr/lib/etlegacy/legacy

# desktop igazítás
sed /PrefersNonDefaultGPU/d -i $UB_INSTALLDIR/usr/share/applications/com.etlegacy.ETLegacy.desktop

# data
cd -
chmod +x et260b.x86_keygen_V03.run
./et260b.x86_keygen_V03.run --noexec --nox11 --target enemy-territory

mkdir -p $UB_INSTALLDIR/usr/share/enemy-territory/etmain
cp enemy-territory/etmain/{pak0,pak1,pak2}.pk3 $UB_INSTALLDIR/usr/share/enemy-territory/etmain/
cp -r enemy-territory/Docs ./
