#!/bin/sh -eux

# alapinstallálás
ub_install

# alap mod eltávolítása
rm -rf $UB_INSTALLDIR/usr/lib/etlegacy/legacy

# a szükséges enemy-territory adatokra linkek
ln -s /usr/share/enemy-territory/etmain/{pak0,pak1,pak2}.pk3 $UB_INSTALLDIR/usr/lib/etlegacy/etmain/

# doc
mkdir -p $UB_INSTALLDIR/usr/share/doc/Packages/etlegacy
mv $UB_INSTALLDIR/usr/lib/etlegacy/INSTALL.txt $UB_INSTALLDIR/usr/share/doc/Packages/etlegacy/
rm -f $UB_INSTALLDIR/usr/lib/etlegacy/COPYING.txt

# systemd
mkdir -p $UB_INSTALLDIR/etc/xdg/etlagacy/etmain
cp misc/etlegacy.conf $UB_INSTALLDIR/etc/xdg/etlagacy/
cp misc/etlegacy.service $UB_INSTALLDIR/usr/lib/systemd/system/

# config linkek
mv $UB_INSTALLDIR/usr/lib/etlegacy/etmain/*.cfg $UB_INSTALLDIR/etc/xdg/etlagacy/etmain/
ln -s /etc/xdg/etlegacy/etmain/{etl_server,legacy,{campaign,lms,mapvote,objective}cycle}.cfg \
    $UB_INSTALLDIR/usr/lib/etlegacy/etmain/

# melyik etlegacy architektúra ?
if [ "$UB_ARCH" == "amd64" ];then
tarfile="87"
else
tarfile="85"
fi

# kibontás
tar -x -f $tarfile
rm -f $tarfile

# etlegacy fájlok eljhelyezése
cd etlegacy*
mkdir -p $UB_INSTALLDIR/usr/lib/etlegacy/legacy
cp legacy/{etl_bin,pak3}_v$UB_VERSION.pk3 $UB_INSTALLDIR/usr/lib/etlegacy/legacy/
cp legacy/qagame.mp.*.so $UB_INSTALLDIR/usr/lib/etlegacy/legacy/

# Geiop helyadatok
ln -s /usr/share/GeoIP/GeoIP.dat $UB_INSTALLDIR/usr/lib/etlegacy/legacy
