#!/bin/sh -eux

ub_makeinstall

rm "$UB_INSTALLDIR"/usr/bin/2to3

#2.5
ln -sf python"$UB_VERSION_HEAD1" "$UB_INSTALLDIR"/usr/bin/python2.5

#2.6
ln -sf python"$UB_VERSION_HEAD1" "$UB_INSTALLDIR"/usr/bin/python2.6
