#!/bin/sh -eux

CC="ccache clang -march=k8 -m64"
CXX="ccache clang++ -march=k8 -m64"

export RUSTFLAGS="-Cdebuginfo=0"
export LDFLAGS="-Wl,-rpath,/usr/lib/firefox/ -Wl,--no-keep-memory -Wl,-z,relro -Wl,-z,now"
export PYTHON=/usr/bin/python3
export MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE=system

: > .mozconfig
cat > .mozconfig << _EOF_
mk_add_options MOZ_OBJDIR=$UB_OBJECTDIR
ac_add_options --prefix=/usr
ac_add_options --enable-application=browser
ac_add_options --enable-release
ac_add_options --enable-official-branding
ac_add_options --enable-optimize="-O2"
ac_add_options --enable-crashreporter
ac_add_options --enable-default-toolkit=cairo-gtk3-wayland
ac_add_options --enable-bundled-fonts
ac_add_options --enable-rust-simd
ac_add_options --enable-linker=lld
ac_add_options --disable-bootstrap
ac_add_options --disable-debug
ac_add_options --disable-elf-hack
ac_add_options --disable-install-strip
ac_add_options --disable-strip
ac_add_options --disable-tests
ac_add_options --disable-updater
ac_add_options --allow-addon-sideload
ac_add_options --with-unsigned-addon-scopes=app,system
ac_add_options --without-system-icu
ac_add_options --without-system-png
ac_add_options --with-system-jpeg
ac_add_options --with-system-libvpx
ac_add_options --with-system-nss
ac_add_options --with-system-nspr
ac_add_options --with-system-zlib
ac_add_options --without-system-libevent
ac_add_options --without-wasm-sandboxed-libraries
_EOF_

"$UB_COMPILEDIR"/mach build
