#!/bin/sh -eux

cd "$UB_OBJECTDIR"

export PYTHON=/usr/bin/python3
export MACH_USE_SYSTEM_PYTHON=1
DESTDIR="$UB_INSTALLDIR" "$UB_COMPILEDIR"/mach install

rm -f "$UB_INSTALLDIR"/usr/lib/firefox/firefox
rm -f "$UB_INSTALLDIR"/usr/bin/firefox

mkdir -p "$UB_INSTALLDIR"/usr/lib/firefox/browser/extensions
mv "$UB_COMPILEDIR"/hu.xpi "$UB_INSTALLDIR"/usr/lib/firefox/browser/extensions/langpack-hu@firefox.mozilla.org.xpi

# install icons
for i in 16 22 24 32 48 64 128 256; do
    install -Dm644 "$UB_COMPILEDIR"/browser/branding/official/default$i.png \
      "$UB_INSTALLDIR/usr/share/icons/hicolor/${i}x${i}/apps/firefox.png"
done
cp "$UB_COMPILEDIR"/browser/branding/official/default48.png "$UB_INSTALLDIR"/usr/share/pixmaps/firefox.png

cd "$UB_INSTALLDIR"/usr/lib/firefox
ln -s firefox-bin firefox
cd -
