#!/bin/sh -eux

cd "$UB_OBJECTDIR"

ub_install

cp "$UB_COMPILEDIR"/browser/branding/official/default48.png "$UB_INSTALLDIR"/usr/share/pixmaps/firefox.png

rm -f "$UB_INSTALLDIR"/usr/lib/firefox/firefox
rm -f "$UB_INSTALLDIR"/usr/bin/firefox
ln -s /usr/lib/firefox/firefox "$UB_INSTALLDIR"/usr/bin/firefox

if [ ! -f "$UB_INSTALLDIR"/usr/lib/firefox/run-mozilla.sh ]; then
	cp "$UB_COMPILEDIR"/build/unix/run-mozilla.sh "$UB_INSTALLDIR"/usr/lib/firefox/run-mozilla.sh
fi

mkdir -p "$UB_INSTALLDIR"/usr/lib/firefox/browser/extensions/langpack-hu@firefox.mozilla.org
cp -aR "$UB_COMPILEDIR"/langpack-hu/. "$UB_INSTALLDIR"/usr/lib/firefox/browser/extensions/langpack-hu@firefox.mozilla.org/
