#!/bin/bash -eux

function alprogi {
	cd $1
    export PREFIX=/usr
    ub_compile
    cd -
}
#előkészület
KVER="$(ls -1 /usr/lib/modules | grep x86_64)"
moduldir="$UB_COMPILEDIR/usr/lib/modules/"$KVER"/kernel/drivers/video"
mkdir -p $moduldir
forras="NVIDIA-Linux-x86_64-${UB_VERSION}-no-compat32"
#kicsomagolás és belépés
chmod +x $forras.run
./"$forras".run -x
mv $forras/* ./
rm -f $forras.run
rm -rf $forras
cd kernel
patch -Np1 < "$UB_SRCDIR"/patches/drm-detection.skip
make CC=gcc SYSSRC=/usr/src/linux-$KVER KERNEL_UNAME="$KVER" MODULE_ROOT=$moduldir module
cd ..
export NV_USE_BUNDLED_LIBJANSSON=0
alprogi settings
alprogi settings/src/libXNVCtrl
alprogi xconfig
alprogi modprobe
alprogi persistenced
