#!/bin/sh -eux

git submodule init
git submodule update
mkdir -p build
cd build
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="/usr" \
	-DINSTALL_SUBDIR_BIN="bin" \
	..

ub_make
