#!/bin/sh -eux

set -u
ub_install
mv "${UB_INSTALLDIR}/usr/doc" "${UB_INSTALLDIR}/usr/share/"
# remove perllocal.pod and .packlist (these don't seem to exist any more)
find "${UB_INSTALLDIR}" -name 'perllocal.pod' -delete
find "${UB_INSTALLDIR}" -name '.packlist' -delete
set +u
