#!/bin/sh -eux

ub_install

#cd "$UB_INSTALLDIR"/etc/gnome-vfs-2.0/vfolders
#mv applications-all-users.vfolder-info applications-all-users.vfolder-info.gnome2
#ln -s /usr/lib/menu/gnome/UHU.vfolder-info applications-all-users.vfolder-info
