#!/bin/sh -eux

jobs="-j${UB_MAKE_PROCS:-$(_procs)}"
pythonver=$(python -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')

./bootstrap.sh \
	--with-toolset=gcc \
	--with-icu \
	--with-python=/usr/bin/python3 \
	--with-python-version=$pythonver

./b2 \
	variant=release \
	debug-symbols=off \
	threading=multi \
	runtime-link=shared \
	link=shared \
	toolset=gcc \
	python=$pythonver \
	cflags="-fPIC" \
	cxxflags="-std=c++14 -fPIC" \
	$jobs \
	--layout=system \
	--prefix="$UB_INSTALLDIR"/usr \
	install
