#!/bin/sh -eux

jobs="-j${UB_MAKE_PROCS:-$(_procs)}"

./bootstrap.sh \
	--with-toolset=gcc \
	--with-icu \
	--with-python=/usr/bin/python3 \
	--with-python-version=3.10

./b2 \
	variant=release \
	debug-symbols=off \
	threading=multi \
	runtime-link=shared \
	link=shared \
	toolset=gcc \
	python=3.10 \
	cflags="-fPIC" \
	cxxflags="-std=c++14 -fPIC" \
	$jobs \
	--layout=system \
	--prefix="$UB_INSTALLDIR"/usr \
	install
