#!/bin/sh -eux

export WXRC=/usr/bin/wxrc

ub_compile \
	--with-pugixml=builtin \
	--with-wx-config=/usr/bin/wx-config \
	--disable-autoupdatecheck \
	--disable-manualupdatecheck \
	--disable-dependency-tracking
