#!/bin/sh -eux

celdir="$UB_INSTALLDIR"/usr/share/games/humphrey
install -d -m 777 $celdir
cp -r images $celdir
install -m 644 abc.dat enemigos.dat humphrey imgt.dat msc.dat obj.dat snd.dat readme.htm $celdir/
install -m 755 humphrey $celdir/
chmod 0777 $celdir
rm -rf ${UB_INSTALLDIR}/usr/include
