#!/bin/sh -eux

ub_install

ln -sf libmariadb.so.3 "$UB_INSTALLDIR"/usr/lib/libmysqlclient.so.18
ln -sf mariadb.pc "$UB_INSTALLDIR"/usr/lib/pkgconfig/mysql.pc
ln -sf mariadb "$UB_INSTALLDIR"/usr/include/mysql
