#!/bin/sh -eux

unset CPPFLAGS
CXXFLAGS+=' -fno-delete-null-pointer-checks -fpermissive -fno-tree-vrp -fno-strict-aliasing -flto=3'
CFLAGS+=' -fno-delete-null-pointer-checks -fpermissive -fno-tree-vrp -fno-strict-aliasing -flto=3'
export CC=gcc CXX=g++ PYTHON=/usr/bin/python2

cd js/src
export JS_STANDALONE=1
export MOZ_OBJDIR=$UB_OBJECTDIR

cd "$UB_OBJECTDIR"
"$UB_COMPILEDIR"/js/src/configure \
	--prefix=/usr \
	--with-system-nspr \
    --with-system-zlib \
	--with-system-icu \
	--with-intl-api \
	--enable-ctypes \
	--enable-system-ffi \
	--enable-shared-js \
	--enable-optimize="-O2" \
	--enable-pie \
	--disable-strip \
	--disable-debug \
	--enable-readline \
	--enable-release
ub_make
