#!/bin/sh -eux

unset CPPFLAGS
CXXFLAGS+=' -fno-delete-null-pointer-checks -fpermissive -fno-tree-vrp -fno-strict-aliasing -flto=3'
CFLAGS+=' -fno-delete-null-pointer-checks -fpermissive -fno-tree-vrp -fno-strict-aliasing -flto=3'
export CC=gcc CXX=g++ PYTHON=/usr/bin/python2

cd js/src
export JS_STANDALONE=1
export MOZ_OBJDIR=$UB_OBJECTDIR

cd "$UB_OBJECTDIR"
"$UB_COMPILEDIR"/js/src/configure \
	--prefix=/usr \
	--with-system-bz2 \
	--with-system-icu \
	--with-system-jpeg \
	--with-system-libvpx \
	--with-system-nspr \
	--with-system-nss \
	--with-system-png \
    --with-system-zlib \
	--enable-system-hunspell \
	--enable-system-sqlite \
	--with-intl-api \
	--enable-shared-js \
	--enable-optimize="-O2" \
	--disable-strip \
	--disable-debug \
	--disable-debug-symbols \
	--disable-jemalloc \
	--enable-readline \
	--enable-release \
	--enable-hardening \
	--enable-linker=gold
ub_make
