#!/bin/sh -eux

# unset CPPFLAGS
# CXXFLAGS+=' -fno-delete-null-pointer-checks -fpermissive -fno-tree-vrp -fno-strict-aliasing -flto=3'
# CFLAGS+=' -fno-delete-null-pointer-checks -fpermissive -fno-tree-vrp -fno-strict-aliasing -flto=3'
export CC=gcc CXX=g++ PYTHON=/usr/bin/python2

cd js/src
export JS_STANDALONE=1
export MOZ_OBJDIR=$UB_OBJECTDIR

cd "$UB_OBJECTDIR"
"$UB_COMPILEDIR"/js/src/configure \
    --prefix=/usr \
    --disable-debug \
    --disable-debug-symbols \
    --disable-jemalloc \
    --disable-strip \
    --enable-hardening \
    --enable-linker=gold \
    --enable-optimize \
    --enable-posix-nspr-emulation \
    --enable-readline \
    --enable-release \
    --enable-shared-js \
    --enable-tests \
    --with-intl-api \
    --with-system-zlib \
    --without-system-icu
ub_make
