#!/bin/sh -eux

ub_install site-perl-install

cd bindings/perl-piped
ub_install

cd ../perl-shared
ub_install

# ugly hack to install ruby binding
mkdir -p "$UB_INSTALLDIR"/usr/lib/ruby/site_ruby/2.6.0/x86_64-linux

cd ../ruby
ub_install
