#!/bin/sh -eux

python3 setup.py install --prefix=/usr --root=${UB_INSTALLDIR} --optimize=1

rm -f "$UB_INSTALLDIR"/usr/share/glib-2.0/schemas/gschemas.compiled
rm -f "$UB_INSTALLDIR"/usr/share/icons/hicolor/icon-theme.cache
