#!/bin/sh -eux

cp amavisd "$UB_INSTALLDIR/usr/sbin"
cp amavisd-agent "$UB_INSTALLDIR/usr/sbin"
cp amavisd-nanny "$UB_INSTALLDIR/usr/sbin"
cp amavisd-release "$UB_INSTALLDIR/usr/sbin"

cp amavisd.conf "$UB_INSTALLDIR/etc/amavisd.conf"
