#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR"/usr/share/games/simutrans $UB_INSTALLDIR/usr/share/pixmaps/
cp -r simutrans/{config,font,music,text,themes,pak} "$UB_INSTALLDIR"/usr/share/games/simutrans/
cp build/default/sim $UB_INSTALLDIR/usr/bin/simutrans
chmod +x $UB_INSTALLDIR/usr/bin/simutrans
cp simutrans.svg "$UB_INSTALLDIR"/usr/share/pixmaps/
