#!/bin/sh -eux

# patchset: https://github.com/stha09/chromium-patches

if [ $((`stat -f -c "%a" .`*`stat -f -c "%s" .`/(1024*1024*1024))) -lt 15 ]; then
	echo "At least 15 GB free space is required!"
	exit 1
fi

procs=$(grep ^processor /proc/cpuinfo | wc -l)
jobs=$(($procs / 2))

# gcc-vel sokkal gyorsabb a build, mivel használja a ccache-t
# linkelni viszont az lld-vel kell (use_lld=true), a többi elszáll
export CC=gcc
export CXX=g++
export AR=ar
export NM=nm
# export CC=clang
# export CXX=clang++
# export AR=llvm-ar
# export NM=nm

# ccache
export CCACHE_CPP2=yes
export CCACHE_SLOPPINESS=time_macros

_flags=("
custom_toolchain=\"//build/toolchain/linux/unbundle:default\"
host_toolchain=\"//build/toolchain/linux/unbundle:default\"
is_debug=false
cc_wrapper=\"ccache\"
clang_base_path=\"/usr\"
is_clang=false
is_cfi=false
is_official_build=true
clang_use_chrome_plugins=false
fatal_linker_warnings=false
treat_warnings_as_errors=false
disable_fieldtrial_testing_config=true
blink_enable_generated_code_formatting=false
ffmpeg_branding=\"Chrome\"
proprietary_codecs=true
rtc_use_pipewire=true
use_gold=false
use_lld=true
use_sysroot=false
symbol_level=0
enable_linux_installer=false
enable_nacl=false
enable_widevine=true
enable_hangout_services_extension=false
enable_rust=false
use_custom_libcxx=false
use_kerberos=false
use_system_libffi=true
gtk_version=3
icu_use_data_file=false
")

# rendszerből használadó libek
_syslibs=(
    flac
    icu
    libdrm
    libevent
    libjpeg
    libpng
    libwebp
)

outdir="../object"

# Allow building against system libraries in official builds
sed -i 's/OFFICIAL_BUILD/GOOGLE_CHROME_BUILD/' tools/generate_shim_headers/generate_shim_headers.py

# external usb.ids (hwdata)
sed "s|//third_party/usb_ids/usb.ids|/usr/share/hwdata/usb.ids|g" -i services/device/public/cpp/usb/BUILD.gn

python3 build/linux/unbundle/replace_gn_files.py --system-libraries "${_syslibs[@]}"

# node
mkdir -p third_party/node/linux/node-linux-x64/bin
ln -s /usr/bin/node third_party/node/linux/node-linux-x64/bin/node

# gn a buildhoz
# tools/gn/bootstrap/bootstrap.py --build-path=$outdir --gn-gen-args=" ${_flags[@]} "

# extra flags
export LDFLAGS+="-Wl,-rpath,/usr/lib/chromium/ -Wl,--no-keep-memory"

# build options: az --args utáni sorok nem kezdődhetnek tab karakterrel!
# $outdir/gn gen $outdir -v --args=" ${_flags[@]} " --script-executable=/usr/bin/python3
gn gen $outdir -v --args=" ${_flags[@]} " --script-executable=/usr/bin/python3

# gn args list - kihagyható, de segít a lehetséges opciók megadásához
# $outdir/gn args --list $UB_COMPILEDIR/$outdir > $UB_COMPILEDIR/$outdir/gn-args-full.list
gn args --list $outdir > $outdir/gn-args-full.list

# ninja
LC_ALL=C ninja -j $jobs -C $outdir -v pdf chrome chrome_sandbox chromedriver.unstripped
