#!/bin/sh -eux

if [ $((`stat -f -c "%a" .`*`stat -f -c "%s" .`/(1024*1024*1024))) -lt 7 ]; then
	echo "At least 7 GB free space is required!"
	exit 1
fi

if [ "$UB_ARCH" == "amd64" ];then
# export CC="x86_64-gnu-linux-gcc"
# export CXX="x86_64-gnu-linux-g++"
# export AR="ar"
# export NM="nm"
cpu="x64"
else
# export CC="i686-gnu-linux-gcc"
# export CXX="i686-gnu-linux-g++"
# export AR="ar"
# export NM="nm"
cpu="x86"
fi

# -Drelease_extra_cflags=" -fno-delete-null-pointer-checks"
# -Dcomponent="shared_library" -> is_component_build=true

_google_api_key=AIzaSyDwr302FpOSkGRpLlUpPThNTDPbXcIn_FM
_google_default_client_id=413772536636.apps.googleusercontent.com
_google_default_client_secret=0ZChLK6AxeA3Isu96MkwqDR4

# host_toolchain=\"//build/toolchain/linux/unbundle:host\"
# v8_snapshot_toolchain=\"//build/toolchain/linux/unbundle:host\"
# clang_base_path=\"/usr\"

_flags=("
host_cpu=\"${cpu}\"
target_cpu=\"${cpu}\"
is_debug=false
is_clang=false
clang_use_chrome_plugins=false
linux_use_bundled_binutils=false
fatal_linker_warnings=false
treat_warnings_as_errors=false
fieldtrial_testing_like_official_build=false
use_sysroot=false
use_gold=false
use_allocator=\"none\"
enable_nacl=false
enable_nacl_nonsfi=false
enable_swiftshader=true
enable_widevine=false
enable_hangout_services_extension=false
ffmpeg_branding=\"Chrome\"
proprietary_codecs=true
remove_webcore_debug_symbols=true
google_api_key=\"${_google_api_key}\"
google_default_client_id=\"${_google_default_client_id}\"
google_default_client_secret=\"${_google_default_client_secret}\"
use_cups=true
use_custom_libcxx=false
use_gio=false
use_gnome_keyring=false
use_gtk3=true
use_kerberos=false
use_pulseaudio=true
link_pulseaudio=true
")

# a chromium szeret patkolt, nem kiadott libeket használni
# (libjpeg, libpng, libvpx, libwebp, libxml, libevent, zlib stb.)
# csak ezeket érdemes használni a rendszerből
_syslibs=(
	flac
	yasm
)

# external usb.ids (hwdata)
sed "s|//third_party/usb_ids/usb.ids|/usr/share/hwdata/usb.ids|g" -i device/usb/BUILD.gn

build/linux/unbundle/replace_gn_files.py --system-libraries "${_syslibs[@]}"

# node
mkdir -p third_party/node/linux/node-linux-x64/bin
ln -s /usr/bin/node third_party/node/linux/node-linux-x64/bin/node

# others
third_party/libaddressinput/chromium/tools/update-strings.py

# gn a buildhoz
tools/gn/bootstrap/bootstrap.py -v --no-clean --no-rebuild

# extra flags
export LDFLAGS+="-Wl,-rpath,/usr/lib/chromium/ -Wl,--no-keep-memory"

# build options: az --args utáni sorok nem kezdődhetnek tab karakterrel!
out/Release/gn gen out/Release -v --script-executable=/usr/bin/python2 \
	--args=" ${_flags[@]} "

# gn args list - kihagyható, de segít a lehetséges opciók megadásához
# out/Release/gn args --list $UB_COMPILEDIR/out/Release

# ninja
LC_ALL=C ninja -j 2 -C out/Release -v pdf chrome chrome_sandbox chromedriver
