#!/bin/sh -eux

# mkdir -p "$UB_INSTALLDIR"/usr/lib/chromium
mkdir -p "$UB_INSTALLDIR"/usr/lib/chromium/swiftshader

outdir="../object"

mv $outdir/chrome "$UB_INSTALLDIR"/usr/lib/chromium/
mv $outdir/chromedriver "$UB_INSTALLDIR"/usr/lib/chromium/
mv $outdir/chrome_sandbox "$UB_INSTALLDIR"/usr/lib/chromium/chrome-sandbox
mv $outdir/crashpad_handler "$UB_INSTALLDIR"/usr/lib/chromium/crashpad_handler
# mv $outdir/chrome.1 "$UB_INSTALLDIR"/usr/share/man/man1/chrome.1

mv $outdir/*.pak "$UB_INSTALLDIR"/usr/lib/chromium/
mv $outdir/*.bin "$UB_INSTALLDIR"/usr/lib/chromium/

mv $outdir/libEGL.so "$UB_INSTALLDIR"/usr/lib/chromium/
mv $outdir/libGLESv2.so "$UB_INSTALLDIR"/usr/lib/chromium/

mv $outdir/swiftshader/*.so "$UB_INSTALLDIR"/usr/lib/chromium/swiftshader/

if [ -f $outdir/icudtl.dat ]; then
mv $outdir/icudtl.dat "$UB_INSTALLDIR"/usr/lib/chromium/
fi

mkdir -p "$UB_INSTALLDIR"/usr/lib/chromium/locales
mv $outdir/locales/*.pak "$UB_INSTALLDIR"/usr/lib/chromium/locales/

for size in 16 24 32 48 64 128 256; do
	mkdir -p ${UB_INSTALLDIR}/usr/share/icons/hicolor/${size}x${size}/apps/
	case ${size} in
	    16|32) iconpath="chrome/app/theme/default_100_percent/chromium" ;;
	    *) iconpath="chrome/app/theme/chromium" ;;
	esac
	cp ${iconpath}/product_logo_$size.png ${UB_INSTALLDIR}/usr/share/icons/hicolor/${size}x${size}/apps/chromium.png
done

ln -s /usr/lib/chromium/chromedriver "$UB_INSTALLDIR"/usr/bin/chromedriver
