#!/bin/sh -eux
mv opt usr/lib
cp -r etc ${UB_INSTALLDIR}/
cp -r usr/lib ${UB_INSTALLDIR}/usr/
cp -r usr/share ${UB_INSTALLDIR}/usr/
ln -s ${UB_INSTALLDIR}/usr/lib/google/chrome/google-chrome ${UB_INSTALLDIR}/usr/bin/google-chrome-stable
for size in 16 24 32 48 64 128 256; do
	mkdir -p ${UB_INSTALLDIR}/usr/share/icons/hicolor/${size}x${size}/apps/
	case ${size} in
	    16|32) iconpath=${UB_INSTALLDIR}/usr/lib/google/chrome ;;
	esac
	cp ${iconpath}/product_logo_$size.png ${UB_INSTALLDIR}/usr/share/icons/hicolor/${size}x${size}/apps/google-chrome.png
done
