#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR/usr/share/fonts/truetype"
cp -a ukai/ukai.ttc "$UB_INSTALLDIR/usr/share/fonts/truetype"
cp -a ukai/fonts.dir "$UB_INSTALLDIR/usr/share/fonts/truetype/fonts.dir.ukai"
cp -a uming/uming.ttc "$UB_INSTALLDIR/usr/share/fonts/truetype"
cp -a uming/fonts.dir "$UB_INSTALLDIR/usr/share/fonts/truetype/fonts.dir.uming"
