#!/bin/sh -eux

ub_install

cp 06/stereo/desktop-login.ogg $UB_INSTALLDIR/usr/share/sounds/freedesktop/stereo/desktop-login.oga
cp 06/stereo/desktop-logout.ogg $UB_INSTALLDIR/usr/share/sounds/freedesktop/stereo/desktop-logout.oga
cp 06/stereo/system-ready.ogg $UB_INSTALLDIR/usr/share/sounds/freedesktop/stereo/system-ready.oga
