#!/bin/sh -eux

ub_install

# sources.list
DIST=${UB_DISTRIBUTION##* } # remove "UHU-Linux "
DIST=${DIST,,} # convert to lowercase

cat > "$UB_INSTALLDIR"/etc/apt/sources.list <<END
# /etc/apt/sources.list

deb http://download.ubk.hu/pkg/$DIST/main/amd64 ./
deb http://quantum-mirror.hu/mirrors/pub/ubk/pkg/$DIST/main/amd64 ./

END
