#!/bin/sh -eux

ub_compile \
	--libdir=/lib \
	--sbindir=/sbin \
	--enable-udev_sync \
	--enable-udev_rules \
	--enable-cmdlib \
	--enable-fsadm \
	--enable-dmeventd \
	--enable-lvmpolld \
	--enable-pkgconfig \
	--with-cache=internal \
	--with-thin=internal
