#!/bin/sh -eux

tar xvf transgui-${UB_VERSION}-x86_64-linux.txz
cp transgui "$UB_INSTALLDIR"/usr/bin/
mkdir -p "$UB_INSTALLDIR"/usr/share/transgui/lang
cp lang/transgui.* "$UB_INSTALLDIR"/usr/share/transgui/lang/
rm "${UB_INSTALLDIR}/usr/share/transgui/lang/transgui.template"
cp transgui.png "$UB_INSTALLDIR"/usr/share/pixmaps/
