#!/bin/sh -eux

cp units/transgui "$UB_INSTALLDIR"/usr/bin/
mkdir -p "$UB_INSTALLDIR"/usr/share/transgui/lang
cp lang/transgui.* "$UB_INSTALLDIR"/usr/share/transgui/lang/
rm "${UB_INSTALLDIR}/usr/share/transgui/lang/transgui.template"
cp transgui.png "$UB_INSTALLDIR"/usr/share/pixmaps/transgui.png
