#!/bin/sh -eux

ub_install

mkdir -p "$UB_INSTALLDIR"/usr/share/transgui/lang
cp lang/transgui.* "$UB_INSTALLDIR"/usr/share/transgui/lang/
cp transgui.png "$UB_INSTALLDIR"/usr/share/pixmaps/transgui.png
