#!/bin/sh -eux

ub_compile \
    -Dgtk=false

ub_install

cd plugins

rm -f meson.build
export AUDACIOUS_CFLAGS=-I$UB_INSTALLDIR/usr/include
export AUDACIOUS_LIBS="-L$UB_INSTALLDIR/usr/lib -laudcore"
sed -i -e "s#^plugindir=.*#plugindir=/usr/lib/audacious#" configure{,.ac}
ub_compile \
	--enable-aac \
	--disable-gtk
