#!/bin/sh -eux

ub_compile \
    -Dgtk=false

ub_install

cd plugins

export PKG_CONFIG_PATH="$UB_INSTALLDIR/usr/lib/pkgconfig"
export CPPFLAGS="-I$UB_INSTALLDIR/usr/include"
export LIBRARY_PATH="$UB_INSTALLDIR/usr/lib"
ub_compile \
	-Daac=true \
	-Dgtk=false
