#!/bin/sh -eux

export CXXFLAGS+=' -DU_USING_ICU_NAMESPACE=1'

ub_compile \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DWL_INSTALL_BASEDIR=/usr \
    -DWL_INSTALL_DATADIR=/usr/share/widelands \
    -DOPTION_BUILD_WEBSITE_TOOLS=OFF
