#!/bin/sh -eux

ub_install
mv ${UB_INSTALLDIR}/usr/{widelands,wl_map_object_info,wl_render_richtext,wl_map_info} ${UB_INSTALLDIR}/usr/bin/
rm -r "$UB_INSTALLDIR"/usr/{ChangeLog,COPYING,CREDITS,VERSION}
