.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH CREAM 1 "Oct 25, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
cream \- a set of macros that makes the VIM easier to use for beginners
.SH SYNOPSIS
.B cream
[ any VIM options ]
.SH DESCRIPTION
.B cream
is a set of macros for the popular VIM editor that makes it a lot more
intuitive to beginners. Cream is useful for users who want to take advantage
of the great VIM features but don't know how to control them (yet).
.PP
Please note that due to limitation to text consoles/terminals cream can
only run in X11.
.SH OPTIONS
You can provide any options from the VIM manpage. See there.
.SH SEE ALSO
vim(1)
.SH AUTHORS
The original program was written by Steve Hall <digitect@mindspring.com> and
others. This manual page was provided by Christoph Haas
<email@christoph\-haas.de> for the Debian GNU/Linux system
but may freely be used by anyone.

