#!/bin/sh -eux

ub_install

mv "$UB_INSTALLDIR"/usr/bin/chroot "$UB_INSTALLDIR"/usr/sbin/
mv "$UB_INSTALLDIR"/usr/share/man/man1/chroot.1 "$UB_INSTALLDIR"/usr/share/man/man8/chroot.8

# usleep symlink
ln -s sleep "$UB_INSTALLDIR"/bin/usleep
