#!/bin/sh -eux

gnome-autogen.sh --prefix=/usr --localstatedir=/var --libexecdir=/usr/lib/pix -disable-static
ub_configure
echo '#dummy' >pix/.deps/oauth_test-gsignature.Po
echo '#dummy' >pix/.deps/glib_utils_test-glib-utils.Po
echo '#dummy' >pix/.deps/gsignature_test-gsignature.Po
echo '#dummy' >pix/.deps/dom_test-dom.Po
ub_make
