diff -Naur femon-2.4.0-orig/Makefile femon-2.4.0/Makefile
--- femon-2.4.0-orig/Makefile	2018-04-15 20:30:39.000000000 +0200
+++ femon-2.4.0/Makefile	2019-10-05 18:52:24.478777150 +0200
@@ -27,7 +27,7 @@
 
 export CFLAGS   = $(call PKGCFG,cflags)
 export CXXFLAGS = $(call PKGCFG,cxxflags)
-STRIP           ?= /bin/true
+STRIP           ?= /usr/bin/true
 
 ### The version number of VDR's plugin API:
 
