#!/bin/sh

# csatolási hitelesítők

# lxde
#/usr/libexec/lxpolkit &

# mate
#/usr/libexec/polkit-mate-authentication-agent-1 &

# gnome
#/usr/libexec/polkit-gnome-authentication-agent-1 &

# kde
#/usr/lib/libexec/polkit-kde-authentication-agent-1 &
