#!/bin/sh -eux

ub_compile \
	--enable-cxx \
	--build=x86_64-pc-linux-gnu

# Quoting the homepage:
# "GMP is very often miscompiled! We are seeing ever increasing problems
# with mis-compilations of the GMP code. Please never use your newly
# compiled libgmp.a or libgmp.so without first running make check."
make check
