#!/bin/sh -eux

ub_compile \
    -Denable-fwupd=false \
    -Denable-flatpak=false \
    -Denable-ostree=false \
    -Denable-ubuntu-reviews=false \
    -Denable-odrs=false \
    -Denable-gtk-doc=false
