#!/bin/sh -eux

export CTARGET="x86_64-gnu-linux"
export CHOST="x86_64-gnu-linux"
export CBUILD="x86_64-gnu-linux"

cd build/workspaces
./update-workspaces.sh \
	--bindir=/usr/bin \
    --libdir=/usr/lib/0ad \
    --datadir=/usr/share/0ad/data

cd gcc
ub_make
