#!/bin/sh -eux

cd build/workspaces
./update-workspaces.sh \
	--bindir=/usr/bin \
    --libdir=/usr/lib/0ad \
    --datadir=/usr/share/0ad/data \
    --without-pch \
    --without-tests \

cd gcc
ub_make
