#!/bin/sh -eux

install -d $UB_INSTALLDIR/usr/{lib/0ad,share/0ad/data}
install -Dm755 binaries/system/pyrogenesis $UB_INSTALLDIR/usr/bin
install -Dm755 binaries/system/*.so $UB_INSTALLDIR/usr/lib/0ad/
install -Dm755 build/resources/0ad.sh $UB_INSTALLDIR/usr/bin/0ad
install -Dm644 build/resources/0ad.desktop $UB_INSTALLDIR/usr/share/applications/0ad.desktop
install -Dm644 build/resources/0ad.png $UB_INSTALLDIR/usr/share/pixmaps/0ad.png

cp -r binaries/data/ $UB_INSTALLDIR/usr/share/0ad/
