#!/bin/sh -eux

export LDADD+=`pkg-config --libs-only-l openssl`

ub_compile \
	--libdir=/etc \
	--enable-nls \
	--with-screen=ncursesw \
	--with-ssl=/usr/lib \
	--enable-cgi-links \
	--enable-color-style \
	--enable-externs \
	--enable-file-upload \
	--enable-included-msgs \
	--enable-ipv6 \
	--enable-nested-tables \
	--enable-nsl-fork \
	--enable-persistent-cookies \
	--enable-prettysrc \
	--enable-read-eta \
	--enable-scrollbar
