#!/bin/sh -eux

export UB_MAKE_PROCS=2

sh Configure -des \
	-Dprefix="/usr"              \
	-Dvendorprefix="/usr"        \
	-Dsiteprefix="/usr"          \
	-Dman3ext="3pm"              \
	-Dcf_by="UHU Linux"          \
	-Dmyhostname="localhost"     \
	-Dperladmin="root@localhost" \
	-Ud_csh                      \
	-Duseshrplib                 \
	-Dusethreads                 \
	-Duse64bitint                \
	-Dusemorebits				 \
	-Dccdlflags='-fPIC'			 \
	-Darchname=x64-linux

make
make test-notty
