#!/bin/sh -eux

# note: --with-tcsetpgrp is required when building without a controlling
# terminal (e.g. running a full rebuild in our build system)

# Remove unneeded and conflicting completion scripts
for _fpath in AIX BSD Cygwin Darwin Debian Mandriva openSUSE Redhat Solaris; do
	rm -rf Completion/$_fpath
	sed "s#\s*Completion/$_fpath/\*/\*##g" -i Src/Zle/complete.mdd
done
rm Completion/Linux/Command/_{pkgtool,rpmbuild}

ub_compile \
	--with-tcsetpgrp \
	--bindir=/usr/bin \
	--sbindir=/usr/sbin \
	--enable-etcdir=/etc/zsh \
	--enable-zshenv=/etc/zsh/zshenv \
	--enable-zlogin=/etc/zsh/zlogin \
	--enable-zlogout=/etc/zsh/zlogout \
	--enable-zprofile=/etc/zsh/zprofile \
	--enable-zshrc=/etc/zsh/zshrc \
	--enable-maildir-support \
	--with-term-lib='ncursesw' \
	--enable-multibyte \
	--enable-function-subdirs \
	--enable-fndir=/usr/share/zsh/functions \
	--enable-scriptdir=/usr/share/zsh/scripts \
	--with-tcsetpgrp \
	--enable-pcre \
	--enable-cap \
	--enable-zsh-secure-free
