#!/bin/sh -eux

ub_install
mv -f "$UB_INSTALLDIR"/usr/bin/ctags "$UB_INSTALLDIR"/usr/bin/ctags-emacs
rm "$UB_INSTALLDIR"/usr/share/man/man1/ctags.1.gz
cp -a etc/images/icons/hicolor/48x48/apps/emacs.png "$UB_INSTALLDIR"/usr/share/pixmaps/emacs.png
rm "$UB_INSTALLDIR"/usr/share/info/info.info.gz
rm -rf ${UB_INSTALLDIR}/usr/include
