#!/bin/sh -eux

NO_BIN_LINK=1 ub_install
cp -a etc/images/icons/hicolor/48x48/apps/emacs.png "$UB_INSTALLDIR"/usr/share/pixmaps/emacs.png
rm "$UB_INSTALLDIR"/usr/share/info/info.info.gz
rm -rf ${UB_INSTALLDIR}/usr/include
