#!/bin/sh -eux

make DIST_ROOT="$UB_INSTALLDIR" PKG_ROOT_SBIN_DIR="/usr/bin" PKG_ROOT_LIB_DIR="/usr/lib" install
make DIST_ROOT="$UB_INSTALLDIR" PKG_ROOT_SBIN_DIR="/usr/bin" PKG_ROOT_LIB_DIR="/usr/lib" install-dev
