#!/bin/sh -eux

mkdir build
cd build
UB_CONFIGURE_DIR=../ ub_configure \
	--disable-native-texlive-build \
	--with-banner-add=/UHU-Linux \
	--with-system-cairo \
	--with-system-fontconfig \
	--with-system-freetype2 \
	--with-system-gmp \
	--with-system-graphite2 \
	--with-system-harfbuzz \
	--with-system-gd \
	--with-system-icu \
	--with-system-libgs \
	--with-system-libpng \
	--with-system-mpfr \
	--with-system-pixman \
	--with-system-poppler \
	--with-system-xpdf \
	--with-system-zlib \
	--with-system-zziplib \
	--with-x \
	--enable-luatex \
	--disable-psutils \
	--disable-t1utils

ub_make
