#!/bin/sh -eux

export GUILE=/usr/bin/guile1.8
export GUILE_CONFIG=/usr/bin/guile-config1.8
export LDFLAGS=" -lpthread "
export LDFLAGS+=$(pkg-config --libs gio-2.0)
ub_compile \
	--disable-documentation
