#!/bin/sh -eux

export GUILE=/usr/bin/guile2.2
export GUILE_CONFIG=/usr/bin/guile-config2.2
export LDFLAGS=" -lpthread "
export LDFLAGS+=$(pkg-config --libs gio-2.0)
ub_compile \
	--with-texgyre-dir=$UB_COMPILEDIR/tex-gyre/opentype \
	--enable-guile2 \
	--disable-documentation
