#!/bin/sh -eux

# git submodule init
# git config --local submodule.bsdiff.url bsdiff
# git config --local submodule.libglnx.url libglnx
# git submodule update

git clone https://gitlab.gnome.org/GNOME/libglnx.git
git clone https://github.com/mendsley/bsdiff.git

NOCONFIGURE=1 ./autogen.sh
ub_compile \
	--with-curl \
	--without-soup
