#!/bin/sh -eux

ub_compile \
	-Dbuildtype=release \
	-Degl_device=true \
	-Dtests=false \
	-Dinstalled_tests=false \
	-Dnative_tests=false \
	-Dcore_tests=false \
	-Dclutter_tests=false \
	-Dcogl_tests=false \
