#!/bin/sh -eux

sed -i -e "s|^#\!.*/usr/bin/env python|#!/usr/bin/env python3|" setuptools/command/easy_install.py

export SETUPTOOLS_INSTALL_WINDOWS_SPECIFIC_FILES=0
export SETUPTOOLS_SCM_PRETEND_VERSION=$UB_VERSION
ub_compile
