diff -Naur orig/Makefile mod/Makefile
--- orig/Makefile	2015-12-04 15:37:32.000000000 +0100
+++ mod/Makefile	2016-02-20 16:23:02.653628909 +0100
@@ -1,10 +1,6 @@
 CC	 = gcc
 CFLAGS	 = -g -Wall -Wno-pointer-sign -O2 -fomit-frame-pointer
 
-GIT2LOG := $(shell if [ -x ./git2log ] ; then echo ./git2log --update ; else echo true ; fi)
-GITDEPS := $(shell [ -d .git ] && echo .git/HEAD .git/refs/heads .git/refs/tags)
-VERSION := $(shell $(GIT2LOG) --version VERSION ; cat VERSION)
-BRANCH  := $(shell git branch | perl -ne 'print $$_ if s/^\*\s*//')
 PREFIX  := gfxboot-$(VERSION)
 
 # THEMES	 = $(wildcard themes/*)
@@ -12,10 +8,7 @@
 
 .PHONY: all clean distclean doc install installsrc themes
 
-all:	changelog bin2c gfxboot-compile bincode gfxboot-font addblack
-
-changelog: $(GITDEPS)
-	$(GIT2LOG) --changelog changelog
+all:	bin2c gfxboot-compile bincode gfxboot-font addblack
 
 gfxboot-font: gfxboot-font.c
 	$(CC) $(CFLAGS) -I /usr/include/freetype2 -lfreetype $< -o $@
