#!/bin/sh -eux

ub_install

ln -sf gzip "$UB_INSTALLDIR"/usr/bin/compress
ln -sf gzip "$UB_INSTALLDIR"/usr/bin/gunzip
ln -sf gzip "$UB_INSTALLDIR"/usr/bin/uncompress
ln -sf gzip "$UB_INSTALLDIR"/usr/bin/zcat

ln -sf zcmp "$UB_INSTALLDIR"/usr/bin/zdiff
ln -sf zgrep "$UB_INSTALLDIR"/usr/bin/zegrep
ln -sf zgrep "$UB_INSTALLDIR"/usr/bin/zfgrep
