#!/bin/sh -eux

for i in *; do
	cd $i
	ub_install
	cd ..
done

# dev fájlok nem kellenek
rm -Rf "$UB_INSTALLDIR"/usr/include
rm -Rf "$UB_INSTALLDIR"/usr/lib/cmake
rm -Rf "$UB_INSTALLDIR"/usr/lib/libpala
