diff -Naur orig/Makefile patched/Makefile
--- orig/Makefile	2004-10-01 23:05:44.000000000 +0200
+++ patched/Makefile	2019-06-20 04:33:35.882271736 +0200
@@ -33,11 +33,11 @@
 # possible. This definition is ok for gcc; if your compiler has
 # problems, comment this out.
 #
-INLINEDEF=-DINLINE_DRAWPIX
+# INLINEDEF=-DINLINE_DRAWPIX
 
 # dest for make install
 #
-PREFIX=/usr/local
+PREFIX=/usr
 BINDIR=$(PREFIX)/bin
 XBINDIR=$(BINDIR)
 MANDIR=$(PREFIX)/man/man1
