#!/bin/sh -eux

ub_install
# lrzsz csomaggal ütköző lrz nevű cuccok átnevezése
mv ${UB_INSTALLDIR}/usr/bin/lrz ${UB_INSTALLDIR}/usr/bin/lrzz
mv ${UB_INSTALLDIR}/usr/share/man/man1/lrz.1 ${UB_INSTALLDIR}/usr/share/man/man1/lrzz.1
