#!/bin/sh -eux

git submodule update --init

mkdir -p build
export CFLAGS+=" -I/usr/include/openssl-1.0"
export CPPFLAGS+=" -I/usr/include/openssl-1.0"
export LDFLAGS+=" -L/usr/lib/openssl-1.0"
export CXXFLAGS+=" -I/usr/include/openssl-1.0"

cd build
cmake \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_TYPE=Release \
..

ub_make
