#!/bin/sh -eux

cd py2
python setup.py install -O1 --skip-build --root "$UB_INSTALLDIR" --prefix=/usr
cd ../py3
python3 setup.py install -O1 --skip-build --root "$UB_INSTALLDIR" --prefix=/usr
mkdir -p $UB_INSTALLDIR/usr/share/doc/Packages/python3-matplotlib
cp -r LICENSE README.rst $UB_INSTALLDIR/usr/share/doc/Packages/python3-matplotlib/
cp -r LICENSE README.rst ../
