#!/bin/sh -eux

make DESTDIR=${UB_INSTALLDIR} install

# libglvnd ütközés
rm -f "$UB_INSTALLDIR"/usr/lib/libGLESv*
# indirect rendering
ln -s /usr/lib/libGLX_mesa.so.0 ${UB_INSTALLDIR}/usr/lib/libGLX_indirect.so.0

mkdir -p "$UB_INSTALLDIR"/usr/lib/xorg/modules/extensions
ln -s libglx.so.xorg "$UB_INSTALLDIR"/usr/lib/xorg/modules/extensions/libglx.so
rm -f "$UB_INSTALLDIR"/usr/include/GL/{glew,glxew,wglew}.h
