#!/bin/sh -eux

ub_install

# indirect rendering
ln -s /usr/lib/libGLX_mesa.so.0 ${UB_INSTALLDIR}/usr/lib/libGLX_indirect.so.0

mkdir -p "$UB_INSTALLDIR"/usr/lib/xorg/modules/extensions
ln -s libglx.so.xorg "$UB_INSTALLDIR"/usr/lib/xorg/modules/extensions/libglx.so
