#!/bin/sh -eux

V=${UB_VERSION_HEAD2}
R=${UB_VERSION}

make \
    MYCFLAGS="-fPIC" \
    TO_BIN="lua${R} luac${R}" \
    TO_LIB="liblua${R}.a liblua${R}.so liblua${R}.so.${R} liblua${R}.so.$R" \
linux
