#!/bin/bash -eux

if [ "$UB_ARCH" == "amd64" ];then
	KVER="$(ls -1 /lib/modules | grep x86_64)"
else
	KVER="$(ls -1 /lib/modules | grep i386)"
fi

#célkönyvtárak
cellibdir="$UB_INSTALLDIR"/usr/lib
moduldir="$cellibdir"/modules/"$KVER"/kernel/drivers
xmoduldir="$cellibdir"/xorg/modules
sharedir="$UB_INSTALLDIR"/usr/share
desktopdir="$sharedir"/applications
mandir="$sharedir"/man/man1
vendordir="$UB_INSTALLDIR"/etc/OpenCL/vendors
pixmapdir="$sharedir"/pixmaps/
egldir="$sharedir"/egl/egl_external_platform.d
vulcandir="$sharedir"/vulcan/icd.d
xconfdir="$sharedir"/X11/x.org.conf.d

#könyvtárgyártás
mkdir -p "$cellibdir"/nvidia \
	"$moduldir" \
	"$xmoduldir"/{drivers,extensions} \
	"$desktopdir" \
	"$mandir" \
	"$vendordir" \
	"$pixmapdir" \
	"$egldir" \
	"$vulcandir" \
	"$xconfdir"

#kernelmodulok
cp kernel/*.ko "$moduldir"/

# binárisok
mv	nvidia-xconfig \
	nvidia-settings \
	nvidia-bug-report.sh \
	nvidia-smi \
	nvidia-cuda-mps-server \
	nvidia-cuda-mps-control \
	nvidia-modprobe \
	nvidia-persistenced \
	nvidia-debugdump \
	"$UB_INSTALLDIR"/usr/bin/

# desktop
mv	nvidia-settings.desktop "$desktopdir"/
mv	nvidia-settings.png "$pixmapdir"/

# man
gunzip	*.1.gz
mv	*.1 "$mandir"/

# vendor
mv	nvidia.icd "$vendordir"/

# biztonságba helyezés a régi módon
mv	libglx.so."$UB_VERSION" "$cellibdir"/nvidia/

#Áthelyezzük a nem a $cellibdir alá kerülő *.so-kat
mv	nvidia_drv.so "$xmoduldir"/drivers/
mv	tls "$cellibdir"

#wailand, vulcan
mv 10_nvidia_wayland.json $egldir/
mv nvidia_icd.json.template $vulcandir/nvidia_icd.json

#xorg.conf.d
mv nvidia-drm-outputclass.conf $xconfdir/10-nvidia-drm-outputclass.conf

#persistenced
mv nvidia-persistenced-init/systemd/nvidia-persistenced.service.template \
    $UB_INSTALLDIR/usr/lib/systemd/system/nvidia-persistenced.service

# remove conflicting vdpau lib
###Jó nekünk az!
#rm "libvdpau.so.$UB_VERSION"
#rm "libvdpau_trace.so.$UB_VERSION"

# minden áthelyezése a libekbe
mv *.so.* "$cellibdir"/
# remove conflicting mesa lib
rm -f "$cellibdir"/libGLESv2.so.2
#linkgyártások
cd "$cellibdir"

ln -s libwfb.so xorg/modules/libnvidia-wfb.so."$UB_VERSION"
ln -s libnvidia-ml.so."$UB_VERSION" libnvidia-ml.so.1
ln -s libnvcuvid.so."$UB_VERSION" libnvcuvid.so.1
