#!/bin/sh -eux

export QTDIR=/usr/lib/qt4

python3 configure.py --confirm-license --verbose -q $QTDIR/bin/qmake -p ${UB_INSTALLDIR}/$QTDIR/plugins
ub_make
ub_install
mv ${UB_INSTALLDIR}/usr/bin/pyuic4 ${UB_INSTALLDIR}/usr/bin/pyuic4-python3

python configure.py --confirm-license --verbose -q $QTDIR/bin/qmake -s /usr/include/dbus-1.0 -p ${UB_INSTALLDIR}/$QTDIR/plugins
make clean
ub_make
