#!/bin/sh -eux

python setup.py install --root="$UB_INSTALLDIR"

python3 setup.py install --root="$UB_INSTALLDIR"

pkgname=python3-markupsafe
doksik="AUTHORS LICENSE README.rst"

py3docdir=$UB_INSTALLDIR/usr/share/doc/Packages/$pkgname
mkdir -p $py3docdir

cp $doksik $py3docdir/
