#!/bin/sh -eux

ub_compile \
	--enable-console-helper=no \
	--enable-authentication-scheme=pam \
	--enable-profiling \
	--with-dmconfdir=/usr/share/xsessions \
	--with-initial-vt=7 \
	--with-user=gdm \
	--with-group=gdm \
	--without-tcp-wrappers \
	--without-plymouth \
	--without-seelinux
