#!/bin/sh -eux

autoreconf -vif
intltoolize --force
ub_compile \
    --enable-gui                \
    --enable-drm                \
    --enable-randr              \
    --enable-vidmode            \
    --enable-geoclue2
