#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR"/usr/share/pixmaps

cp -a . -- "$UB_INSTALLDIR"/usr/share/SweetHome3D/
ln -s ../share/SweetHome3D/runtime/lib/amd64/jli/libjli.so \
"$UB_INSTALLDIR"/usr/lib/libjli.so
cp SweetHome3DIcon.png "$UB_INSTALLDIR"/usr/share/pixmaps/
cp COPYING.TXT LICENSE.TXT ../
