#!/bin/sh -eux

ub_install

ln -s bash "$UB_INSTALLDIR"/bin/sh
ln -s ../../bin/bash "$UB_INSTALLDIR"/usr/bin/bash
ln -s ../../bin/bash "$UB_INSTALLDIR"/usr/bin/sh
ln -s bash.1 "$UB_INSTALLDIR"/usr/share/man/man1/sh.1
