#!/bin/sh -eux

ub_install

cd gnucash-docs
ub_install

rm -Rf "$UB_INSTALLDIR"/usr/include
rm -Rf "$UB_INSTALLDIR"/usr/lib/gnucash/scm
rm -Rf "$UB_INSTALLDIR"/usr/libexec/gnucash/src
rm -Rf "$UB_INSTALLDIR"/usr/share/doc
rm -Rf "$UB_INSTALLDIR"/usr/share/gnucash-docs

rm -Rf "$UB_INSTALLDIR"/usr/share/gnome/help/gnucash-help/{it,pt}
rm -Rf "$UB_INSTALLDIR"/usr/share/gnome/help/gnucash-guide/{it,ja,pt,ru}
