#!/bin/sh -eux

ub_install

# Install python modules
cd build
_pythonpath=`python -c "from sysconfig import get_path; print(get_path('platlib'))"`
install -Dm755 python3*/*.so -t "$UB_INSTALLDIR"/$_pythonpath
chrpath -d "$UB_INSTALLDIR"/$_pythonpath/*.so # Remove insecure RPATH

# FHS tiltott mappa eltávilítás
rm -rf "$UB_INSTALLDIR"/usr/sr

# nem kell pdf doksitömeg.
rm -rf ${UB_INSTALLDIR}/usr/share/doc/OpenEXR-${UB_VERSION}
