#!/bin/sh -eux

cp ${UB_SRCDIR}/patches/config.sub.skip  config.sub
cp ${UB_SRCDIR}/patches/config.guess.skip  config.guess
export CXXFLAGS+="-fPIC"
export CFLAGS+='-fPIC'
export LDFLAGS+='-fPIC'
ub_compile
