diff -urN zoo-2.10.orig/makefile zoo-2.10/makefile
--- zoo-2.10.orig/makefile	1991-07-05 18:00:00.000000000 +0200
+++ zoo-2.10/makefile	2004-02-24 16:45:17.000000000 +0100
@@ -23,8 +23,7 @@
 MODEL =
 EXTRA = -DBIG_MEM -DNDEBUG
 LINTFLAGS = -DLINT
-OPTIM = -O
-DESTDIR = /usr/local/bin
+OPTIM = -O -Wall
 
 #List of all object files created for Zoo
 ZOOOBJS = addbfcrc.o addfname.o basename.o comment.o crcdefs.o \
@@ -53,6 +52,7 @@
 	@echo "ultrix:       ULTRIX 4.1"
 	@echo "convex:       Convex C200 series"
 	@echo "sysv:         System V Release 2 or 3; or SCO Xenix"
+	@echo "linux:        Linux"
 	@echo "scodos:       Cross-compiler under SCO Xenix/UNIX for MS-DOS"
 	@echo "xenix286:     Older Xenix/286 (not tested)"
 	@echo "xenix68k:     Xenix/68000 (not tested)"
@@ -68,15 +68,15 @@
 
 # install alpha zoo as "tzoo"
 install:
-	mv zoo $(DESTDIR)/tzoo
+	mv zoo $(DESTDIR)/usr/bin/zoo
 
 # install beta zoo as "bzoo"
 inst_beta:
-	mv zoo $(DESTDIR)/bzoo
+	mv zoo $(DESTDIR)/usr/bin/bzoo
 
 # install production zoo as "zoo"
 inst_prod:
-	mv zoo $(DESTDIR)/zoo
+	mv zoo $(DESTDIR)/usr/bin/zoo
 
 # executable targets
 TARGETS = zoo fiz
@@ -94,6 +94,10 @@
 bsd:
 	$(MAKE) CFLAGS="-c $(OPTIM) -DBSD4_3" $(TARGETS)
 
+# Linux
+linux:
+	$(MAKE) CC="gcc" CFLAGS="-c $(OPTIM) $(LINTFLAGS) -DLINUX -DANSI_HDRS" $(TARGETS)
+
 # ULTRIX 4.1
 ultrix:
 	$(MAKE) CFLAGS="-c $(OPTIM) -DULTRIX" $(TARGETS)
@@ -235,7 +239,11 @@
 parse.o: zoofns.h zooio.h
 portable.o: /usr/include/stdio.h assert.h debug.h machine.h options.h
 portable.o: portable.h various.h zoo.h zoofns.h zooio.h
-prterror.o: /usr/include/stdio.h /usr/include/varargs.h options.h various.h
+
+# I deleted varags.h dependancy from prterror.o since that is a
+# dependancy covered by a #ifdef, and in Debian's case #undef'ed
+
+prterror.o: /usr/include/stdio.h options.h various.h
 prterror.o: zoofns.h zooio.h
 sysv.o: /usr/include/sys/stat.h /usr/include/sys/types.h /usr/include/time.h
 sysv.o: nixmode.i nixtime.i
