#!/bin/bash -eux

# --disable-vmmraw: disable building 32-bit guest additions iso
./configure \
	--target-arch=amd64 \
	--target-cpu=k8 \
	--with-linux="$(echo /lib/modules/*.x86_64/build/)" \
	--disable-hardening \
	--disable-java \
	--disable-docs \
	--disable-vmmraw

source ./env.sh
kmk all

cd ./out/linux.amd64/release/bin/src

ub_make \
	KERN_DIR="/usr/src/`readlink /usr/src/linux`"
