#!/bin/sh -eux

ub_install

#alap config fájlok
cp *.conf $UB_INSTALLDIR/etc/vdr/
#plugins headers
mkdir -p $UB_INSTALLDIR/usr/include/vdr/PLUGINS/pictures
cp PLUGINS/src/pictures/*.h $UB_INSTALLDIR/usr/include/vdr/PLUGINS/pictures/
