#!/bin/sh -eux

ub_compile \
    -Dfft=fftw \
    -Dresampler=libsamplerate
#    -Dextra_include_dirs="/usr/lib/jvm/java-$java_major-openjdk/include,/usr/lib/jvm/java-$java_major-openjdk/include/linux"
