#!/bin/sh -eux

./configure \
	--prefix=/usr \
	--enable-ccache \
	--enable-shared \
	--enable-postproc \
    --enable-pic \
    --enable-vp8 \
    --enable-vp9 \
    --enable-vp9-highbitdepth \
    --disable-install-docs \
    --disable-install-srcs \
    --enable-ssse3 \
    --disable-optimizations
ub_make
