#!/bin/sh -eux

cd "$UB_OBJECTDIR"
ub_install

rm -f "$UB_INSTALLDIR"/usr/lib/*.ajs

# remove execution bit from headers and pkgconfig file
find "$UB_INSTALLDIR"/usr/include -type f -exec chmod a-x {} \;
chmod a-x  "$UB_INSTALLDIR"/usr/lib/pkgconfig/*.pc
