#!/bin/sh -eux

function build () {
cp d${1}x-rebirth/d${1}x-rebirth.desktop ./
cp d${1}x-rebirth/d${1}x-rebirth.xpm ./
scons \
	sharepath=/usr/share/games/d${1}x \
	prefix=/usr \
	lto=1 \
	sdl2=1 \
	sdlmixer=1 \
	ipv6=1 \
	opengl=1 \
	use_tracker=1 \
	screenshot=png \
	builddir=build/main/ \
	d${1}x=1
}

build 1
build 2
