#!/bin/sh -eux

mv build/main/d{1,2}x-rebirth/d*x-rebirth "$UB_INSTALLDIR"/usr/bin/
mkdir -p "$UB_INSTALLDIR"/usr/share/{doc/Packages/{d1x-rebirth,d2x-rebirth},applications,pixmaps,games/d{1,2}x}
rm d2shar10/*.{bat,exe,lst,386,txt}
rm desc14sw/*.{ubn,bat,exe,386,txt}
cp -a d2shar10/. "$UB_INSTALLDIR"/usr/share/games/d2x/
cp -a desc14sw/. "$UB_INSTALLDIR"/usr/share/games/d1x/
cp d2xaddons/"d2x-rebirth addons"/d2xr-sc55-music.dxa "$UB_INSTALLDIR"/usr/share/games/d2x/
cp d1xaddons/"d1x-rebirth addons"/d1xr-sc55-music.dxa "$UB_INSTALLDIR"/usr/share/games/d1x/
cp d{1,2}x-rebirth.desktop $UB_INSTALLDIR/usr/share/applications/
cp d{1,2}x-rebirth.xpm $UB_INSTALLDIR/usr/share/pixmaps/
cp COPYING.txt GPL-3.txt "$UB_INSTALLDIR"/usr/share/doc/Packages/d1x-rebirth/
cp COPYING.txt GPL-3.txt "$UB_INSTALLDIR"/usr/share/doc/Packages/d2x-rebirth/
