#!/bin/sh -eux

celdir="$UB_INSTALLDIR"/usr/share/games/quake2/baseq2
mkdir -p $celdir/players/{female,male}
cp Install/Data/baseq2/players/female/doomgal* "$celdir"/players/female/
cp Install/Data/baseq2/players/male/skin.pcx "$celdir"/players/male/
cp Install/Data/baseq2/pak0.pak "$celdir"/
