#!/bin/sh -eux

ub_install
ub_install -C modules/pam_envfeed
ub_install -C modules/pam_locallogin

rm "$UB_INSTALLDIR"/lib/security/pam_*.la

for i in modules/pam_*/README; do
	j="${i#modules/pam_}"
	j="${j%/README}"
	cp -a "$i" "$UB_INSTALLDIR"/usr/share/doc/Packages/pam/README."$j"
done

ln -sf deny-all "$UB_INSTALLDIR"/etc/pam.d/other

# unix_chkpwd needs setuid bit, but pam 0.99.3.0 forgets to add it
chmod 4755 "$UB_INSTALLDIR"/sbin/unix_chkpwd
