#!/bin/sh -eux

rm CMakeLists.txt
ub_compile \
	--enable-ipv6 \
	--with-ssl \
	--with-libssh2 \
	--with-nghttp2 \
	--with-ca-path=/etc/ssl/certs \
	--with-ca-bundle=/etc/ssl/certs/ca-certificates.crt
