#!/bin/sh -eux

cd rtd
python setup.py install --root="$UB_INSTALLDIR"
cd ../rtd3
python3 setup.py install --root="$UB_INSTALLDIR"

py3docdir=${UB_INSTALLDIR}/usr/share/doc/Packages/python3-sphinx-rtd-theme
mkdir -p $py3docdir
cp LICENSE README.rst $py3docdir/
