#!/bin/sh -eux

ub_replace -O3 -O2 configure
# compile static lib
ub_compile \
	--prefix=/usr

# compile shared lib
./configure \
	--prefix=/usr \
	--shared
make

# minizip
cd contrib/minizip
ub_compile
