#!/bin/sh -e

shopt -s nullglob

reload_systemd () {
	[ -z "${UHU_PKG_QUIET+x}" ] && echo -n "  Reload systemd unit files ..."
	systemctl daemon-reload || :
	true > /var/lib/uhu-pkg/systemd
	while [ ! /var/lib/uhu-pkg/systemd -ot /var/lib/dpkg/info \
	     -a ! /var/lib/uhu-pkg/systemd -nt /var/lib/dpkg/info ]; do
		sleep 0.1
		true > /var/lib/uhu-pkg/systemd
	done
	[ -z "${UHU_PKG_QUIET+x}" ] && echo
}

if [ "$1" = "systemd" -o "$1" = "+" ] || grep -q '^/usr/lib/systemd/system/' /var/lib/dpkg/info/"$1".list; then
	reload_systemd
fi
