#!/bin/sh -eux

ub_install
mkdir -p ${UB_INSTALLDIR/usr/share/pixmaps
cd ${UB_INSTALLDIR}/usr/share/fluxstyle/
cp glade/*.glade images/
cp images/*.{jpg,png} glade/
cp images/fluxmetal.png ${UB_INSTALLDIR}/usr/share/pixmaps/
mv ${UB_INSTALLDIR}/usr/bin/fluxstyle_gui ${UB_INSTALLDIR}/usr/bin/fluxstyle
