#!/bin/sh -eux

ub_compile \
	--disable-docs
ub_install

export CFLAGS="-I${UB_INSTALLDIR}/usr/include"
cd drivers
ub_compile \
	--with-dbi-libdir=${UB_INSTALLDIR}/usr/lib \
	--with-mysql \
	--with-sqlite3 \
	--disable-docs
