#!/bin/sh -eux

python3 setup.py install --prefix=/usr \
    --skip-build \
    --optimize=1 \
    --root="$UB_INSTALLDIR"

# strip $UB_INSTALLDIR from embedded paths:
py_ver=$(python -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')
python3 -m compileall -d "/usr/lib/python${py_ver}" \
    "${UB_INSTALLDIR}/usr/lib/python${py_ver}"
python3 -O -m compileall -d "/usr/lib/python${py_ver}" \
    "${UB_INSTALLDIR}/usr/lib/python${py_ver}"

rm -f ${UB_INSTALLDIR}/usr/bin/*.bat
