#!/bin/sh -eux

ub_configure \
	--bindir=/usr/bin \
	--sbindir=/usr/sbin \
	--with-gnu-ld \
	--with-libcrack \
	--with-libpam \
	--without-selinux \
	--with-group-name-max-length=32

make CFLAGS=-fPIC
