#!/bin/sh -eux

ub_install

# ln -sf system-auth "$UB_INSTALLDIR"/etc/pam.d/chfn
# ln -sf system-auth "$UB_INSTALLDIR"/etc/pam.d/chsh
# ln -sf system-auth "$UB_INSTALLDIR"/etc/pam.d/login
# ln -sf system-auth "$UB_INSTALLDIR"/etc/pam.d/passwd

# getspnam comes from man-pages
find "$UB_INSTALLDIR"/usr/share/man -name getspnam.3 -delete
