#!/bin/sh -eux

ub_compile \
    -Dconnman=false \
    -Dwl-x11=false \
    -Dwl-buffer=false \
    -Dwl-desktop-shell=false \
    -Dwl-drm=false \
    -Dwl-text-input=false \
    -Dwl-weekeyboard=false \
    -Dwl-wl=false \
    -Dwl-x11=false \
	-Dconvertible=true \
	-Dpackagekit=false \
