#!/bin/sh -eux

ub_compile \
    --enable-librsvg \
    --enable-mate \
    --enable-marco \
    --enable-menu-entries \
    --enable-gsettings \
    --disable-schemas-compile \
    --enable-xi2-events
