diff -Nur orig/Makefile mod/Makefile
--- orig/Makefile	2023-11-07 17:41:56.563673686 +0100
+++ mod/Makefile	2023-11-07 17:46:53.789029828 +0100
@@ -1,5 +1,5 @@
 srcdir = .
-prefix = /usr/local
+prefix = /usr
 bindir = $(prefix)/bin
 mandir = $(prefix)/share/man
 datadir = $(prefix)/share
