#!/bin/sh -eux

cd source
make \
    DESTDIR=${UB_INSTALLDIR} \
    TILES=y \
    prefix=/usr \
    bin_prefix=bin \
    install
make \
    DESTDIR=${UB_INSTALLDIR} \
    TILES=y \
    prefix=/usr \
    bin_prefix=bin \
    install-xdg-data
make \
    DESTDIR=${UB_INSTALLDIR} \
    TILES=y \
    prefix=/usr \
    bin_prefix=bin \
    install-data
cp ../docs/crawl_manual.txt ../
