#!/bin/sh -eux

mkdir -p ${UB_INSTALLDIR}/usr/lib
mkdir -p ${UB_INSTALLDIR}/usr/include/fmodex
# csak 64 bites kell
cp -d api/lib/libfmodex64* "$UB_INSTALLDIR"/usr/lib/
cp -d api/lib/libfmodexL64* "$UB_INSTALLDIR"/usr/lib/
cp -d api/inc/* "$UB_INSTALLDIR"/usr/include/fmodex

ln -s "$UB_INSTALLDIR"/usr/lib/libfmodex64-${UB_VERSION}.so "$UB_INSTALLDIR"/usr/lib/libfmodex.so.4
ln -s "$UB_INSTALLDIR"/usr/lib/libfmodexL64-${UB_VERSION}.so "$UB_INSTALLDIR"/usr/lib/libfmodexL.so.4
ln -sf libfmodex.so.4 "$UB_INSTALLDIR"/usr/lib/libfmodex.so
ln -sf libfmodexL.so.4 "$UB_INSTALLDIR"/usr/lib/libfmodexL.so
