#!/bin/sh -eux

if [ $UB_ARCH == "i386" ]; then
qmake -set QMAKE_XSPEC linux-g++-32
fi

export QT_CFLAGS+=" -fPIC -std=c++11"
export QMAKE_CXXFLAGS+=" -std=c++11"
./bootstrap
ub_compile \
	--with-qt=/usr/lib/qt5
