#!/bin/sh -eux

find . -type f | xargs sed -i 's@^#!.*python$@#!/usr/bin/python2@'
sed -i 's/python -c/$PYTHON -c/' configure.ac
sed -i 's/python/python2/' shell/plugins/PackageInstaller/__init__.py
autoreconf -vif
export PYTHON=python2
ub_compile \
    --disable-update-check
