#!/bin/sh -eux

cd py2
ub_install
cd ../py3
ub_install
mkdir -p $UB_INSTALLDIR/usr/share/doc/Packages/python3-gst
cp ChangeLog COPYING TODO $UB_INSTALLDIR/usr/share/doc/Packages/python3-gst/
cp ChangeLog COPYING TODO ../
