#!/bin/sh -eux

cd sphinx
python2 setup.py install --root="$UB_INSTALLDIR"
cd ../sphinx3
python3 setup.py install --root="$UB_INSTALLDIR"
cp CHANGES LICENSE README.rst ../
mkdir -p ${UB_INSTALLDIR}/usr/share/doc/Packages/python3-sphinxcontrib-websupport
cp CHANGES LICENSE README.rst ${UB_INSTALLDIR}/usr/share/doc/Packages/python3-sphinxcontrib-websupport/
