#!/bin/sh -eux

#eliminate gcc-9.10 warnings
export CXXFLAGS='-Wno-class-memaccess -Wno-misleading-indentation -Wno-stringop-truncation -Wno-stringop-truncation -Wno-deprecated-copy -Wno-implicit-fallthrough -Wno-shift-negative-value -Wno-ignored-qualifiers -Wno-maybe-uninitialized -Wno-int-in-bool-context'

ub_compile \
        -DFMOD_LIBRARY=/usr/lib/libfmodex.so \
        -DFMOD_INCLUDE_DIR=/usr/include/fmodex \
        -DGME_INCLUDE_DIR=/usr/include/gme \
        -DFORCE_INTERNAL_GME=OFF
