#!/bin/sh -eux

export SETUPTOOLS_SCM_PRETEND_VERSION=$UB_VERSION
python3 setup.py install --root="$UB_INSTALLDIR"
mv ${UB_INSTALLDIR}/usr/lib/python3.8/site-packages/Automat-0.3.0-py3.8.egg-info ${UB_INSTALLDIR}/usr/lib/python3.8/site-packages/Automat-${UB_VERSION}-py3.8.egg-info
sed "s/Version: 0.3.0/Version: ${UB_VERSION}/" -i ${UB_INSTALLDIR}/usr/lib/python3.8/site-packages/Automat-${UB_VERSION}-py3.8.egg-info/PKG-INFO
